### ISSUE TITLE
enttecdmxusbopen - setting channel=NNN in config file isn't working

### ISSUE THREAD

**Issue by semerad** [mcallegari/qlcplus#1007]
Helo,
there is mistake in EnttecDMXUSBOpen::writeUniverse() . At first call
it replaces for example 128 channels set in conf file with standard number
of 512 channels.
At info output of enttecdmxusbopen is always 512 channels then.
With attached patch it starts working. It uses replace() with specifying number
of bytes to replace.
[odmx_channels.patch.txt](https://github.com/mcallegari/qlcplus/files/1484027/odmx_channels.patch.txt)

**Comment by mcallegari** [comment]
Hi, on GitHub the proper way to send patches is through a Pull Request.
In any case, I think the suggested patch is wrong anyway.
It does the same thing the existing code does, but introducing a -1 on universe size which is wrong.

Have you actually tested it ? Does it bring any benefit at all ? Does channel 511 work with your patch ?

**Comment by mcallegari** [comment]
[EDIT] I see your point now, but there's a but...
What's the sense of limiting channels to (let's say) 128 and then add fixtures above address 128 ?
This line shows QLC+ sends only the used channels to plugins:
https://github.com/mcallegari/qlcplus/blob/master/engine/src/inputoutputmap.cpp#L306

In any case, the replace call changes the m_universe array length, which is not right. I'll fix it.

**Comment by mcallegari** [comment]
Applied 64c2d269d2d4208105849704ab7279668c312df0

**Comment by semerad** [comment]
On Sat, Nov 18, 2017 at 11:40:04AM +0000, Massimo Callegari wrote:
> [EDIT] I see your point now, but there's a but...
> What's the sense of limiting channels to (let's say) 128 and then add fixtures above address 128 ?
> This line shows QLC+ sends only the used channels to plugins:
> https://github.com/mcallegari/qlcplus/blob/master/engine/src/inputoutputmap.cpp#L306

  When You send only used channels to enttecdmxusbopen, that plugin still
sends 512 channels to hardware (when You don't set channels= to another
value - which isn't working correctly now).
  And it isn't my code, I am trying to make it working correctly only :-) .
> 
> In any case, the replace call changes the m_universe array length, which is not right. I'll fix it.

  I am looking at your commit, and You omitted "-1" thing. It should be
there, because m_universe array has size "number_of_channels + 1" :

  m_universe = QByteArray(channels + 1, 0);

Look at EnttecDMXUSBOpen::additionalInfo() for showing number of
channels also:

  info += QString("<B>%1:</B> %2").arg(tr("DMX Channels")) .arg(m_universe.size()-1);

In EnttecDMXUSBOpen::writeUniverse() it is replacing m_universe from
index 1 and not from beginning (0) so it is needed to replace one less
than is m_universe.size() .

  What it is doing now: it grows m_universe size by one every frame
till max size 512 and we are back where we were before (it takes more
steps now, before it was 1 step only) :
  first frame it replaces 128 bytes with 129
  second frame 129 with 130
  ...

  To be sure, I compiled actual git version, run qlcplus with
channels=128 . First time I looked for plugin info, I saw 399
channels and second time full 512 channels already .

  That additional zero byte is there to send "one-byte Start Code" of
DMX protocol. It is in m_universe to handle it the same as DMX values
probably (at EnttecDMXUSBOpen::run() loop).

  So please use "m_universe.size() - 1" in replace() to make it working
correctly.

  And OK, some possible next time i will try to clone repository and send
request to merge it, after I will learn how to do it :-) .

Pavel Semerad

**Comment by mcallegari** [comment]
You're right. Fixed b45a9821354792fc981aa254d9cbb8b78aa07ae1
