### ISSUE TITLE
udmx enhancement - new conf variable channels=NNN

### ISSUE THREAD

**Issue by semerad** [mcallegari/qlcplus#1008]
Helo,
when trying udmx interface I found it isn't smooth when fading in/out.
This interface is using Low-Speed USB only, which means speed of 12Mbit/s only.
Qlcplus sends all 512 bytes every frame to udmx and udmx can work at 15Hz only then
(taken from https://www.illutzmination.de/udmx-timing.html).
So I am suggesting conf variable channels=NNN as it is in enttecdmxusbopen already.
With attached patch it works well with channels=128 and frequency=50 .
[udmx_channels.patch.txt](https://github.com/mcallegari/qlcplus/files/1484062/udmx_channels.patch.txt)
Another solution can be to send only changed values to udmx, but it will be much more
difficult to do.

**Comment by mcallegari** [comment]
Applied, thanks. aabd4b098bc5dd888b76e97e8d3ae651d902b092
Next time please send a Pull Request though
