### ISSUE TITLE
Only Console version

### ISSUE THREAD

**Issue by ramonberrutti** [mcallegari/qlcplus#1009]
Hi, I want to start the app in a Ubuntu Server. (No gui)

I start with: 
`qlcplus --nowm --nogui --web`

but I get:
`qlcplus: cannot connect to X server`

**Comment by siegmund42** [comment]
Hey, have a look at [this thread](http://www.qlcplus.org/forum/viewtopic.php?f=7&t=9978&p=43673)
Please search the forum and post your questions there in the future.

**Comment by ramonberrutti** [comment]
Yes, thanks. I solved with xvfb :)
