### ISSUE TITLE
Ungraceful handling of failure to open /dev/snd/seq

### ISSUE THREAD

**Issue by rewolff** [mcallegari/qlcplus#1021]
I'm working on a pi, and I hate adding -l pi everytime I need to login to that box, so I've created an account under my normal username. So I had not yet added myself to group "audio" and got: 
`ALSA lib seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: Permission denied
`
This causes the mainwindow to come up but not display anything but leftover garbage from what used to be there. (I work over SSH on another Linux machine for display). 

UPDATE: I honestly only changed the permissions on the device retried and then it worked. 
It seems it works alternatingly. Once it works, once it doesn't work and so on.

**Comment by mcallegari** [comment]
Roger, I kindly ask you to be more precise if you report issues and want me to take them into account.
> adding -l pi everytime I need to login to that box

What are you talking about ? Adding to what ?
SSH login to a host is simply: ssh username@IPaddress

> I've created an account under my normal username

What does this even mean ? Added where ? What is a 'normal' username ? Are there 'special' ones too ?

Also, which QLC+ version are you using ? 
Did you build it yourself ? 
If so, Qt4 or Qt5 ?
On which Raspberry Pi distribution are you working ?

**Comment by rewolff** [comment]
To login as user pi, you can add " pi@ " in front of the hostname. Or add "-l pi" at the end. Even though the latter has 4 (5?) characters to type,  it is quicker if you notice it after typing the hostname/ip address. 

All that is irrelevant to qlc+ and the problem at hand. I was just trying to clarify why I ended up on a raspbian install without the permission to access /dev/seq/... 

I compiled myself on "Raspbian GNU/Linux 9" (according to /etc/issue.net), which seems to be called "stretch" in other places. I used QT5, and manually enabled "uart" plugin because that's what I was intending to use. 

I used the version from github, **Your branch is up-to-date with 'origin/master'.**

**Comment by mcallegari** [comment]
To be honest I haven't started to work on Stretch yet. However, seeing the growing demand for QLC+ on it, I really need to spend some time to port my image on Stretch. (right now I provide a Jessie based image)

Speaking of that, I took the liberty to add your email address to the distribution list of the QLC+ RPi image. Curious that I didn't do it before, since you guys provided the DMX hat in the first place. It includes the UART plugin.

As for ALSA, QLC+ on Qt5 uses the QtMultimedia module to provide audio/video playback, so QLC+ doesn't have a direct relationship with ALSA. Qt has.
If you added an extra user, you should check the difference with the 'pi' user. For example, doing
`cat /etc/group`
should show which groups 'pi' belongs to. Your user should belong to the same groups.

I don't recall reports of the ALSA errors on the RPi with my image, so you should try that first.

**Comment by mcallegari** [comment]
[EDIT] /dev/snd/seq is the MIDI sequencer !
So it's definitely the MIDI plugin, and it does have direct calls to the ALSA sequencer.
If you don't use a MIDI controller, you can move the MIDI plugin away so QLC+ will not load it on startup.
It is located here:
`/usr/lib/qt4/plugins/qlcplus/libmidiplugin.so`
Note that 'qt4' is still used for historical reasons, but it's perfectly fine also for Qt5

**Comment by rewolff** [comment]
You are latching onto the wrong things. 
It is annoying to get a bug report: "I tried running your program and it doesn't work". 
So.... I try to provide some context. 

In short: I got QLC to "fail" (screen contents never updated, only garbage what was "behind" the window). I then examined the output in the terminal where I started qlcplus. I saw an error message, dealt with the error message and tried again. Voila! No misbehaving qlcplus! 

So I reported the error, but also explained how I got there. You do not need to tell me that pi@<ipaddress> will log me in as pi. I know that. I personally often use the other syntax, but that doesn't matter. When I get fed up with typing that username, I follow several different paths. Sometimes I add the user name to .ssh/config. Somtimes I add the other user. This time I added a user. 

Then, of course I run into various things that the raspberry pi image already has taken care of for the pi user. I can fix that. For example, at first I didn't have sudo rights. Fixed. Then I ran into this "i'm not in the audio users group". I fixed that. But at that point in time I thought I'd do you a favor and report the problem I had found. When a "permission denied" happens to a graphical program it should not "hang" the GUI as it did. Sure, the exact way that things started to happen on my raspberry are not likely to repeat. But sometimes a bug that shows up in one case, will also happen in other cases. In the case at hand, maybe tailure to open other devices could trigger the same behaviour. 

All this is moot though. Somehow, it looks as if the bug toggles and has nothing to do with the device opening or not opening. I have reported that but you ignore it. 
I'm explaining how I (thought I)  triggered a bug, but you keep talking about all the circumstances that I described that might help you trigger hte bug on your system. Maybe just logging in as "pi" or giving myself permission on the device causes the bug to not show on my system. But it doesn't fix the bug. The bug is that QLCPLUS may under some circumstances show a non-functioning gui. At first I reported that I thought "failure to open the seq device" triggered it, but after some more trials that appears to be not the case.
