### ISSUE TITLE
[VC] Changing knob appearence to slider limits max value

### ISSUE THREAD

**Issue by siegmund42** [mcallegari/qlcplus#1029]
I discovered an issue regarding the knob/slider widget. Just put a knob on the vc (controlling a function of your choice). If you use it, the output value is adjusted as expected. After changing its appearance to be a slider, you can't get the output value to be over 99.
Changing back the appearance gives a working knob again.
Slider is working as expected, when it is created directly by the "new slider" button, but the problem reoccurs after the appearance was changed once.

**Comment by mcallegari** [comment]
This affect Playback mode only.
Level mode works as expected.
