### ISSUE TITLE
[VC] Using mousewheel over knob not working

### ISSUE THREAD

**Issue by siegmund42** [mcallegari/qlcplus#1030]
I discovered a bug while trying to control a knob widget using the mouse wheel. Just put a knob on the vc and let it control a function of your choice. Using click&drag works as expected, using the mouse wheel will change the appearance of the knob (value increasing) but has no effect on the DMX output.
Using the mouse wheel over the slider widget works as expected.

**Comment by mcallegari** [comment]
Fixed, thanks
