### ISSUE TITLE
Please provide AppImage for download on GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [mcallegari/qlcplus#1032]
https://github.com/mcallegari/qlcplus/blob/cc1e5e9a5c1016dce2904dba4f99aba19be308ba/create-appimage.sh#L3

Please provide a readymade AppImage for download on GitHub Releases. Thanks!

**Comment by mcallegari** [comment]
Huh ?
http://www.qlcplus.org/downloads.html

**Comment by probonopd** [comment]
Thanks. Unfortunately the AppImage does not run because a required library is not correctly bundled:

`qlcplus-qml: error while loading shared libraries: libpulse-mainloop-glib.so.0: cannot open shared object file: No such file or directory`

**Comment by mcallegari** [comment]
Distro ?

**Comment by probonopd** [comment]
Ubuntu 14.04 (trusty) on Travis CI:
https://travis-ci.org/AppImage/appimage.github.io/builds/348720782#L586

**Comment by probonopd** [comment]
> I bundled 5.9.4 which is quite recent, and I'm not even sure they ever targeted Ubuntu 14.04.
My recommendation is to use Qt from the beineri ppa as shown on https://github.com/probonopd/linuxdeployqt/#using-linuxdeployqt-with-travis-ci. I never had issues with it.

**Comment by mcallegari** [comment]
I already use it on Travis: https://github.com/mcallegari/qlcplus/blob/master/.travis.yml#L49
However, I haven't attempted an AppImage creation on Travis. Care to help ?

**Comment by probonopd** [comment]
I would suggest to copy&paste https://github.com/probonopd/linuxdeployqt/#using-linuxdeployqt-with-travis-ci and work from there. Maybe do this in a separate branch. Your current `.travis.yml` is already pretty large and I am afraid of ruining it...

**Comment by mcallegari** [comment]
@probonopd I've already received 2 reports of undefined symbols. Example:
http://www.qlcplus.org/forum/viewtopic.php?f=35&t=11962

This means those users have a libqlcplusengine.so library in their system, which is not binary compatible with the on bundled in the AppImage.
Now the question is: isn't AppImage supposed to export its internal paths to have the precedence over system paths and eventually fall back ?
I am confused, but this is not working for me.

**Comment by probonopd** [comment]
> This means those users have a libqlcplusengine.so library in their system, which is not binary compatible with the one bundled in the AppImage.

Quite possibly.

> Now the question is: isn't AppImage supposed to export its internal paths to have the precedence over system paths and eventually fall back?

`linuxdeployqt` is supposed to patch the RPATH in executables and libraries so that libraries from within the AppImage get loaded with preference over those in the base system. Apparently this is not working properly for `qlcplus-qml`, so that it is not looking for `libqlcplusengine.so` at the correct path inside the AppImage.

Can you please upload a build made on Ubuntu Trusty on Travis CI as described on https://github.com/probonopd/linuxdeployqt/#using-linuxdeployqt-with-travis-ci ? Then I can have a look at it. Thanks.

**Comment by mcallegari** [comment]
> linuxdeployqt is supposed to patch the RPATH in executables and libraries so that libraries from within the AppImage get loaded with preference over those in the base system. Apparently this is not working properly for qlcplus-qml, so that it is not looking for libqlcplusengine.so at the correct path inside the AppImage.

That's exactly what I meant to do with this:
https://github.com/mcallegari/qlcplus/blob/master/create-appimage.sh#L25

> Can you please upload a build made on Ubuntu Trusty on Travis CI as described on https://github.com/probonopd/linuxdeployqt/#using-linuxdeployqt-with-travis-ci ? Then I can have a look at it. Thanks.

I'll try my best, but my spare time is limited and linuxdeployqt didn't work for me when I used it manually on my PC

**Comment by mcallegari** [comment]
@probonopd almost there, but as expected, linuxdeployqt is making my life harder
This is the log: https://travis-ci.org/mcallegari/qlcplus/jobs/350540572
Desktop file is installed here: https://travis-ci.org/mcallegari/qlcplus/jobs/350540572#L4487
So why is linuxdeployqt complaining about it ?

**Comment by probonopd** [comment]
```
Desktop file as first argument: "appdir/usr/share/applications/qlcplus.desktop"
ERROR: Desktop file in first argument does not exist!
```

Are you 100% certain that there is `appdir/usr/share/applications/qlcplus.desktop`(relative to the current working directory)? Seems like it can't find it there.

**Comment by mcallegari** [comment]
Found it. I basically copied your [instructions](https://github.com/probonopd/linuxdeployqt/#using-linuxdeployqt-with-travis-ci) for Qt deployment, but while they might work for a simple project, they won't for a complex one like mine with lot of subfolders.
This is basically wrong:
`make INSTALL_ROOT=appdir -j$(nproc) install`
because INSTALL_ROOT should be an absolute path, otherwise every time `make` enters a folder, it will create a LOCAL appdir folder. This worked for me:
```
TARGET_DIR=~/qlcplus.AppDir
make INSTALL_ROOT=$TARGET_DIR install
```
Please adjust your instructions before other people will waste their time like I did.

Now Travis goes a little bit further, but linuxdeployqt still fails to resolve libraries.
I'm about to give up, as this is taking me too much time and to be honest I don't have a particular interest in CI of an AppImage bundle.

**Comment by probonopd** [comment]
Thanks for pointing this out. Do you think 

```
make INSTALL_ROOT=$( readlink -f appdir) -j$(nproc) install
```

would do the trick?

**Comment by probonopd** [comment]
> Now Travis goes a little bit further, but linuxdeployqt still fails to resolve libraries.

Can they be found by `ldd`?

**Comment by mcallegari** [comment]
> Thanks for pointing this out. Do you think
mkdir ./appdir ; make INSTALL_ROOT=$(readlink -f ./appdir) -j$(nproc) install
would do the trick?

No. ./appdir is a relative path. You need to use an absolute one

**Comment by mcallegari** [comment]
Sorry but I'm gonna abandon this.
linuxdeployqt doesn't really work for me.
In any case I think for the final release of QLC+ 5 I will switch to snap, since most distros have already adopted it and looks like it's becoming the next packaging standard.

**Comment by probonopd** [comment]
@mcallegari I am trying to help you but I need your collaboration for it to work;

> Can the libraries be found by `ldd`?

**Comment by mcallegari** [comment]
> Can the libraries be found by ldd?

This is the error:
https://travis-ci.org/mcallegari/qlcplus/jobs/350966796#L7260
And this makes clear that the library can be found:
https://travis-ci.org/mcallegari/qlcplus/jobs/350966796#L4512

most likley `unset LD_LIBRARY_PATH` is a mistake on Travis since Qt is in /opt. I copied that too from your example.

In general, if you'e only goal is to include my application in some sort of hub, here's where you can find a working bundle: http://www.qlcplus.org/downloads.html

If I am forced to provide an AppImage through Travis and GitHub, then sorry, but I have no time for this.
Plus, these are alpha releases, not ready for production, so I don't want them to be included anywhere as if they were final releases. I am months away from that.

**Comment by probonopd** [comment]
> If I am forced to provide an AppImage through Travis and GitHub, then sorry, but I have no time for this.

You are not, by any means. It's just that personally I find Travis and GitHub most convenient for collaborative development and debugging.

**Comment by probonopd** [comment]
I see that as part of the build

```
/opt/qt59/bin/qmake -install qinstall /opt/qt59/qml/QtQml /home/travis/qlcplus.AppDir/usr/bin/QtQml
/opt/qt59/bin/qmake -install qinstall /opt/qt59/qml/QtQuick /home/travis/qlcplus.AppDir/usr/bin/QtQuick
/opt/qt59/bin/qmake -install qinstall /opt/qt59/qml/QtQuick.2 /home/travis/qlcplus.AppDir/usr/bin/QtQuick.2
/opt/qt59/bin/qmake -install qinstall /opt/qt59/qml/Qt3D /home/travis/qlcplus.AppDir/usr/bin/Qt3D
```

is going on. I wonder whether it is correct that these things go to `usr/bin/` in the AppDir. Where do they go in a normal installation? Are those binaries that are executed during usage of the main application?
