### ISSUE TITLE
[Windows] Show manager time cursor doesn't move

### ISSUE THREAD

**Issue by mcallegari** [mcallegari/qlcplus#1033]
Reported here
http://www.qlcplus.org/forum/viewtopic.php?f=35&t=11963

I don't even need to confirm this. I already know for misterious reasons Qt5 style signals connect don't work on Windows (at least on MSYS2)
https://github.com/mcallegari/qlcplus/blob/master/qmlui/showmanager.cpp#L64
https://github.com/mcallegari/qlcplus/blob/master/qmlui/showmanager.cpp#L71
https://github.com/mcallegari/qlcplus/blob/master/qmlui/showmanager.cpp#L195

**Comment by janosvitok** [comment]
We use QT5 style signals in my day job exclusively since at least August 2017 and we haven't had a problem. MSVC 2015 and later 2017, 32bit, QT 5.8 later 5.9.

**Comment by janosvitok** [comment]
You may try to assert or log return value of connect (after conversion to bool): if (!connect(...)) log something.
You may also try to save the QMetaObject::Connection (return value from connect) and use it in disconnect().


Off topic: since you can use C++11 stuff in QLC+5, you can replace NULL with nullptr in qml dir...

**Comment by mcallegari** [comment]
The Windows version is built on MSYS2 and Qt is built by me to avoid ICU dependency.
Qt is heavily patched on MSYS2 and I'm afraid they broke something.
I might give a try to the official MINGW version and see if that works.
In any case, the new Qt5 style connect works correctly on Linux and macOS, so this seems to be Windows specific

**Comment by janosvitok** [comment]
I quickly skimmed over the patches and didn't find anything suspicious.

**Comment by mcallegari** [comment]
Now that I think about it, if I recall correctly, Qt5 style connects don't work from the qlcplusengine library, but they work from within the same "target". If even built Qt examples using them and they were working.
Not sure if there's some build flag missing in the engine, but this behaviour is really strange
