### ISSUE TITLE
[engine] rework monitor properties

### ISSUE THREAD

**Issue by mcallegari** [mcallegari/qlcplus#1041]
The plan is [documented here](https://docs.google.com/document/d/12EFNdONL8xCb6ClJdnqb3x8ckA6bGefdP21zdZ4HpPM/edit?usp=sharing).
When completed, this should address also #1040.

Now that the 3D preview is in, there's a limitation in the current MonitorProperties implementation.

Right now the MonitorProperties "key" parameter is Fixture ID, but a Fixture can have multiple heads (e.g. dimmer packs, PAR stands, multi head moving heads, etc)
In the real world, each head has a physical object representation. Right now one single 3D item represents a multi head fixture, which is no good.
This is kind of an issue in 2D as well. Again, one item represents several heads.

It is necessary to rework MonitorProperties to support heads.

**Comment by mcallegari** [comment]
@janosvitok I've linked a document with the implementation plan for this rework.
Can you please have a look at it and see if it can cover all the cases, or if it can lead to implementation nightmares ?
Thanks

**Comment by mcallegari** [comment]
I won't add a class when I can use macros.

```
#define FIXTURE_ID(x) (((x) >> 16) & 0xFFFF)
#define FIXTURE_LINKED_INDEX(x) (((x) >> 8) & 0xFF)
#define FIXTURE_HEAD_INDEX(x) ((x) & 0xFF)
```

**Comment by janosvitok** [comment]
With macros you don't gain anything these days, you just lose type safety, readability and maintainability.
Disclaimer: I didn't check assembly code yet :)

**Comment by mcallegari** [comment]
Hilarious...
I don't even know why I get paid since I use macros in C since 15 years...

**Comment by mcallegari** [comment]
I changed my mind, updated the doc, implemented and committed.
All without using a single macro...so the professor should be happy :wink:

**Comment by mcallegari** [comment]
Declaring this complete for now. Bugfix and further enhancements can come later.
