### ISSUE TITLE
ShutterOpen crash on high capability value

### ISSUE THREAD

**Issue by fxedel** [mcallegari/qlcplus#1063]
Steps to reproduce:

1. In JB-Lighting-Varyscan-P7.qxf: Remove all capabilities after "191-191: ShutterClose" and enlarge that capability to:
```xml
<Capability Min="191" Max="255" Preset="ShutterClose">Closed</Capability>
```
2. Apply fixture changes (either by `make` or moving into user's fixture directory)
3. Start QLC+
4. Create a JB-Lighting Varyscan P7 fixture (1st mode)
5. Add this fixture to 2D monitor
6. Set channel 6 (Shutter) to 241 or greater
7. **QLC+ crashed!** Console output:
```
ASSERT failure in QList<T>::at: "index out of range", file /usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h, line 541
Abgebrochen (Speicherabzug geschrieben)
```

Selecting a high value in ShutterClose capabilities makes QLC+ crash. This only happens if the capability is greater; the "0-4: ShutterClose" capability in ADJ Auto Spot 150 doesn't make any problems.

Tested with commit fb1787c2 and QLC+ 4.

**Comment by mcallegari** [comment]
Should be fixed now. Thanks for reporting
