### ISSUE TITLE
Infinite Pan/Tilt with the new fixture definitions

### ISSUE THREAD

**Issue by fxedel** [mcallegari/qlcplus#1070]
I'm wondering how to properly describe continuous (infinite, endless) pan/tilt movement with the new QLC+ fixtures.

There are some channel presets for pan/tilt speed, but even though they are used in [American DJ XS 600](https://github.com/mcallegari/qlcplus/blob/0c1e1fe48a618f057d43b521e7309ef9f49079ec/resources/fixtures/American_DJ/American-DJ-XS-600.qxf) to represent continuous pan/tilt speed, I recognize them more like a general motor (reaction) speed used in combination with PanPosition or TiltPosition:
```
SpeedPanSlowFast
SpeedPanFastSlow
SpeedTiltSlowFast
SpeedTiltFastSlow
SpeedPanTiltSlowFast
SpeedPanTiltFastSlow
```

As of capability presets, there's only the (never-used) `TiltContinuous` preset. Why not `PanContinous`? And what about directions and speed? I'd suggest these capability presets instead:
```
PanContinuous
PanContinuousSlowToFast
PanContinuousFastToSlow
PanContinuousStop
PanContinuousCounterClockwise
PanContinuousCounterClockwiseSlowToFast
PanContinuousCounterClockwiseFastToSlow
TiltContinuous
TiltContinuousSlowToFast
TiltContinuousFastToSlow
TiltContinuousStop
TiltContinuousCounterClockwise
TiltContinuousCounterClockwiseSlowToFast
TiltContinuousCounterClockwiseFastToSlow
```

Sure, these are many presets. But as both direction and speed is included, QLC+ could visualize continuous pan / tilt properly (or at least there's the future opportunity to do that). See the [Elation ACL 360 Roller](https://open-fixture-library.org/elation/acl-360-roller) which would immediately benefit from these new presets!

I don't think any new channel presets are needed, as continuous rotation typically requires more than one capability.

One last thing about physical data: We're currently about to allow "infinite" as possible value for `panMax`/`tiltMax` in OpenLightingProject/open-fixture-library#515. Maybe that'll also be something for QLC+?

cc @FloEdelmann

**Comment by mcallegari** [comment]
The idea of capability presets is to combine them with the channel type.
If the channel is "Pan" type, saying "ContinuousSlowToFast" is enough to tell it refers to the pan motor.

The problem can eventually comes when the channel is called "Pan & Tilt speed" and there are multiple capabilities. I have no idea if there are fixtures with such issue though.

> One last thing about physical data: We're currently about to allow "infinite" as possible value for panMax/tiltMax in OpenLightingProject/open-fixture-library#515. Maybe that'll also be something for QLC+?

No. Fixture with continuous rotation usually have also a range for pan and a range for tilt. We need that for the previews.
I prefer to "know" about continuous rotation from a channel capability and change it on the fly.

**Comment by fxedel** [comment]
> If the channel is "Pan" type, saying "ContinuousSlowToFast" is enough to tell it refers to the pan motor.

That's a good point! So let's stick to the Elation ACL Roller example. Its "Pan Continuous" channel looks like this:

```
  0 … 127 Nothing
128 … 189 Continuous pan CW fast…slow
190 … 193 Continuous pan stop 
194 … 255 Continuous pan CCW slow…fast
```

The channel type is "Pan" of course, but what would be the capability presets?

```
Nothing
RotationClockwiseFastToSlow
RotationStop
RotationCounterClockwiseSlowToFast
```

... would make most sense for me. That'll require these rotation presets (which could be used for gobo wheels, prism, etc. as well):

* `RotationClockwise`
* `RotationClockwiseSlowToFast`
* `RotationClockwiseFastToSlow`
* `RotationStop`
* `RotationCounterClockwise`
* `RotationCounterClockwiseSlowToFast`
* `RotationCounterClockwiseFastToSlow`
* (+ `Nothing`)

There still exists the never-used [`TiltContinuous`](https://github.com/mcallegari/qlcplus/blob/master/engine/src/qlccapability.h#L133) capability preset (`PanContinuous` doesn't exist) which should be removed then.

**Comment by mcallegari** [comment]
> There's still a bug: Most fixtures have this channel order:

Pan
Tilt
Pan Continuous Rotation
Tilt Continuous Rotation
...
The EFX function sets channel 3 and 4 then (which is incorrect, as it should access the angle by setting 1 and 2). I don't know how to fix this – maybe by changing something in qlcfixturehead.cpp#L171 or efxfixture.cpp#L98?

@fxedel I have just tried ADJ Asteroid in Basic and Standard mode and EFX controls the right channels (1 and 2)
Where did you see the wrong behaviour ?

**Comment by fxedel** [comment]
@mcallegari I can't reproduce the behavior either; so this seems to be fixed somehow.
