### ISSUE TITLE
[plugins] artnet error compiling with GCC8

### ISSUE THREAD

**Issue by susnux** [mcallegari/qlcplus#1075]
Using gcc8 compiling qlc+ (4 and 5) will not work because of this lines in the artnet plugin:

        if (type == Output && ((this->type() | Output) == 0))

the issue:

    artnetcontroller.cpp:146:56: error: bitwise comparison always evaluates to false [-Werror=tautological-compare]

`Type::Output` is not 0 and because of this everything you OR with it (here `this->type()`) will be `!= 0`, so the `if` is never true!

**Comment by mcallegari** [comment]
Wow, nice catch GCC 8 !
It is indeed a wrong line of code, and if I interpret it right I think it was meant to be
`if (type == Output && ((this->type() & Output) == 0))`
However at the moment I don't have the chance to test it, so it's a blind guess ATM.

**Comment by janosvitok** [comment]
My guess: the code in question wants to determine whether there are any open output universes (see also [type()](https://github.com/mcallegari/qlcplus/blob/master/plugins/artnet/src/artnetcontroller.cpp#L65).
If there are no open outputs, the timer is not needed anymore.

I vote for
```c++
if (type == Output && ((this->type() & Output) == 0))
```

I'd:
1. make ArtnetController::type() *const*
2. add
```c++
bool ArtnetController::isAnyOutputOpened() const {
    return (type() & Output) == Output;
}
```
3. change the condition to
```c++
if (type == Output && !isAnyOutputOpened())
```

**Comment by susnux** [comment]
Then why not make it unambiguous?
Why using complicate (to understand) and use bitwise compares, instead of simple:

    if (type == Output && this->type() != Output)

The bitwise compare does not provide any speed benefits, instead it makes it harder to understand the intention of the developer when writing this if condition.

**Comment by janosvitok** [comment]
@susnux: this->type() is a bitmask that may be Input, Output or both.
