### ISSUE TITLE
QLC+ 5 translations

### ISSUE THREAD

**Issue by mcallegari** [mcallegari/qlcplus#1076]
@kripton @siegmund42 @fxedel @sbenejam @tornel @jeromelebleu @nils-van-zuijlen @magcho @joepadmiraal 

Hey guys, it's about time to start translating QLC+ 5 ! :tada: 
I have laid ground for it and there are already 764 strings to translate in qmlui.
This time, thanks to QtQuick, it is possible to change the language from within QLC+ without restarting the application !
I have already created a submenu for the most maintained languages.
![image](https://user-images.githubusercontent.com/2951337/42411210-77711f7a-81f8-11e8-903f-0a9579ce6f41.png)

If you have some time and are willing to contribute, just add your language here: [qmlui.pro#L146](https://github.com/mcallegari/qlcplus/blob/master/qmlui/qmlui.pro#L146)
For example
```
TRANSLATIONS += \
    qlcplus_it_IT.ts \
    qlcplus_xx_YY.ts
```
Then run `lupdate qmlui.pro` and your new translation file will be created.
Then use Qt Linguist on it as usual.
I haven't found a smart way to use existing translations from the QLC+ 4 UI. If someone find a way, please let us know here.
I am evaluating to move translations over to Transifex to attract new translators, but for now let's go the hardcore way since you guys are already familiar with that.

If you have questions, please shoot. I'm here to help.

Thanks in advance !

**Comment by fxedel** [comment]
@mcallegari I've just created an AppImage with the newest code, but I don't see the "Language" menu item. `make distclean` didn't help. Do I have to do another "clean"?

**Comment by mcallegari** [comment]
@fxedel the change is indeed upstream [ActionsMenu.qml#L416](https://github.com/mcallegari/qlcplus/blob/master/qmlui/qml/ActionsMenu.qml#L416)
Maybe remove the AppImage target folder and try again ?

**Comment by fxedel** [comment]
@mcallegari I hadn't got the latest Qt version, that caused `make` to fail at some point (and obviously use an older build instead).

With Qt 5.11, I can see the new Languages menu, but choosing a language doesn't work – neither German nor Italian works, QLC+ remains English.

**Comment by janosvitok** [comment]
It seems that a translation glossary would be useful. I saw in Czech translation that the same thing was translated in differently in different places -- the translator(s) used synonyms. It would be better to use one term for one thing.

For start, a table with words from glossary from online help and translations in various languages may be useful...

**Comment by fxedel** [comment]
@janosvitok Maybe it would also make sense to reuse translation strings, i. e. by extracting `qsTr("Red")` calls into another class as constant? This would decrease the amount of translation work.

**Comment by mcallegari** [comment]
> Maybe it would also make sense to reuse translation strings, i. e. by extracting qsTr("Red") calls into another class as constant? This would decrease the amount of translation work.

There are 2 occurences of "Red".

**Comment by nils-van-zuijlen** [comment]
I wonder if the languages names in the UI should be in English or in the language they show.
("English" in English, "Français" in French, "Español" in Spanish, etc.)
This will ease the process of changing language for non English people.

**Comment by mcallegari** [comment]
> I wonder if the languages names in the UI should be in English or in the language they show.
("English" in English, "Français" in French, "Español" in Spanish, etc.)
This will ease the process of changing language for non English people.

Please translate those too.

@everyone: there's something awkward with the VC Clock days of the week. For some reason, lupdate optimize in a wrong way (e.g. Tuesday and Thursday are both "T" and it keeps just one)
I need to check that, please do not translate.

**Comment by mcallegari** [comment]
Great ! All the preliminary languages are in ! Thanks everyone for contributing :+1:
