### ISSUE TITLE
Hotplug does not work when removing USB-DMX-device

### ISSUE THREAD

**Issue by AThomsen** [mcallegari/qlcplus#1086]
Arch Linux, latest QLCPlus.
Enttec USB DMX Pro.

Adding USB-devices works fine - hotplug monitor catches that and updates in/out devices.

However, when disconnecting the USB-device it is not caught.

The reason is that ID_VENDOR_ID and ID_MODEL_ID is not populated by udev when removing a USB-device.

See [here](https://pastebin.com/Z8ARsZqv) for the output of `udevadm monitor --udev --property`.

Properties are supplied for the TTY-device so perhaps a solution is to include these in the filter as well. Or perhaps just refresh whenever *some* USB device is removed.

**Comment by mcallegari** [comment]
Works as expected on Ubuntu 16.04.
You might have a Arch specific udev related issue. Or QLC+ udev rules are not installed correctly

**Comment by AThomsen** [comment]
Can confirm it works on Ubutnun 14.04 as well. And I can recreate my issue on another Arch installation. 

I'll dig into this some more...

**Comment by AThomsen** [comment]
I can confirm that it works in Ubuntu 14.04 as well as 16.04.
But in Ubuntu 18.04 it behaves as in Arch: adding devices work, but removing does not (in QLC). Udevadm does not show ID_VENDOR and ID_MODEL on remove actions, hence QLC skips the event.

@mcallegari - can you verify that this is an issue with Ubuntu 18.04? If so, there must be a bug in newer kernels/udev or behaviour has changed.

**Comment by mcallegari** [comment]
@AThomsen I have a 18.04 and I'll check when I can find some time

**Comment by AThomsen** [comment]
Look at this as I really need it.

@mcallegari, is  it strictly necessary to check for known VID/PID instead of just re-scanning when *something* is removed?  It seems like a fairly cheap operation to do.

**Comment by AThomsen** [comment]
Yeah, I thought at that too. I can't find the `PRODUCT` property documented anywhere though. Is it constructed in udev or does it come from straight the device, and can we be sure it works with all usb-dmx-dongles?
