### ISSUE TITLE
[Arch Linux] AUR build fails

### ISSUE THREAD

**Issue by checcoux** [mcallegari/qlcplus#1089]
I'm trying to build from sources with AUR the _qlcplus_ package but it throws this error:

> In file included from /usr/include/qt4/QtCore/qxmlstream.h:50,
                 from /usr/include/qt4/QtCore/QXmlStreamReader:1,
                 from audio.cpp:20:
/usr/include/qt4/QtCore/qvector.h: In instantiation of ‘void QVector<T>::realloc(int, int) [with T = QXmlStreamAttribute]’:
/usr/include/qt4/QtCore/qvector.h:337:3:   required from ‘void QVector<T>::detach_helper() [with T = QXmlStreamAttribute]’
/usr/include/qt4/QtCore/qvector.h:123:84:   required from ‘QVector<T>::QVector(const QVector<T>&) [with T = QXmlStreamAttribute]’
/usr/include/qt4/QtCore/qxmlstream.h:169:26:   required from here
/usr/include/qt4/QtCore/qvector.h:503:25: error: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of type ‘QVector<QXmlStreamAttribute>::Data’ {aka ‘struct QVectorTypedData<QXmlStreamAttribute>’} with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Werror=class-memaccess]
                 ::memcpy(x.p, p, sizeOfTypedData() + (qMin(aalloc, d->alloc) - 1) * sizeof(T));
                 ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/qt4/QtCore/qxmlstream.h:50,
                 from /usr/include/qt4/QtCore/QXmlStreamReader:1,
                 from audio.cpp:20:
/usr/include/qt4/QtCore/qvector.h:94:8: note: ‘QVector<QXmlStreamAttribute>::Data’ {aka ‘struct QVectorTypedData<QXmlStreamAttribute>’} declared here
 struct QVectorTypedData : private QVectorData
        ^~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[3]: *** [Makefile:287: audio.o] Error 1
make[3]: Leaving directory '/tmp/pamac-build-ux/qlcplus/src/qlcplus-4.11.2/engine/audio/src'
make[2]: *** [Makefile:76: sub-src-make_default-ordered] Error 2
make[2]: Leaving directory '/tmp/pamac-build-ux/qlcplus/src/qlcplus-4.11.2/engine/audio'
make[1]: *** [Makefile:41: sub-audio-make_default-ordered] Error 2
make[1]: Leaving directory '/tmp/pamac-build-ux/qlcplus/src/qlcplus-4.11.2/engine'
make: *** [Makefile:83: sub-engine-make_default-ordered] Error 2
==> ERROR: A failure occurred in build().

**Comment by mcallegari** [comment]
Don't build with Qt4. Build on Qt5.
https://github.com/mcallegari/qlcplus/wiki/Linux-build-Qt5
By the way, there's a forum for this kind of reports. I take you haven't even read the template message of GitHub issues I left here.
