### ISSUE TITLE
Can't register to the forum

### ISSUE THREAD

**Issue by Stefan531** [mcallegari/qlcplus#1136]
hello everyone,
First, I know this is not the good place for this issue but I can't find an other place to post about it.

I registered recently to the qlc+ forum and i don't receive the validation email.
I checked my spam and still nothing.
I tried to contact a board administrator but there's no way if I'm not logged in.

If someone can help me, i would be very thankful.
I registered twice (to be sure), with these usernames : 
stefan531 and stefan534
with two different email adresses...

Thank you very much in advance
Stefan

**Comment by mcallegari** [comment]
This is definitely the wrong place.
You should have sent an email to support@qlcplus.org

Anyway stefan531 is activated now.

**Comment by trebmuh** [comment]
@mcallegari : where, on the website and the forum part of this website, someone is supposed to find this email address?
I, for one, can find it.

**Comment by mcallegari** [comment]
https://www.qlcplus.org/forum/ucp.php?mode=resend_act

I received a few emails on support for activation issues, so I thought it was visible at some point during registration. However I checked and I can't seem to find it either, so I added it.

It's a HUGE problem for me to expose email addresses cause the forum is constantly under attack. I even started to receive spam on the PayPal email address and I have NO idea how to stop it. This means there are people around the world that have nothing better to do in their life other than spamming around for no reason.
I even investigated at some point, and I found out that they steal someone's email address, correctly activate in the forum and start sending non sense messages to the board. One day I logged in and there were 45 spam messages in the approval queue.

Again, this is a HUGE problem for me cause I've got other things in my life other than deleting emails from losers.

**Comment by trebmuh** [comment]
> However I checked and I can't seem to find it either, so I added it.

Nice.

> It's a HUGE problem for me to expose email addresses cause the forum is constantly under attack.

Yes, we're all on the same point. A usual work around can be:

- providing the address as a image file (ie: .png, .jpg, ...)
- providing the address but obfuscated (ie support HAT qlcplus DOT org)
- a third one could a mix such as support image-of-an-at-sign) qlcplus image-of-a-dot org
