### ISSUE TITLE
Mode flash with right click

### ISSUE THREAD

**Issue by Pablodjj** [mcallegari/qlcplus#1139]
This area is reserved to developers.
If you are not a developer, you are in the wrong place and your issue will be closed.

For discussions, feedbacks, ideas and new fixtures, go to:
http://www.qlcplus.org/forum/index.php
and provide as many details as possible regarding your findings.

Before reporting new issue, please discuss it on the forum. Let's keep the issues tidy!

If you are a developer, you are supposed to have built QLC+ from sources, and started to debug the issue you have found.

Therefore, please provide a crash log or references to the code that are supposed to help the QLC+ developers to resolve the issue.
Also, if your issue concerns a specific platform, please indicate it in the issue title like [platform] description.

**Comment by Pablodjj** [comment]
It is possible to implement flash mode by right clicking on the button (in virtual console).
Please, it's a function that I need a lot.

Sorry if this is not well located.

**Comment by mcallegari** [comment]
Please use the forums as indicated in the message you ignored.
