### ISSUE TITLE
Reconnecting USB messes up I/O assignment using two DMXUSB devices

### ISSUE THREAD

**Issue by matthijskooijman** [mcallegari/qlcplus#1150]
I'm using a DMX USB PRO and and DMX USB PRO Mk2 for doing DMX I/O. When testing how QLC would handle an usb connection failure, I noticed that when unplugging and replugging one or both devices, QLC would mess up the the I/O patching (e.g. end up using the MIDI input or output of my Mk2, which I had not selected previously).

I dug into the code and generated some debug output to figure out the problem here, but IIUC, QLC does I/O patching using a universe to "plugin + line number" mapping. Here, a line number is not a per-device line number, but a global line number, which spans all lines on all devices for a given plugin. So the line numbers assigned to a particular physical line are dependent on what DMXUSB devices are attached and in what order they are enumerated.

In my particular case, I believe the Mk1 device is sorted before the Mk2 device. If I then unplug the Mk1 device, the Mk2 device's line numbers will be shifted down, resulting in a wrong patch. What's a bit unexpected is that when unplugging the patch seems to remain correct, but when replugging it, the patch gets messed up (possible because lines are only reopened when a device is added, not when a device is removed?).

Did I understand how things work correctly? If so, then USB replugging can never be really reliable when multiple DMXUSB devices are used. Originally, I had expected to find some code that uses serial numbers and per-device line numbers to select the right output lines on startup and USB hotplugging? Or did I not look closely enough and is there some such code which is not behaving properly on my setup?

**Comment by mcallegari** [comment]
This should be addressed by b5c3dbb4c85255f71f250b19372de05bd044ed49

**Comment by matthijskooijman** [comment]
Cool, thanks! No time to look at the code, or even test now, but I might have another show in a few months, then I'll be sure to test :-)
