### ISSUE TITLE
[QLC+ forum] Unable to validate a change of e-mail address

### ISSUE THREAD

**Issue by nils-van-zuijlen** [mcallegari/qlcplus#1153]
Well, I know it is not the best way to report a problem with the forum. But I didn't found any other.

I have an account on the forum, named `nilsvanzuijlen`, and I have posted a bit with it in the past.

Today, I wanted to change the e-mail address associated with it, and it worked... in a way. It disconnected me, updated it in the database (seems like it, I am not able to use that e-mail to register because "The entered email address is already in use.").

But then, when I want to reconnect, I am greeted with a very unpleasant message: "The specified username is currently inactive. If you have problems activating your account, please contact a board administrator." So that's what I am doing by opening this issue, as I didn't found any other way.

PS: I checked my e-mails for an activation link, even in the spam folder, and I didn't receive any.

**Comment by nils-van-zuijlen** [comment]
If you can manually activate my account, or send me an activation link, it would be great.
You may ask if you need more information.

**Comment by mcallegari** [comment]
Activated

**Comment by nils-van-zuijlen** [comment]
Thank you
