### ISSUE TITLE
[fixture definition] add emitters layout parameters

### ISSUE THREAD

**Issue by mcallegari** [mcallegari/qlcplus#1156]
One more thing is needed in fixture definitions to help out the previews and avoid guessing.
As [mentioned here](https://github.com/OpenLightingProject/open-fixture-library/issues/581#issuecomment-414584829), the 2D preview tries to understand the heads layout by doing some spatial calculations.
However, this mechanism fails on several cases.

Moreover, there are 2 other cases not considered at all at the moment:
- some [blinders](https://www.thomann.de/gb/showtec_stage_blinder_4_dmx.htm) have multiple emitters, but they usually work together. Right now QLC+ shows just one emitter representing all of them
- fixtures have multiple operational modes, and across modes, heads can be different. Some LED bars have modes with a limited number of channels, but the light emitters are physically always the same.
Example 3 DMX channels: intensity, shutter, color macro --> 8 physical emitters.

The proposal is to add 2 new fields to physical properties to indicate the emitter matrix Width x Height.
In XML could be something like this in the `Physical` section:
`<Layout Width="8" Height="1" />`

The default will be 1x1 and if not changed, it won't even be saved in XML. This is to avoid changing all the current definitions and avoid to waste space.

@fxedel @FloEdelmann sounds good ?

**Comment by fxedel** [comment]
This definitely sounds good, as it will fix the pixel arrangement for many matrix heads!

`1x1` will result in the current behavior (ratio guessing)?

What if the amount of specified heads is higher or lower than `width*height`? Is this an error? And will empty heads be allowed now?

**Comment by mcallegari** [comment]
Leaving 1x1 and then definining let's say 6 heads, the latter will have precedence, as it is an explicit user setting.
Mode heads lower than physical heads could follow these rules:
- 1 head should never be defined cause it's the default. I've seen so many wrong definitions where users added all the channels to 1 head. No need. QLC+ implicitely define at least one head, and autodetects channels
- I've seen bars with DMX modes to group LEDs. Example: 8 physical emitters, 4 heads (or zones). The behaviour will be guessed and first head will control LED 1 & 2, seconds head 3 & 4 and so on.

At least, this is how they usually work. Edge cases will probably rest uncovered.

**Comment by FloEdelmann** [comment]
That sounds really nice to me! I guess this will be an addition to the `multihead` branch / QLC+ 5 fixture format?

**Comment by mcallegari** [comment]
Definitions are in common, so QLC+ 4/5.
Multihead branch, yes, that was the idea.

**Comment by fxedel** [comment]
@mcallegari That's pretty cool! The preview actually shows the correct pixel amount, even if only one channel is specified :+1:

I haven't noticed yet that you changed the spec to include width/head in the physical section, not in the heads section. This definitely makes sense!

Is it allowed (or recommended) to reuse a channel in the heads section? For example to define an even/odd mode:

```xml
 <Mode Name="Even/Odd">
  <Channel Number="0">Dimmer odd</Channel>
  <Channel Number="1">Dimmer even</Channel>
  <Head>
   <Channel>0</Channel>
  </Head>
  <Head>
   <Channel>1</Channel>
  </Head>
  <Head>
   <Channel>0</Channel>
  </Head>
  <Head>
   <Channel>1</Channel>
  </Head>
 </Mode>
 <Physical>
  <!-- ... -->
  <Layout Width="4" Height="1"/>
</Physical>
```

**Comment by mcallegari** [comment]
Layout is definitely a physical property. See the updated fixture editor panel:

![image](https://user-images.githubusercontent.com/2951337/48675633-9211ee00-eb5b-11e8-9a86-309632b10125.png)

Re-use channel in heads: doesn't make much sense to me from a pure definition perspective.
If that helps QLC+ preview though, maybe it could work. Never tried actually
