### ISSUE TITLE
[QLC+ forum] Cannot receive activation code

### ISSUE THREAD

**Issue by m-dhooge** [mcallegari/qlcplus#1165]
Hello,
I created an account (mdhooge) on the forum several days ago. But I cannot receive the activation e-mail.
It seems I'm not the only one with this problem: #1153. And, as Nils, I didn't found any other way to contact you: you need an active account to contact an administrator!
Sorry for the noise and thanks for your help.
M.

**Comment by mcallegari** [comment]
activated.
Months ago I added a message to contact support@qlcplus.org. Strange you didn't see it.
