### ISSUE TITLE
Martin MAC Encore Performance Gobos

### ISSUE THREAD

**Issue by FloEdelmann** [mcallegari/qlcplus#1169]
The [Martin MAC Encore Performance](https://open-fixture-library.org/martin/mac-encore-performance) is not yet included in QLC+ (but it could easily with the OFL export).

Its manual includes 4 nice vector gobos (and one glass gobo image) that seem to be not included in QLC+ yet:

![screenshot_2019-01-21_15-54-15](https://user-images.githubusercontent.com/202916/51481790-f8ea9800-1d94-11e9-9f3e-2cecf34ce93e.png)

I cleaned up the vector gobos (everything is one path now) and cropped the glass gobo image, but I don't know where to put them, because there is no Martin gobo folder. I'll just append them here; you'll surely know where to put them best :blush: 

[mac-encore-performance-gobos.zip](https://github.com/mcallegari/qlcplus/files/2779436/mac-encore-performance-gobos.zip)

**Comment by mcallegari** [comment]
Sorry for the delay. These go to "others".
If you can, please send a PR with the definition and the gobos. Thanks!

P.S. broken marble is 387kb ! :sob:
