### ISSUE TITLE
Add a stop poll artnet button 

### ISSUE THREAD

**Issue by hyndruide** [mcallegari/qlcplus#1170]
hi and thx for this cool application !!

when I use qlc+ with a fixture of my own creation, I use Arduino, esp8622 or esp32. with the artnetwifi or artnet library. I always receive poll but in fact the library are too simple to add poll answer so. can you add a button or do you have a way to avoid qlc+ artnet plugin to send this poll. because it slowdown the fixture and block communication. 

thx again for your program and sry for my beautiful English 
I'm a French guy...

**Comment by mcallegari** [comment]
Sorry but no, I won't implement such feature.
QLC+ is open source, so you can add it yourself to your personal copy.
Next time please use the forums.
