### ISSUE TITLE
[OSX] Picture not showing up with video function

### ISSUE THREAD

**Issue by gahujipo** [mcallegari/qlcplus#1211]
I was [pointed to use the video function to show a picture on a second screen](https://www.qlcplus.org/forum/viewtopic.php?f=5&t=9283&start=10#p58809) (e.g. a projector). This works on Windows. The OSX version is showing a black window:

<img width="1305" alt="Screenshot 2020-01-29 at 19 10 19" src="https://user-images.githubusercontent.com/26710574/73384319-562ff800-42cb-11ea-9d5c-3291c0ad9638.png">

It would be nice to have that feature on OSX too.

**Comment by mcallegari** [comment]
The linked reference doesn't say to use the Video function to show a picture. It says to use the Script function and launch Videolan.
Pictures are actually not supported in QLC+ 4. They are in QLC+ 5.
The fact it works on Windows is pure luck.

**Comment by gahujipo** [comment]
>The linked reference doesn't say to use the Video function to show a picture

well, not exactly, the linked answer says:

>Set it up as you would a video and set it to loop mode.

The next answer says to use Videolan. But it is quite some work to set up a project with many pictures in it. Would it be much work to implement picture support in QLC+ 4? Could maybe some of the code be adapted?

> Pictures are actually not supported in QLC+ 4. They are in QLC+ 5.

I tried alpha3 on OSX. At least the OSX version doesn't show a window when set to windowed and loop after pressing the preview button.

**Comment by gahujipo** [comment]
I wonder that I am the first who tries to show a picture with QLC+.

**Comment by JonnyTech** [comment]
Does anyone have a test project that shows videos working?
