### ISSUE TITLE
InputOutputMap test fails on ARM64 platform

### ISSUE THREAD

**Issue by MDAR** [mcallegari/qlcplus#1235]
Hi

Just a quick question

I have been trying  to compile QLCplus 4.12.2 on an ARM64 machine for a few months and have not been having much success.... until today...

I have now got an Odroid C4 with Ubuntu and it all went very well, right up until the testing phase, I believe just before it creates the DEB file.

Can you point me in the right direction to look further into this (and a hint as to what to look for would be nice)

(I'd love to have the PulseAudio side of things working too, but that is a different issue, for a different day)

Thank you.

This is the output from the testing phase

```

********* Start testing of InputOutputMap_Test *********
Config: Using QtTest library 5.12.8, Qt 5.12.8 (arm64-little_endian-lp64 shared (dynamic) release build; by GCC 9.3.0)
QWARN  : InputOutputMap_Test::initTestCase() PulseAudioService: pa_context_connect() failed
PASS   : InputOutputMap_Test::initTestCase()
PASS   : InputOutputMap_Test::initial()
PASS   : InputOutputMap_Test::pluginNames()
PASS   : InputOutputMap_Test::pluginInputs()
PASS   : InputOutputMap_Test::pluginOutputs()
PASS   : InputOutputMap_Test::configurePlugin()
PASS   : InputOutputMap_Test::inputPluginStatus()
PASS   : InputOutputMap_Test::outputPluginStatus()
PASS   : InputOutputMap_Test::universeNames()
QWARN  : InputOutputMap_Test::addUniverse() bool InputOutputMap::addUniverse(quint32) Universe 3 is already present in the list. The universe list may be unsorted.
PASS   : InputOutputMap_Test::addUniverse()
QWARN  : InputOutputMap_Test::removeUniverse() bool InputOutputMap::removeUniverse(int) Removing universe 1 would create a gap in the universe list, cancelling
PASS   : InputOutputMap_Test::removeUniverse()
PASS   : InputOutputMap_Test::universe()
PASS   : InputOutputMap_Test::profiles()
QWARN  : InputOutputMap_Test::setInputPatch() bool InputOutputMap::setInputPatch(quint32, const QString&, quint32, const QString&) Universe 4 out of bounds.
PASS   : InputOutputMap_Test::setInputPatch()
QWARN  : InputOutputMap_Test::setOutputPatch() bool InputOutputMap::setOutputPatch(quint32, const QString&, quint32, bool, int) Universe 4 out of bounds.
QWARN  : InputOutputMap_Test::setOutputPatch() bool InputOutputMap::setOutputPatch(quint32, const QString&, quint32, bool, int) Universe 4 out of bounds.
QWARN  : InputOutputMap_Test::setOutputPatch() OutputPatch* InputOutputMap::feedbackPatch(quint32) const Universe 42 out of bounds.
PASS   : InputOutputMap_Test::setOutputPatch()
PASS   : InputOutputMap_Test::setMultipleOutputPatches()
PASS   : InputOutputMap_Test::slotValueChanged()
PASS   : InputOutputMap_Test::slotConfigurationChanged()
PASS   : InputOutputMap_Test::loadInputProfiles()
PASS   : InputOutputMap_Test::inputSourceNames()
FAIL!  : InputOutputMap_Test::profileDirectories() 'dir.absolutePath().contains(USERINPUTPROFILEDIR)' returned FALSE. ()
   Loc: [inputoutputmap_test.cpp(628)]
PASS   : InputOutputMap_Test::claimReleaseDumpReset()
PASS   : InputOutputMap_Test::blackout()
PASS   : InputOutputMap_Test::grandMaster()
PASS   : InputOutputMap_Test::cleanupTestCase()
Totals: 24 passed, 1 failed, 0 skipped, 0 blacklisted, 587ms
********* Finished testing of InputOutputMap_Test *********
/opt/qlcplus/sourcecode/qlcplus-QLC-_4.12.2
1 Engine unit tests failed. Please fix before commit.
make[1]: *** [Makefile:603: check] Error 1
make[1]: Leaving directory '/opt/qlcplus/sourcecode/qlcplus-QLC-_4.12.2'
dh_auto_test: error: make -j1 check returned exit code 2
make: *** [debian/rules:8: build] Error 255
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2

```

**Comment by MDAR** [comment]
FYI


It turns out that I can install QLCplus onto this machine, I just can't create the DEB file to share with other ARM64 users

**Comment by mcallegari** [comment]
Please show the value of USERINPUTPROFILEDIR. Find it in engine/src/config.h

**Comment by MDAR** [comment]
Thank you :-)

The `qlcconfig.h` file us untouched, from the source code zip. (Should I have edited it?)

*** That said..

Prior to "installing" QLCplus from the source code (as opposed to creating the DEB file, then installing), I'm fairly sure the directories listed in this file didn't exist.

So... Now that QLCplus has been installed, if I run the create-deb.sh file, do you think it will compile successfully?



The complete file contains this text


```
# ifndef CONFIG_H
# define CONFIG_H
# define APPNAME "Q Light Controller Plus"
# define FXEDNAME "Fixture Definition Editor"
# define APPVERSION "4.12.2"
# define DOCSDIR "/usr/share/qlcplus/documents"
# define INPUTPROFILEDIR "/usr/share/qlcplus/inputprofiles"
# define USERQLCPLUSDIR ".qlcplus"
# define USERINPUTPROFILEDIR ".qlcplus/inputprofiles"
# define MIDITEMPLATEDIR "/usr/share/qlcplus/miditemplates"
# define USERMIDITEMPLATEDIR ".qlcplus/miditemplates"
# define MODIFIERSTEMPLATEDIR "/usr/share/qlcplus/modifierstemplates"
# define USERMODIFIERSTEMPLATEDIR ".qlcplus/modifierstemplates"
# define FIXTUREDIR "/usr/share/qlcplus/fixtures"
# define USERFIXTUREDIR ".qlcplus/fixtures"
# define PLUGINDIR "/usr/lib/aarch64-linux-gnu/qt5/plugins/qlcplus"
# define AUDIOPLUGINDIR "/usr/lib/aarch64-linux-gnu/qt5/plugins/qlcplus/audio"
# define TRANSLATIONDIR "/usr/share/qlcplus/translations"
# define RGBSCRIPTDIR "/usr/share/qlcplus/rgbscripts"
# define USERRGBSCRIPTDIR ".qlcplus/rgbscripts"
# define GOBODIR "/usr/share/qlcplus/gobos"
# define WEBFILESDIR "/usr/share/qlcplus/web"
# endif
```

**Comment by mcallegari** [comment]
qlcconfig.h is not in the source zip...it is generated at build time.

I would start from scratch again.
Just unzip the sources and run ./create-deb.sh. Nothing else

**Comment by MDAR** [comment]
I'll run it now and see what happens.

Thanks for you time and guidance

**Comment by mcallegari** [comment]
To have UI tests pass, you need to have a full desktop environment up, including Xorg.
Also, via SSH you need to export the DISPLAY variable.
`export DISPLAY=:0`
I'm closing this

**Comment by MDAR** [comment]
Hi @mcallegari 
I've bought another Odroid C4, with the sole intention of compiling QLCplus for Arm7_64, as I'm certain there must be other people that would like a DEB file for it.

So, the unit is running Mate desktop, with Xorg and all the other dependancies that you list in the Wiki.


The compilation gets right to the end stages without any errors, but fails at

`FAIL!   :   InputOutputMap_Test::profileDirectories() 'dir.absolutePath().conatins(USERINPUTPROFILEDIR)' returned FALSE. ()`


The script then goes on to report

`Totals: 24 passed, 1 failed, 0 skipped, 0 blacklisted, 227ms`

Have you any suggestions what I can do to fix this?

(Given that I'm a long way from being a programmer, I'm just trying to _give back to you_ for all the effort you have put in)

**Comment by MDAR** [comment]
@mcallegari 

Your most recent version of QLCplus V4 has compiled perfectly on an Odroid C4 (Arm64)

AND it compiled into a .deb file for the first time ever !!!

Which I have now installed and use headlessly with a VNC scrapper., for use at a music festival at the end of this month.

Would you like a copy of the .deb with full instructions?

It is already on my website, but because you charge for your PI headless version, I WILL NOT give anyone the URL to the ZIP without your express permission.

Please advise.

**Comment by mcallegari** [comment]
This is great news, thanks for sharing!
Unfortunately I don't have a C4 to test the package (I have an old C2 which at the time was a great piece of hardware)
So thanks for the offer but at this time I kindly say no.
Instead, would you mind to share the results of QLC+ running on a C4 in the community section of the forums? A few pics and a brief description of the equipment would do.
That would be a great use case to show QLC+ running on "any" device 😉

**Comment by MDAR** [comment]
Hello 👋 

Thanks for the support.

>Instead, would you mind to share the results of QLC+ running on a C4 

I'm happy to post something about what I'm doing with it.

Are you okay with me posting a link the .deb file too ?
(or would you rather you take ownership of it)

**Comment by yestalgia** [comment]
This is super cool guys nice work.

**Comment by mcallegari** [comment]
> 
> Are you okay with me posting a link the .deb file too ? (or would you rather you take ownership of it)

Obviously I wouldn't take ownership of your work!
I would rather evaluate if there is interest around the C4 in the forums and then eventually provide an official package.
So for now I wouldn't publish a link but I leave this up to you

**Comment by MDAR** [comment]
> Obviously I wouldn't take ownership of your work!


Hardly anything I've done 😆 
This is totally your hard work.

All I did was prepare a system exactly as per your instructions and run the commands as supplied.

As you wish, I'll create a forum post next week to start a conversation.

If / when you want to take control, please just say. 

I absolutely do not want to take any of the spotlight from you and your efforts.


FYI, let me know if you want me to test V5 on a fresh Odroid C4.
I can give you full access to it via ZeroTier.
