### ISSUE TITLE
Artnet Input is not listening on unicast, only on broadcast // SoundSwitch broken

### ISSUE THREAD

**Issue by ui-maciej-ciach** [mcallegari/qlcplus#1243]
Hello everyone ! 

I had problems with communicating SoundSwitch with QLC+

Discovered then that QLC+ in ArtPollReply packets sends IP address of listening interface. 

https://github.com/mcallegari/qlcplus/blob/master/plugins/artnet/src/artnetpacketizer.cpp#L74

The problem is I see that you can't communicate with QLC+ using unicast as it only listens on broadcast.

https://github.com/mcallegari/qlcplus/blob/master/plugins/artnet/src/artnetcontroller.cpp#L56

I am talking about macOS build. I manually changed ArtPollReply packet to send broadcast address and suddenly DMX data was received correctly.

**Comment by ui-maciej-ciach** [comment]
@mcallegari

**Comment by mcallegari** [comment]
How much are you willing to pay to have this change done?
Because you paid for SoundSwitch, right?

**Comment by ui-maciej-ciach** [comment]
I've found a bug in this project that has nothing to do with any 3rd party application. 
ArtnetPoolReply packet has an advertisement IP that is not matching with the UDP socket that QLC+ is listening to. 
This is a bug in QLC+.

**Comment by mcallegari** [comment]
1. it's ArtPoll, not ArtPool
2. You mentioned Soundswitch in the ticket title, so IT HAS to do with a 3rd party application
3. as far as I can recall, no one reported this before
4. this is a bug in your opinion. A missing feature in my opinion. Many other users successfully used ArtNet input with QLC+
5. I'm not suggesting this is an invalid report, I am suggesting you guys don't appreciate free software. Go ask Soundswitch to broadcast on ArtNet and see what they reply. I just tested if/how much you are willing to contribute to this project for me to work on your request. As I suspected, the answer is: zero.

**Comment by mcallegari** [comment]
For the record, I just checked with 2 PCs running both Linux.
Transmitter with IP 10.0.0.123/255.0.0.0 and the receiver with IP 10.0.0.200/255.0.0.0
Transmission on 10.255.255.255 (QLC+ default) or 10.0.0.200 doesn't make any difference for the receiver.
Both configurations work. I double checked with Wireshark.

So the OP is either an error on subnets or specific to macOS.
Therefore I need to check also on Windows and macOS

**Comment by mcallegari** [comment]
Finally tested also on macOS. The behaviour is the same of Linux and Windows, so QLC+ is receiving data correctly from broadcast or unicast.
Therefore this report is invalid.

**Comment by jundl77** [comment]
Honestly, this is borderline harassment - do you expect anyone to help if the first reply they get is "are you paying"? I mean come on.
