### ISSUE TITLE
Feature request: Store settings on ini file

### ISSUE THREAD

**Issue by hellishvictor** [mcallegari/qlcplus#1250]
Hi, it would awesome if there exist an option for store the settings on a .ini files instead of  the registry, so it become portable and allow the user to launched the program from an usb pendrive.

Cheers.

**Comment by mcallegari** [comment]
Use the dedicated forum: https://www.qlcplus.org/forum/viewforum.php?f=18
Closing.

**Comment by hellishvictor** [comment]
Awesome.
