### ISSUE TITLE
Feature request: Ableton Link support

### ISSUE THREAD

**Issue by hellishvictor** [mcallegari/qlcplus#1251]
Hi, please consider implement Ableton Link support, that would be a badass.
Cheers.

**Comment by mcallegari** [comment]
Wow, not even a link to what that is, specifications, nothing.
Use the dedicated forum: https://www.qlcplus.org/forum/viewforum.php?f=18
Closing.

**Comment by hellishvictor** [comment]
Check it out [https://ableton.github.io/link/](url)
And yeah, have a good year !
