### ISSUE TITLE
How to get export data from output to file?

### ISSUE THREAD

**Issue by mv2050arshad** [mcallegari/qlcplus#1271]
Hi

Greeting to your excellent software
I want to export out data to a file. please guide me which part of code generate output data base on animations which designed in projects?

thanks in advance

**Comment by mcallegari** [comment]
Hi, next time please use the forums.
This is mainly an area for developers.
As for your request, I guess you need to write a new output plugin that saves DMX data to a file.
Not an easy task if you're not familiar with C++ and Qt.
There's a dummy plugin to help wirite a new one: https://github.com/mcallegari/qlcplus/tree/master/plugins/dummy

**Comment by kripton** [comment]
@mv2050arshad : And even if there was a plugin, a bit more info would've been nice:
* What data format (binary, human-readable?)
* What do you want to use the recorded data for?

Even without an existing plugin, you can stream the data out via network (sACN or ArtNet) and use another software to record. Open Lighting Architecture can receive both (ArtNet and sACN) and can record DMX data

**Comment by mv2050arshad** [comment]
> 
> 
> Hi, next time please use the forums.
> This is mainly an area for developers.
> As for your request, I guess you need to write a new output plugin that saves DMX data to a file.
> Not an easy task if you're not familiar with C++ and Qt.
> There's a dummy plugin to help write a new one: https://github.com/mcallegari/qlcplus/tree/master/plugins/dummy

Thanks for your answer, absolutely you have guessed correctly. of course i'm c++,qt developer. i just asked to reach my goal fast because your project have really big code. 
Btw i will try that link which have send.

**Comment by mv2050arshad** [comment]
> 
> 
> @mv2050arshad : And even if there was a plugin, a bit more info would've been nice:
> 
>     * What data format (binary, human-readable?)
> 
>     * What do you want to use the recorded data for?
> 
> 
> Even without an existing plugin, you can stream the data out via network (sACN or ArtNet) and use another software to record. Open Lighting Architecture can receive both (ArtNet and sACN) and can record DMX data

Good idea but i prefer to understand qlcplus process to make the plugin to export data to in any format that i want.
