### ISSUE TITLE
[FEATURE REQUEST] Color matrix background.

### ISSUE THREAD

**Issue by kingpin1905** [mcallegari/qlcplus#1280]
Could be very usefull to be able to set a background color when doing animations with the RGB matrix function (replacing the "unlit" fixtures with a static color.

I don't rly know what to add. Don't hesitate if you need more info.

**Comment by FloEdelmann** [comment]
Feature requests should be asked in the forum: https://www.qlcplus.org/forum/viewforum.php?f=18

The GitHub issues are only for development-related problems.
