### ISSUE TITLE
[ui] XY Pad doesn't scale correctly

### ISSUE THREAD

**Issue by mcallegari** [mcallegari/qlcplus#1284]
Screenshot attached.
Tried different Qt versions.

![Screenshot_20210711_155432](https://user-images.githubusercontent.com/2951337/125197989-4b1f1c80-e260-11eb-9d4d-1c5929ea064b.png)

**Comment by hjtappe** [comment]
This is where the regression was introduced in v4:
- OK: 12.06.2020 c946d91f2
- NOK: 13.06.2020 8e243175b https://github.com/mcallegari/qlcplus/commit/8e243175b
It seems strange as he latter does not change the XY pad code - but this is where to XY pad display starts to be broken reproducably.

Can you please re-visit the patches around there?

**Comment by hjtappe** [comment]
I see there was a branch for QT deprecation warnings and the last OK revision therein is 4052a1b3d.
So I think we are looking into the QT related patches between 4052a1b3d (10.06.2020) and 8e24317 (13.06.2020).
