### ISSUE TITLE
Linux build instructions: qt5-default is not available on new ubuntu versions

### ISSUE THREAD

**Issue by jlskuz** [mcallegari/qlcplus#1287]
The package `qt5-default` is not available in Ubuntu 21.04 anymore. Instead one need to install `qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools`. See also https://stackoverflow.com/questions/67373586/install-qt5-on-ubuntu-21-04

**Comment by mcallegari** [comment]
wiki updated, thanks
