### ISSUE TITLE
[QLC+ 5] - Crash during loading workspace from previous version and blank Qt window after startup

### ISSUE THREAD

**Issue by scooon** [mcallegari/qlcplus#1298]
Crash during opening workspace from v4, after this crash during try start app, it shows only blank windows with titlebar. Uninstal/Install again not resolve this problem, a lot of people have similar problem.

**Comment by mcallegari** [comment]
As indicated in the issue guidelines, this is a place for developers.
Please use the forums and don't forget to attach the project file you forgot here. (without it's impossible to solve a crash issue)
