### ISSUE TITLE
Eurolite DMX-512 pro not working

### ISSUE THREAD

**Issue by MikeTango** [mcallegari/qlcplus#1305]
Hi,

i just acquired an eurolite DMX 512 pro and it is not performing well on qlc+, newest build, xubuntu.
The output is choppy and laggy, even with only one generic dimmer attached. 
 I see conflicting information which dongles work and how to make them work, is there any definitive way of fixing it or at least identifying whether it's an affected model or if the problem lies elsewhere? 

regards,

MT

**Comment by mcallegari** [comment]
Hello, as indicated in the issue guidelines, this is a place for developers.
Please use [the forums](https://www.qlcplus.org/forum/) like everybody else and include as much information as possible to describe your setup and the issue.
Thanks
