### ISSUE TITLE
Images, texts and animated GIFs appear blurry in RGB Matrix

### ISSUE THREAD

**Issue by 3rd3** [mcallegari/qlcplus#1310]
**Describe the bug**
When an such elements are placed in an RGB Matrix then it will appear blurry. Instead of being rendered at 1:1 zoom, it is slightly scaled, resulting in blurry appearance, even though the image might contain a sharp pattern, e.g. non-aliased pixel fonts.

**Comment by mcallegari** [comment]
sample project?
sample picture?
screenshot?

**Comment by mcallegari** [comment]
10 days of inactivity. Closing
