### ISSUE TITLE
Wrong scene attached to slider on file open.

### ISSUE THREAD

**Issue by Off-IT** [mcallegari/qlcplus#1313]
**Describe the bug**
When saving and re-opening a file, a wrong scene is assigned to my sliders

**To Reproduce**
1. I have 4 dimmer fixture and 3 simple scenes
2. On the virtual console I have a frame with 4 sliders : one submaster and the 3 scenes
3. I save the file, close QLC+ then I re-start QLC+ and reload the file
4. All the sliders are now attached to the first scene

**Expected behavior**
The sliders should keep their associated scenes

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - QLC+ Version 5.0.0 beta1

Example file here : https://drive.google.com/file/d/124eBxom6YtH1VJN-XkwHdPGnoXYRH1t6/view?usp=sharing

**Comment by mcallegari** [comment]
Thanks for reporting this. It was like a super bug!
Save/load is now consistent again.
