### ISSUE TITLE
E1.31 input is not interpreted correctly

### ISSUE THREAD

**Issue by davidpanic** [mcallegari/qlcplus#1321]
**Describe the bug**
QLC+ does not interpret E1.31 input at all.

**To Reproduce**
1. Open two instances of QLC+
2. Set one to input E1.31
3. Set the other to output E1.31 to the first instance's IP (localhost if running on the same machine)
4. Change some faders in the `simple desk` of the outputting instance
5. Observe no change on the instance that is inputting E1.31 (even when a bound slider is added to the `virtual console`)
6. Observe packes sent and packets received values increasing in the respective instances E.131 `inputs/outputs` settings.

**Expected behavior**
The second instance should read the E1.31 values correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/13370323/161191887-f2a72110-6279-4967-841b-d80e166cd488.png)
![image](https://user-images.githubusercontent.com/13370323/161191908-81df1886-8d52-4874-8d18-8242cd501fe1.png)
![image](https://user-images.githubusercontent.com/13370323/161192176-ba44b236-cc04-42ff-b84b-c984614d067e.png)

**Desktop (please complete the following information):**
- OS: Artix Linux, kernel 5.16.14
- QLC+ Version: 4.12.4
- hardware setup: none required

**Additional context**
Sending E1.31 works fine, I have fixtures that are receiving it. The problem arises when I want to input E1.31 data from another computer or a mobile phone app.

**Comment by davidpanic** [comment]
:rofl: Alright, this only seems to happen on universes >= 128, I just happened to pick 128 to test with, still a bug though.

**Comment by mcallegari** [comment]
Fixed, thanks for reporting
