### ISSUE TITLE
Restore CAPS regular expression

### ISSUE THREAD

**Issue by mcallegari** [mcallegari/qlcplus#1329]
The "port" to build with Qt6 required to switch QRegExp calls to QRegularExpression, which now supports only Perl-like regexp.
This commit 2bf07b313f3f629eb00478ce61504e1edfeb9b75 disables caps checking on fixture editor, but it needs to be restored with the proper syntax.

Most likely, there are other regexp around that need to be checked

**Comment by hjtappe** [comment]
I could help with fixing regular expressions in 3 weeks if you need help and if there is more to be done.

**Comment by mcallegari** [comment]
@hjtappe that would be a great help, thanks!

**Comment by mcallegari** [comment]
Fixed by #1333
