### ISSUE TITLE
Audio stop play when you switch to Functions

### ISSUE THREAD

**Issue by universe-42** [mcallegari/qlcplus#1342]
**Describe the bug**
When I play an audio in live mode (button), then I switch to Functions and click on any function (scene, script...), or when i want to create new, the music stops.

**To Reproduce**
- Add button with audio in Console
- Go to Live mode
- Click on button to play a Audio
- Switch to Functions tab and do something

**Expected behavior**
Audio should continue

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 (tested also on Windows 11)
 - QLC+ Version 4.12.4

**Comment by sbenejam** [comment]
I made some tests on Ubuntu 22.04 with QLC+ 4.12.5-GIT. Audio stops after a few clicks in the function manager. Sometimes crash at first click selecting any function manager element, sometimes crash after 3, 4, 5 or 6 clicks.

**Comment by mcallegari** [comment]
> Switch to Functions tab and do something

Please define "do something"
If you click on the same audio function then yes, audio is stopped.
If you click on any other DMX function then it works for me. I just tested and no crash

**Comment by universe-42** [comment]
_do something_
click on any function (scene, script, efx...) you don't need to do any change. Just click to see a detail.

Its not crashing. Its just stop an audio playing in Virtual console (live mode).
If this not help. I will share you project file with audio file on monday. Also I can record video what exactly I am doing.
