### ISSUE TITLE
Rounded values inconsistency in FadeChannel and KeyPadParser

### ISSUE THREAD

**Issue by jeromelebleu** [mcallegari/qlcplus#1344]
I have uploaded the last version of QLC+ 4.12.5 in Debian but some tests fail on at least arm64 and i386, see [here](https://buildd.debian.org/status/package.php?p=qlcplus&suite=sid).

For [arm64](https://buildd.debian.org/status/fetch.php?pkg=qlcplus&arch=arm64&ver=4.12.5-1&stamp=1655984314&raw=0):
```
FAIL!  : FadeChannel_Test::calculateCurrent() Compared values are not the same
   Actual   (fch.calculateCurrent(255, time)): 126
   Expected (uchar(255 - time))              : 127
   Loc: [fadechannel_test.cpp(348)]
```

For [i386](https://buildd.debian.org/status/fetch.php?pkg=qlcplus&arch=i386&ver=4.12.5-1&stamp=1655982894&raw=0):
```
FAIL!  : KeyPadParser_Test::parsing() Compared values are not the same
   Actual   (scv.value): 71
   Expected (uchar(72)): 72
   Loc: [keypadparser_test.cpp(188)]
```

Do you have the same errors? And any idea on how to fix that please?

**Comment by mcallegari** [comment]
Obiously I don't have those errors, otherwise I would have stopped the release.
No error on Ubuntu 64bit nor on the OBS build which are a quite variety of distros and compilers.
I even compiled on a Raspberry Pi 4 which is 32bit and no error there too.
I don't know how I can help here...

**Comment by kripton** [comment]
I experienced the same today on my Gentoo Linux system. However, the root cause was:
```
./test.sh: line 9: lupdate: Command not found.
./test.sh: line 10: lrelease: Command not found.
```

Installing `dev-qt/qtchooser` made the tests pass. See also: https://www.gentoo.org/support/news-items/2022-03-30-qt-5_15_3-bump.html

**Comment by kripton** [comment]
Make sure that the Debian package `qttools5-dev-tools` is installed and the command `lupdate` is available.

**Comment by jeromelebleu** [comment]
> The errors you see are rounding issues depending on the architecture. Perhaps adding qRound() here and there could solve some cases. Do you have any chance to test some patches?

Thanks for having a deeper look @mcallegari, I will try on a i386 chroot at first to see if it fixes the issue.

> [EDIT] btw in 2022 Debian should definitely drop i386 builds for desktop...

I didn't see this debate yet in the Debian community. I think however that it would be a shame to throw away all the old computers which are still working fine for their usage - as a simple server for example as there is no difference between desktop and server in our distribution.

> I experienced the same today on my Gentoo Linux system. However, the root cause was:

Thanks @kripton, but it is not the same issue here, since all tests pass on amd64.

**Comment by StefanBruens** [comment]
For FadeChannel::calculatecurrent(), the problematic values are:
m_start=255, m_target=0, elapsedTime=128, fadeTime=255
Putting these into:
https://github.com/mcallegari/qlcplus/blob/ff4eb3e05221d42c92b75af4481398c2f916c3bc/engine/src/fadechannel.cpp#L325-L333

we end up with `-255.0 * (128.0 / 255.0) + 255.0`, which is not, as one may assume, exactly 127.0, but dependent on the floating point implementation, may be something more like 126.999.... The implicit float-to-integer cast then *must* (according to the C standard) truncate the value to 126.

The following code should be able to cope with this problem:
```
    float val = (float(m_target - m_start) * float(elapsedTime) / float(fadeTime)) + float(m_start);
    long rval = lrintf(val * 256); // round to nearest in 8.8 fixed point notation 
    if (m_flags & Fine) {
            m_current = rval & 0xff;
    } else {
            m_current = val / 256;
    }
```

**Comment by jeromelebleu** [comment]
Thanks a lot @StefanBruens for having a look and for this useful explanations! I will try to instantiate an arm64 environment to test your patch. Do you have any clue for the [other test which fails](https://github.com/mcallegari/qlcplus/blob/QLC%2B_4.12.5/engine/test/keypadparser/keypadparser_test.cpp#L188)? I guess [this line](https://github.com/mcallegari/qlcplus/blob/QLC%2B_4.12.5/engine/src/keypadparser.cpp#L199) should be responsible of this gap?

**Comment by mcallegari** [comment]
I would give `std::round` or `qRound` a try.
E.g. `float val = std::round( ... )`
