### ISSUE TITLE
fixtures activate while on standby

### ISSUE THREAD

**Issue by djstudiodenis** [mcallegari/qlcplus#1359]
Any idea?  i have version 4 11 2 on a mac.  this happens often. the menu is on stand by, dinner time. all devices are on stand by, meaning no lights are running. then some fixtures goes on randomly, qlc is not responding anymore. i have to exit the qlc, go back in, then then lights goes off normally. it does this a few times when im at gigs. i cannot reproduce this error when im testing at home. 
note: the laptop battery is dead, im wondering if some type of power issues can cause this like loosing connection/handshake with the usb dmx entec pro.
tks

**Comment by mcallegari** [comment]
Please use the forums to report such usage issues. This area is mainly for developers.

First thing I would do is to change the computer if you suspect it could be the cause. Or the DMX adapter.
By the way, version 4.11.2 is ancient. You should update.
