### ISSUE TITLE
Web interface doesn't show button background images

### ISSUE THREAD

**Issue by nospam2k** [mcallegari/qlcplus#1362]
v4.12.5 (possibly all?) - On linux and MacOs. Button background images are not show in web interface of virtual console. Looking through web page html, there is no sign of background-image tag. Is this by design or is there a problem?

If it is not been implemented, please point me towards the supporting code and I'll be happy to look into implementation.

There is no info in web api to address background-image.

**Comment by mcallegari** [comment]
Closing, as reported here:
https://www.qlcplus.org/forum/viewtopic.php?f=34&t=15789

**Comment by nospam2k** [comment]
@mcallegari I'm happy to work on this. I'm just jumping in and will have to work back to some end which will take a long time. I've had a look through the code and I imagine webaccess and ui are the places to look but not sure where xmlProject is loaded as it points to res->body which I don't quite follow as it seems self referencing to me not knowing the code.

If this is something you have already resolved in a later developer release, I'd be interested in it. Otherwise, again, I'm happy to work on a resolution.

**Comment by mcallegari** [comment]
See if this is what you expect:
https://github.com/mcallegari/qlcplus/commit/a97abd449f3e3a9d22973640f394743323108740
