### ISSUE TITLE
QLC Plus does not discover artnet nodes on 127.0.0.1

### ISSUE THREAD

**Issue by D1plo1d** [mcallegari/qlcplus#1364]
In debugging a new Artnet node implementation against QLC Plus I've ran into an issue with QLC not discovering nodes running on 127.0.0.1.

After verifying that my `ArtPollReply` messsages are valid with WireShark (and many hours of assuming it was a problem with my node implementation :sweat_smile:), I think I've found the issue in QLC Plus.

Is my reading correct that this line means that QLC Plus will mistakenly ignore all `ArtPollReply` messages when they originate from the same IP address as QLC Plus? Shouldn't this check the ip address and the port, not just the ip?

https://github.com/mcallegari/qlcplus/blob/9050a7f134f4ab6ffc0a45757f27ad5675246cde/plugins/artnet/src/artnetcontroller.cpp#L470-L471

**Comment by mcallegari** [comment]
I am still in doubt this is OK for all cases.
For example now I'm trying to do RDM to a fixture (not on loopback) and it segfaulted QLC+ because of this patch.
That's because QLC+ receives the messages it sends which is not wanted.
I need to find an alternative solution
