### ISSUE TITLE
Launchpad mini MK3 Inputs/Outputs setting problem (4.12.6)

### ISSUE THREAD

**Issue by janjurek** [mcallegari/qlcplus#1371]
**Describe the bug**
Version 4.12.6 made it impossible for me to send feedback to my MK3 mini launchpad due to UI problems when selecting input and mainly feedback for my device. It all started probably in 4.12.5, but there it was still possible to manually set everything to work, but it had to be done on every app start.

**To Reproduce**
1. Have Launchpad mini MK3 setup (input/output/feeback) to Midi channel 1 ( or 1-16) 
2. Select "Line 2" device (since there are 2 visible for this device, nut only the second is working in QLC, see screenshots below) for input and feedback
3. Bind any launchpad button to function (and set custom feedback color if needed)
4. Press button to activate (while in operation mode)
5. Virtual console take the input of the launchpad but no feedback is sent do the controller.

**Expected behavior**
Button on the controller gets feedback and turns on.

**Screenshots**
The main problem lies in how the inputs/feedback are handled for the Lauchpad mini MK3 when read from the save file. This is how the XML definition should look (I even tried to manually change it)
```xml
  <InputOutputMap>
   <Universe Name="Universe 1" ID="0" Passthrough="True">
    <Input Plugin="MIDI" UID="Launchpad Mini MK3" Line="2"/>
    <Feedback Plugin="MIDI" UID="Launchpad Mini MK3" Line="2"/>
...
   </Universe>
  </InputOutputMap>
```
But `Line` is always changed and corrupted on version 4.12.5 to this:
```xml
    <Input Plugin="MIDI" UID="Launchpad Mini MK3" Line="1"/>
    <Feedback Plugin="MIDI" UID="Launchpad Mini MK3" Line="1"/>
```
And on **4.12.6** it is even stranger with feedback change to "0":
```xml
    <Input Plugin="MIDI" UID="Launchpad Mini MK3" Line="1"/>
    <Feedback Plugin="MIDI" UID="Launchpad Mini MK3" Line="0"/>
```

**The main problem** with this being "Major" bug for me in 4.12.6 version is fact that in 4.12.5 I just manually switched Line to 2 on startup every time like this:

![4 12 5](https://user-images.githubusercontent.com/14951952/198849667-f25d3e53-636b-4dd4-8912-fd29cfc31d16.png)

But in the most recent version (4.12.6) the UI corrupts itself in the Feedback part (see the picture) and even if I change everything properly to "Line 2", it never really works (I suppose this is the reason why it's always saved as 0 for feedback in this version), therefore there is no way to get around the problem of feedback on this version.

![4 12 6](https://user-images.githubusercontent.com/14951952/198849746-91970637-f2ff-46dd-a572-78c54299336d.png)

Hope this all makes sense, I'm only end user of this program so I can only assume that is the culprit here. Please reach out if I missed any detail that could help solve this one. I will until then use the older version (4.12.5 with manual change). Thank you for maintaining this great program, I've been using it for years without much problems 😊 

**Desktop (please complete the following information):**
 - OS: MacBook Air M1 2020, macOS 12
 - QLC+ Version 4.12.6 (but partialy in 4.12.5)
- Launchpad Mini MK3, DMX USB dongle (works as expected)

**Comment by mcallegari** [comment]
Hi, I don't have two identical midi controllers but I have an idea how to fix this.
Since you landed on Github I assume you can build QLC+ on your own and test my changes?

**Comment by janjurek** [comment]
Hi there, I landed here since I'm a developer and I know this is the best place to cooperate. Sadly I have no knowledge of building Qt apps, but I can try it, seems fair to offer my help here :)

**Comment by mcallegari** [comment]
Otherwise if you can get a hold of a Linux machine it would be much much easier to build and test fixes

**Comment by janjurek** [comment]
Heh I finally build the linux version (I tried the macOS route and it was hell and I didn't succeed), I had to do it on my RPi4 but I was able to compile head of master (currently 4.12.7) and the problem didn't occurred there, so did a clean build of 4.12.6 tag commit and it worked as well. 

So it looks like it's not a problem on Linux, it works there as expected (even save device with correct Line="2" into qxw) as you can see on the picture below. So I guess the problem is with how MIDI devices are resolved for this device on macOS specifically I guess.

![Linux_4 12 6](https://user-images.githubusercontent.com/14951952/199203134-61973758-77db-407e-ad08-aef804e8b8f1.png)

**Foot note:** Just to make it clear (it might not be, now that I read your comment), I did connect only one MIDI device and that is the Launchpad Mini MK3. The controller shows always as 2 MIDI Lines. First one is how the call it "Session Mode" (this one does not work in QLC) and the second one is "Standalone Mode" that pretty much works as the old Launchpad Mini MK2 and this is the one I'm trying to send the feedback to.

**Comment by mcallegari** [comment]
As I suspected, the name makes the difference.
If you notice, on Mac the 2 devices have the same name, while on Linux for some reason ALSA maps them with different names.
That is exactly what I wanted to try: make unique names when populating the devices list.
I'm gonna submit a patch when I have some time.
Thanks for the confirmation.

**Comment by janjurek** [comment]
I see, that's perfect, glad I could help a little and I'm here to test this more if needed. Btw I really appreciate your quick response, I was really not expecting that it was nice surprise. Thanks for still taking time maintaining this program after so many years :)

**Comment by mcallegari** [comment]
I published a Windows test version. If you have any chance, please test it.
If I find some time I'll try to publish also a macOS version with the fix.

**Comment by janjurek** [comment]
I managed to dig up old windows laptop and run **4.12.6** version and the latest **4.12.7.129** CI build on it just to check and in both instances on Windows the change is probably not visible since they have been properly separated even on older version, so this look like to be the macOS problem only then.

![windows](https://user-images.githubusercontent.com/14951952/199722172-81381044-baf4-49ef-9a54-85bb010491c3.jpg)

**Comment by mcallegari** [comment]
Please check the latest test version for mac
https://www.qlcplus.org/downloads/test/index.php?p=macOS

**Comment by janjurek** [comment]
Yes superb, I can verify that your solution did resolved the issue in this build. Names are now different, I can comfortably select the correct one and input and feedback works as expected. Thanks once more for resolving it so promptly :)

![resolved](https://user-images.githubusercontent.com/14951952/199841318-7419f546-6857-4f1f-a8c3-c8170b3db922.png)
