### ISSUE TITLE
QLC+ crashes on load when a workspace containing a DMX USB universe is opened on a machine that hasn't previously had DMX USB enabled

### ISSUE THREAD

**Issue by FloridaManDJ** [mcallegari/qlcplus#1379]
**Describe the bug**
QLC+ crashes on load when a workspace containing a DMX USB universe is opened on a machine that hasn't previously had DMX USB enabled.

**To Reproduce**
1. Install QLC+ on a new machine or VM, that has not previously had QLC+ installed.
2. In the 'Inputs/Outputs' tab, note how 'DMX USB" isn't enumerated in the list of plugins. The behavior I'm seeing is that DMX USB only shows up in the list after it's been plugged in; but don't plug it in yet.
3. Open any QLC+ workspace that has previously been configured to contain a DMX USB output universe.
4. QLC+ will crash.
5. Re-open QLC+
6. Now plug the DMX USB device in, and check the 'output' box to enable it.
7. Now attempt to re-open the same project. 
8. QLC+ doesn't crash this time.

**Expected behavior**
QLC+ shouldn't crash simply because DMX USB hasn't been used on a new machine. It should be capable of opening files made on other machines, even if the output devices haven't been configured.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - QLC+ Version 4.12.6

**Comment by mcallegari** [comment]
Hi, I have tested the sequence on Linux and it doesn't crash for me.
I have reset all the QLC+ config files to start like a new installation.
Perhaps this is specific to Windows. As soon as I can I will test there too.

**Comment by mcallegari** [comment]
I've been able to reproduce the crash by tweaking a project with a non existing plugin, like this:
`<Output Plugin="FOO USB" UID="DMX USB PRO - DMX Output 1 - (S/N: 123456)" Line="0"/>`
