### ISSUE TITLE
Blackout does not work as usually shoud do

### ISSUE THREAD

**Issue by hfuerst** [mcallegari/qlcplus#1381]
Blackout-Button should only blackout Intensitys, not other Channels. Professional Consoles do so for a long time, some cheap Consoles and older Analog Consoles don't. 
The actually Blackout-Button is not useable in Live-Shows. Master-Fader Works fine, but there is no Button for it. Also needed with external Inputs for it.

**Comment by hfuerst** [comment]
Master-Fader Works fine, but there is no Button for it. Also needed with external Inputs.

**Comment by yestalgia** [comment]
Hey I appreciate this being brought up again.

Though you can create a button and make it triger a blackout in the virtual console. Simply create a button, open it's settings and click the "Toggle Blackout" radio button.

**Comment by hfuerst** [comment]
I know this possibility in the Virtual Console. 
But the Problem is still the there. Blackout is NOT the same as Masterfader at Zero.

**Comment by yestalgia** [comment]
Yeah I understand and agree. I'm hoping this gets looked at soon. The main problem I have is how the blackout sends my moving heads into a spin.

In any case, the issues section of this github is usually reserved for build issues/crashes etc. Create a thread in the forum so Massimo can keep track of it better.  Thanks!

**Comment by hfuerst** [comment]
OK. Made it.

**Comment by hfuerst** [comment]
Closed
