### ISSUE TITLE
Some rgb scripts missing in virtual console

### ISSUE THREAD

**Issue by MonsieurNaexec** [mcallegari/qlcplus#1384]
**Describe the bug**
When adding a preset to the custom controls of a RGBMatrix properties panel (in the Virtual Console), some preset patterns are missing.

**To Reproduce**
1. Go to the Virtual Console
2. Create a new "Animation" widget
3. Go to the animation widget properties
4. Go to the "Custom Controls" tab
5. Click "Add preset"
6. Change the "Pattern"

**Expected behavior**
You should be able to select any script pattern.

**Current behavior**
All patterns are shown except for "Plain Color", "Text", "Image" and "Audio Spectrum"

**Desktop (please complete the following information):**
 - OS: all
 - QLC+ Version: 4.12.6

**Additional context**
This is because the pattern list is retrieved using `m_doc->rgbScriptsCache()->names()` instead of `RGBAlgorithm::algoritms(m_doc)` in `vcmatrixpresetselection.cpp`
I'm working on a PR but just wanted to make sure this was actually a bug since it seems to have been like that since the beginning.

**Comment by mcallegari** [comment]
The fix is easy, I just need to test myself if adding the other algorithms break presets

**Comment by mcallegari** [comment]
Fixed. I also included the missing presets from the widget combobox selection.
Thanks for reporting
