### ISSUE TITLE
QLC+ 4.12.5 .deb package wrong label

### ISSUE THREAD

**Issue by MikeTango** [mcallegari/qlcplus#1389]
Hi,

QLC 4.12.5 when downloaded from the Web identifies as "ArtNet Plugin for QLC" and not the full program. I guess it only needs a label change.
![Bildschirmfoto_2023-02-05_12-07-46](https://user-images.githubusercontent.com/3368005/216815448-11fc13a2-162e-4d77-a16b-418118200ea9.png)

**Comment by mcallegari** [comment]
What?
Where did you take that screenshot?

**Comment by mcallegari** [comment]
The package description is correct
https://github.com/mcallegari/qlcplus/blob/master/debian/control#L34
Who created that website didn't even took the time to copy the right name.
Closing as out of scope.

This is the only source for downloads: https://www.qlcplus.org/downloads.html
And 4.12.5 is not even the latest release.

**Comment by MikeTango** [comment]
That's a very interesting one because i'm quite sure that i downloaded it from the official QLC+ website as latest release. I will try and retrace my steps and let you know.

**Comment by mcallegari** [comment]
This is another official page
![Screenshot_20230205_142859](https://user-images.githubusercontent.com/2951337/216821962-144fae9c-c546-42c6-afec-ab1e0749bd9a.png)

There are no others

**Comment by MikeTango** [comment]
It's from the official QLC website. I re-downloaded and compared the md5 checksums of both files, they match.
md5 is 0270f60e07ff4f6b2a5a11eff95d592c

I accidentally downloaded the older version, since it's superseded, i guess it doesn't matter anyway.
![Bildschirmfoto_2023-02-05_14-30-45](https://user-images.githubusercontent.com/3368005/216822195-581b920e-f197-4e5c-ba03-c30c21d54a1a.png)

**Comment by MikeTango** [comment]
Same behaviour on .06 , downloaded from the QLC website. 

Xubuntu 20.05

![Bildschirmfoto_2023-02-05_14-35-25](https://user-images.githubusercontent.com/3368005/216822323-f7098c0e-c18e-4d6c-9785-21209a229d5d.png)

**Comment by MikeTango** [comment]
weirdly enough, dpkg --info throws this:
![Bildschirmfoto_2023-02-05_14-39-25](https://user-images.githubusercontent.com/3368005/216822672-d190f4bd-09c9-44ff-b968-1cc1a89054d7.png)

**Comment by mcallegari** [comment]
OK so the screenshot is not from a website. It's from your local package manager...which is...?
Please state all the relevant information when opening an issue.
Also which distro you're using

**Comment by MikeTango** [comment]
the erratic package manager is gnome-software on Xubuntu 20.04 LTS. I don't know where it pulls the info from since dpkg show ist correctly.

**Comment by mcallegari** [comment]
I think they have their own maintained database with packages information.
No idea why it's wrong or why it says "ArtNet plugin". There has never been a dedicate deb package for the ArtNet plugin.
In any case I think this is not a QLC+ issue and this can be closed, right?

**Comment by MikeTango** [comment]
If there is nothing that can be done from this side, i'll probably head over there and ask them where it pulls the info from.

**Comment by MikeTango** [comment]
Thanks for the quick support!
