### ISSUE TITLE
Concurrent MIDI notes not correctly read on Mac

### ISSUE THREAD

**Issue by Timebutt** [mcallegari/qlcplus#1390]
**Describe the bug**
A MIDI note that is immediately preceded by a MIDI CC value is not being read by QLC+, causing whatever is listening to that signal to not fire.

I have attached two MIDI files as well as a QLC+ project file to this issue to illustrate the problem. If you open `Test.qxw`, only `Scene 5` and the `Slider` are of note. The idea is that at a certain point in time, my MIDI track sends both MIDI CC to control the fader level (you'll see it bounce around as you play either of the supplied MIDI tracks), as well as at the exact same time send a `Note On` to trigger `Scene 5`.

If you first play `not-working.midi`, you'll see that `Scene 5` does not get triggered, and the MIDI timeline looks like this when viewed with a debugging tool (https://www.midimonitor.com/ is a pretty cool one):

```
16:49 23:567 | Virtual MIDI Bus 1 | Control Change | CC#1 Value 0 | 1
16:49 23:567 | Virtual MIDI Bus 1 | Note On | Note #63 Velocity 100 | 1
```

The MIDI note is clearly sent, but is somehow ditched by QLC+.
If we now take a look at `working.midi`, you'll see that `Scene 5` correctly gets triggered and all is well! The timeline looks like this:

```
16:52 45:316 | Virtual MIDI Bus 1 | Note On | Note #63 Velocity 100
16:52 45:508 | Virtual MIDI Bus 1 | Control Change | CC#1 Value 1 | 1
```

I've noticed that there's never a problem if the `Note On` message is sent before the CC value gets sent. Whenever the CC value is received right before the `Note On` message, the `Note On` is ignored by QLC+.

**To Reproduce**
1. Open `Test.qxw` from the zip archive I provided (see **Additional context**)
2. Load `not-working.midi` in any type of software that can play back a MIDI file
3. Configure QLC+ to correctly receive MIDI messages 
4. Verify `Scene 5` does not triggered when playing back `not-working.midi` even though the correct note gets sent!
5. Compare with `working.midi` file, which has the almost identical MIDI information, but the first CC message is delayed the tiniest amount
6. Verify `working.midi` playback results in `Scene 5` correctly being triggered in QLC+

**Expected behavior**
MIDI notes should always correctly be read by QLC+, regardless of the presence of any CC values.

**Desktop (please complete the following information):**
 - OS: MacOS Ventura `13.2`
 - QLC+ Version  `4.12.6`

**Additional context**
Attached zip with QLC+ project file and MIDI files can be found below:
[MIDI files + QLC project file.zip](https://github.com/mcallegari/qlcplus/files/10716470/MIDI.files.%2B.QLC.project.file.zip)

I'm going to take a look at the issue myself if I can set up the project to compile (it's been a while since I wrote C++ D:), but my guess is that the issue lies [somewhere in this routine](https://github.com/mcallegari/qlcplus/blob/master/plugins/midi/src/macx/coremidiinputdevice.cpp#L42). `Go thru all simultaneously-occurring messages in the packet` seems to reflect on this exact scenario, my guess is that somewhere in code some information is incorrectly skipped.

I will now verify if the same issue occurs on Windows, as it seems to use a different implementation. Will report back with the results!

**Comment by mcallegari** [comment]
Please launch QLC+ with debug and paste the output here
I'm pretty sure QLC+ is receiving all the MIDI signals but scenes are triggered only on high+low values. That's why there's an option for notes, discussed a thousand times in the forums.
https://www.qlcplus.org/docs/html_en_EN/howto-input-profiles.html
See Generate an extra Press/Release when toggled

**Comment by Timebutt** [comment]
Thanks for your very swift response @mcallegari. I took your suggestion and toggled the `Generate an extra Press/Release when toggled` option for the input channel that is reading MIDI, but it makes no difference, `Scene 5` is still not triggered through the external MIDI note.

I also don't really see how this would affect my situation, as that option seems to be in place for ` TouchOSC or the Behringer BCF2000`? I'm sending MIDI from Cubase, no external hardware device.

In any case, I ran `/qlcplus --debug 0 --log` to run the scenario I described above, which generated this log output:

```
virtual void CoreMidiInputDevice::close() Unable to disconnect input source in "IAC Driver"
virtual void CoreMidiInputDevice::close() Unable to disconnect input source in "IAC Driver"
virtual void CoreMidiInputDevice::close() Unable to disconnect input source in "IAC Driver"
```

Am I supposed to see more information (incoming MIDI notes, scene triggers, ...) here? I dove into the documentation, but didn't see any other option to increase the logging level even further. I'm trying to be as specific as I can here, to narrow down the problem!

**Comment by mcallegari** [comment]
For debug output you need to use a debug build either built by you or from here
https://www.qlcplus.org/downloads/test/index.php?p=macOS
Extra press is a generic feature. Please read this sentence again:
`this is a quite specific option used **for example** when dealing with TouchOSC or the Behringer BCF2000.`

**Comment by Timebutt** [comment]
I see, thanks for the clarification!
After installing the debug build, I get proper logs indeed. I have done two runs: once with the `Generate an extra Press/Release when toggled` enabled, and once with the feature disabled.

Interestingly enough there is indeed a difference: with the setting enabled, QLC+ triggers `Scene 5`, but only on `Note Off`. On `Note On` nothing happens. With the setting disabled nothing happens for both `Note On` as well as `Note Off`.

**Log Files:**

[QLC+-without-extra-press.log](https://github.com/mcallegari/qlcplus/files/10723065/QLC%2B-without-extra-press.log)
[QLC+-with-extra-press.log](https://github.com/mcallegari/qlcplus/files/10723064/QLC%2B-with-extra-press.log)

**Comment by Timebutt** [comment]
Ok so I was meanwhile able to set up `Qt 5.15.8` to compile QLC+ and provide you with more accurate logging, as it's the clearest way to illustrate the issue.

I [set up a branch](https://github.com/Timebutt/qlcplus/pull/1) where I just log the incoming MIDI messages caveman-style. If you play the provided MIDI files from a DAW, you'll see that `Note On` is never logged for the not working MIDI file. If I repeat the same test with the working MIDI file, you'll see `Note On` is received by QLC+ and everything works fine.

As other MIDI tools receive `Note On` in both cases, I'm convinced there is an issue in QLC+ that causes this `Note On` to be ignored. With a working development setup in hand, I'll take a look and see if I can isolate the problem!

**Comment by Timebutt** [comment]
@mcallegari so I debugged everything and found the issue. In concurrent MIDI messages the first package was always taken, which means that in the situation as described the `Note On` would never be read as a MIDI message and didn't get passed on into QLC+. 

I dropped a PR that addresses the issue, hopefully saving many others from going crazy as to why in some cases MIDI notes wouldn't trigger scene changes D:

Q: what is the release process for fixes like this? I'm assuming you'd release this sooner rather than later?
I for one definitely need it for a show I'm preparing, and I'm not entirely sure how to do a release build I can have faith in.

**Comment by mcallegari** [comment]
Releasing QLC+ is a very cumbersome activity. So I don't make a new release for a one-liner fix.
For that purpose there are [test versions](https://www.qlcplus.org/forum/viewtopic.php?f=12&t=3135).
Once merged, I can build a version for you. However, since you built QLC+ yourself you can create a dmx package yourself.
Instructions in wiki pages

**Comment by Timebutt** [comment]
I see how releasing could be a drag, but this is an issue that as far as I can see affects everyone trying to run a DMX show from MIDI. Many others like me I assume have an Ableton setup on a Mac for their live set, and want to send MIDI into QLC+. Less technically skilled people will notice sending concurrent MIDI commands doesn't work, go crazy over why that is and eventually ditch QLC+, not knowing why it doesn't work.

In my opinion this requires a hotfix release, to prevent people from downloading the current version with this bug. Being able to quickly ship important patches is crucial in open source software, and software engineering as a whole. If I can help set up a more automated release flow, I'm more than happy to!

**Comment by mcallegari** [comment]
PR merged, thanks.
I have uploaded an up-to-date test version for macOS.

**Comment by Timebutt** [comment]
Just downloaded and tested the new version, works perfectly! Very happy to see this new build as I can now program without any flakiness, thanks!
