### ISSUE TITLE
Default Toggle Blind Mode

### ISSUE THREAD

**Issue by chouvener** [mcallegari/qlcplus#1392]
Hi there! New here and not sure if this is the place to ask for help. When I start a new template, add simple dimmer pack fixtures, then create a scene- when I go live and click between the scenes it automatically turns on blind mode every time I go to a new scene and I can't default it to non-blind mode. Does anyone know whats going wrong? Thank you!

**Comment by mcallegari** [comment]
This is an area for developers. Please use the forums to report issues and provide as many details as you can.
https://www.qlcplus.org/forum/
