### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by yestalgia** [mcallegari/qlcplus#1409]
# Why a new logo?
The current logo for QLC+ has been an iconic feature of QLC+ since 2013.

Why should it be changed now? For a long time, the only way to access QLC+ has been on a desktop environment or through a web browser. The new versions of QLC+ may soon be interacted with on mobile devices including phones, tablets or even in VR. QLC+ will always run on desktop but it's no longer bound by this platform.

QLC+ should be able to help you wherever and whenever you need it, which is why a modern identity is required to reflect this.

The new logo should be flat, simple and still keep the "Lightbulb" motif which has been a key aspect of the current design. The design should work on desktop, web and mobile devices. 

# Previous designs
## Q Light Controller
![Image](https://user-images.githubusercontent.com/42596763/226748672-61f29036-7dab-461c-b5aa-33f1c7e74387.png)
https://sourceforge.net/projects/qlc/
[hjunnila](https://sourceforge.net/u/hjunnila/profile/)

## Q Light Controller+ (2013-Present)
![Image](https://user-images.githubusercontent.com/42596763/226748756-29208c85-dbe2-4b68-9334-a8a65f95cd69.png)

## New
![qlcplus](https://user-images.githubusercontent.com/42596763/227166208-01e4a56d-4c3a-47d6-9053-9dc2568a923c.png)

**Comment by yestalgia** [comment]
Big thanks to

**Comment by mcallegari** [comment]
![final-logo-dark-white-plus3](https://user-images.githubusercontent.com/2951337/226766759-97b0c819-6059-44f5-b48a-1a7c52a362fc.svg)

**Comment by mcallegari** [comment]
![final-logo-dark-white-plus3-inkscape](https://user-images.githubusercontent.com/2951337/226766845-d8b4075b-f521-4fbe-9720-9db8dc3302da.svg)

**Comment by yestalgia** [comment]
Testing has revealed the need to change the scaling factor in the "About" page for V4.

I would suggest keeping the new PNG size as it looks perfect in the top toolbar.

![image.png](https://user-images.githubusercontent.com/42596763/227089721-71f3b4da-7897-443d-90d5-bc7616195ce2.png)

**Comment by mcallegari** [comment]
What? No!
Toolbar icons are scaled, about icon is not.
Please stick to the original size (96px)

**Comment by yestalgia** [comment]
> What? No! Toolbar icons are scaled, about icon is not. Please stick to the original size (96px)

Fixed.

**Comment by yestalgia** [comment]
Done!

**Comment by marekjedrzejewski** [comment]
Wow, looks like I'm late to the party, but I just saw this when browsing for other program I forgot name of

![Image](https://github.com/user-attachments/assets/b6071b72-6f1c-4dde-a19b-ab9c384111cc)

Looks like I stopped receiving forum notifications or something, because I wasn't aware of anything that appeared there past first page 😅 

Just wanted to say great job to @yestalgia and I'm glad that I was there to start this ball rolling :)

**Comment by yestalgia** [comment]
> Just wanted to say great job to [@yestalgia](https://github.com/yestalgia) and I'm glad that I was there to start this ball rolling :)

This wouldn't have been possible without you, cheers!
