### ISSUE TITLE
[QLC+ 5] Items in dropdown menus are not selectable

### ISSUE THREAD

**Issue by ygversil** [mcallegari/qlcplus#1429]
**Describe the bug**
When trying to select an item in a dropdown menu (eg. mode in a fixture properties, or a chaser run property), the item disappears when the mouse cursor is hovering, and then clicking has no effect.

**To Reproduce**
Fixture mode example:
1. In the `Add Fixtures` panel, select whatever fixture with multiple modes (for example American DJ 12P Hex IP),
2. In the `Fixture properties` section, try to change the mode from *6 Channel* to *13 Channel*.

When the mouse cursor is over *13 Channel*, the text disappears. Click on the now blank item, nothing happens.

Chaser run property example:
1. Click on `Add a new function` button and select `New Chaser`,
2. Unhide the `Run properties` section by clicking on the `+` button,
3. Try to change the `Run order` from *Loop* to *Random*.

When the mouse cursor is over *Random*, the text disappears. Click on the now blank item, nothing happens.

**Expected behavior**
In each case, one should have been able to select *13 Channel* and *Random*.

**Desktop (please complete the following information):**
 - OS: Archlinux with latest packages (KDE Plasma 5, Qt 5.15.9)
 - QLC+ Version: 5.0.0 beta3 (from latest git master branch)

**Additional context**
If I launch QLC+ 5 from the command line, I get the following warning:

`file:///usr/lib/qt/qml/QtQuick/Controls.2/org.kde.desktop/ComboBox.qml:117: TypeError: Type error`

And, for the chaser example:

`qrc:/ChaserEditor.qml:237: TypeError: Cannot read property 'runOrder' of null`

Not sure if this is related.

**Comment by mcallegari** [comment]
![image](https://github.com/mcallegari/qlcplus/assets/2951337/52023121-cc38-4f5b-b343-7a913f7a15d4)

**Comment by mcallegari** [comment]
![image](https://github.com/mcallegari/qlcplus/assets/2951337/e0fa5cae-f1f0-44a8-89cd-b4524f97ba54)

**Comment by mcallegari** [comment]
Not reproduced.
Please try the latest AppImage built by GitHub actions

**Comment by ygversil** [comment]
It was indeed a problem with my Plasma environment on Archlinux. The package qqc2-desktop-style provides an old version of ComboBox.qml, and yet it was the one used when launching QLC+. Replacing with the file provided by the qt5-quickcontrols2 package fixed the issue.
