### ISSUE TITLE
error: variable 'haze' set but not used

### ISSUE THREAD

**Issue by yurivict** [mcallegari/qlcplus#1431]
**Describe the bug**
```
avolitesd4parser.cpp:748:9: error: variable 'haze' set but not used [-Werror,-Wunused-but-set-variable]
    int haze = 0, smoke = 0;
        ^
1 error generated.
```

**Desktop (please complete the following information):**
 - OS: FreeBSD 13.2
 - QLC+ Version 4.12.7

clang-15

**Comment by mcallegari** [comment]
Fixed 3 weeks ago.
https://github.com/mcallegari/qlcplus/commit/e99e1f9306f1cf493920535d973632aecbe3cf5f
Build the latest sources.
