### ISSUE TITLE
Button label locked when action isn't "toggle function"

### ISSUE THREAD

**Issue by ComedyTomedy** [mcallegari/qlcplus#1441]
**Describe the bug**
In the Button Properties modal, changing the "on button press" radio list to any value other than "toggle function on/off" will lock the "General" panel at the top of the modal. The intention is clearly to lock the "Function" field, but it also stops the user editing the "Label" field. So the button's name is frozen until you change its type again.

I've tested this only on version 4.12.7.

**To Reproduce**
1. Go to Virtual Console, create a button, open the "Button Properties"
2. Focus the "Button Label" field, to see that it's editable
3. Change the "On button press..." radio to anything other than the default of "Toggle function on/off"
4. the "General" panel at the top becomes locked - if you attempt to focus "Button Label", it won't work

**Expected behavior**
Lock only the "Function" field and its associated buttons.

**Desktop (please complete the following information):**
 - OS: Linux
 - Q Light Controller Plus version 4.12.7
 - (no hardware involved)

**Comment by yestalgia** [comment]
Hi there,

Thank you for making a bug report and providing detail so I could investigate the issue. 

I've been able to reproduce your issue in Windows 10, but only for "Toggle Scene" and "Stop All Functions"

Can you confirm if you are seeing this for the "Flash Function" radio button as well?

![image](https://github.com/mcallegari/qlcplus/assets/42596763/27259adc-5846-42df-a402-41b5eb818558)
![image](https://github.com/mcallegari/qlcplus/assets/42596763/ead8281a-d07b-4847-917a-eb031db4d763)

**Comment by ComedyTomedy** [comment]
No laptop right now, but I only tested stop and blackout, so it's likely that the behaviour is the same as you're seeing. Can confirm later.

**Comment by mcallegari** [comment]
I confirm label is locked only on "Toggle blackout" and "Stop all functions".
It's basically because an icon is displayed so no label is needed.
I think the proper behavior (at least in v4) would be to blank the label when selecting those 2 modes. This would make even clearer that label is irrelevant
Is there any need for a label on blackout/stop all?

**Comment by ComedyTomedy** [comment]
Ah, I see! I'm happy for you to close this issue, or keep it as a reminder to make the interface clearer, whatever works.

Personally, I'm only using this Virtual Console to assign OSC paths to functions, and I'm labelling them all after the OSC path. I suppose my preference would be that *all* widgets have a default name, like "[Toggle|Flash|] FunctionName", so "Toggle Blackout" and "Stop All" could have default names (instead of images) and not be special cases. But it's fine how it is, and I'm not really a typical user.
