### ISSUE TITLE
v5 beta2 crashing a lot on MacOS

### ISSUE THREAD

**Issue by mpicard** [mcallegari/qlcplus#1449]
**Describe the bug**

Beta 2 is crashing a lot, is there a way to help out with logs? Let me know where to find them and I can upload them. 

**To Reproduce**
1. open v5 beta2
2. try adding fixtures / new scene, etc
3. crashes

**Expected behavior**

does not crash unexpectedly 

**Desktop (please complete the following information):**
 - OS: MacOS 13.5.1
 - QLC+ Version v5beta2

**Comment by filiphanes** [comment]
QLC 5.0.0 beta 2 crashes after selecting preset in new fixture channel.

**Comment by mcallegari** [comment]
Beta 3 should fix these.
