### ISSUE TITLE
XY Pad in Relative to scene mode doesn’t work properly

### ISSUE THREAD

**Issue by sidlomydlo** [mcallegari/qlcplus#1456]
Hi,

found this issue:

When XY pad is in Relative to scene mode and the scene is active, you can’t move with fixtures. In fact moving XY pad is changing values on different chanels instead of moving heads pan/tilt, so only some fixtures are moving or even any of them (and you can even e.g. dimm your other fixtures accidentaly).

See end of this thread for more info about how the bug is acting: https://www.qlcplus.org/forum/viewtopic.php?p=69373#p69373

Hope you can manage to repair it.

Thanks!

**Comment by mcallegari** [comment]
Should be fixed. Please try the latest build version
