### ISSUE TITLE
Feature request Speed function slider

### ISSUE THREAD

**Issue by Vorona** [mcallegari/qlcplus#1457]
Hello!
I need slider mode, which can control speed channel in function. I mean, slider with same functional as playback mode, but control speed channels instead intensity. Also needed feature, whitch in solo frame any button will switch off sliders in playback mode (and mode with speed control) and any slider in playback mode will switch off any button.

Case reason:
I have strobe with 2 channels (intensity and speed). Strobe activates with non-zero intensity channel, zero on speed channel means very low speed.
I created some functions for strobe. In function I added all of 2 channels (intensity I set to 255 (100%) or 0% to turn on or off).
This functions I place to solo frame as buttons, also I place here slider with submaster function for control strobe brightness.
It works fine.
But Also I need abylity to simple manual control strobe speed by one slider with brightness sets with submaster slider.
I mean: Create scene with 255 level on both channels. Assign slider with "playback-speed" mode. Place to frame this slider and submaster slider.
Submaster slider will set brightness for working functions, and playback-speed will turn on and control speed channel for function.

**Comment by Vorona** [comment]
Closed by mistake

**Comment by mcallegari** [comment]
Hi, please use the dedicated forum to request new features.
https://www.qlcplus.org/forum/viewforum.php?f=18
This is not the right place.
