### ISSUE TITLE
Submaster slider

### ISSUE THREAD

**Issue by Vorona** [mcallegari/qlcplus#1458]
Hello!
I'm not shure, that it bug. Submaster slider follows by Intensity level of functions.

- Add fixture, for example, par or strobe with intensity channel. HTP channel mode
- Add sequence with intensity channel 255 level
- Add frame with submaster slider and button with sequence function
- Set any non-zero level on submaster
- activate sequence with button
- deactivate sequence with

I expect, that submaster slider will not change, but at deactivation sequence submaster slider sets to zero

 - OS: Linux Mint 21.1
 - QLC+ Version 4.12.7

**Comment by Vorona** [comment]
It' bug...
Steps for repeat ar not correct. Right way:

- Add fixture, for example, par or strobe with intensity channel. HTP channel mode
- Add sequence with intensity channel 255 level
- Add frame 
- Add slider, assign playback mode and sequence, click OK
- Enter to slider properties, go to submaster tab, activate this mode, click ok
- Add button with sequence function
- Set any non-zero level on submaster
- activate sequence with button
- deactivate sequence with button

**Comment by mcallegari** [comment]
> Add sequence with intensity channel 255 level
Sequence or Scene?

**Comment by Vorona** [comment]
It doesn't matter.

**Comment by mcallegari** [comment]
Should be fixed now. Please check one of the automated builds when done thanks
