### ISSUE TITLE
shows manager stops on a chaser

### ISSUE THREAD

**Issue by infrafast** [mcallegari/qlcplus#1461]
**Describe the bug**
 have a bug very difficult to reproduce, it happends to me a couple of time and become now very serious for the use.
We are using it for a band in live shows.
on windows 10 using QLC 4.2.4 and extensively use the shows manager to sync backtrack/clic with lights
For some reason, the shows just stop when reahcing some of the steps. This is really random, but when it happens, it will always fail on the same step.
Let's say I have one chaser name "all white", which puts all dimmer white lights on
It use to work in all shows, and for some reaosn, when laucnhing the show, it will stop in all the one that use "all white" when it reach it. 

**To Reproduce**
See video: It only happens when you are in "operate mode"
[](https://youtu.be/n7YxZ9sEf3E?si=PtRW7OTb6td7LmDs
)
https://www.youtube.com/watch?v=n7YxZ9sEf3E

**Expected behavior**
Show should not stop

**Screenshots**
see video [](https://youtu.be/n7YxZ9sEf3E?si=PtRW7OTb6td7LmDs)

https://www.youtube.com/watch?v=n7YxZ9sEf3E

**Desktop (please complete the following information):**
 - OS: windows
 - QLC+ Version 4.12.4 but also tested with latest 4.12.7
- hardware setup : Lixada usb stick

**Additional context**

it persists when shuting down/restarting the app.
I tested the project from another laptop with a QLC 4.2.4 on it, same behaviour...

The workaround I found is is to delete the chaser (or whatever function it is) and recreate it, then reassign it in all the shows. YOu can imagine this is absolutely not reliable when you have 30 shows using the item.

That's really anoying and prevents from using for production, is there any chance you look to that, I can provide all necessary details if needed,

**Comment by yestalgia** [comment]
Hello, please when this happens again give us the following:

1. The .qxw file where the chaser does not work
2. The .qxw file where you have fixed the chaser

Giving us these two files might help to find the source of the problem.

**Comment by infrafast** [comment]
Hello & thanks I manage to reproduce the issue. Not sure if this is a bug.

Basically, it happens in the following context:

A chaser is using a scene. This scene is also used by a solo button from the virtual console
When the shows hit the chaser, it stops, maybe because of the solo button ?

If you remove the button from the virtual console, it works fine.

**Comment by yestalgia** [comment]
Thanks for the additional context.

I suggest you duplicate the scene and assign one scene to the chaser and the other to the button.

If you still have trouble then please make a forum thread or provide what I asked for previously.

Please mark the issue as resolved if you're happy with that. :)
