### ISSUE TITLE
Bug: Missing _ZN5Audio9setVolumeEd

### ISSUE THREAD

**Issue by X-Raym** [mcallegari/qlcplus#1464]
I 

Win 10x64, QLC+ 5 beta 2

I  am trying to open a v4 project which had MIDI mapping to fader,

https://gist.github.com/X-Raym/4aac0af9bb747675f767df4a78e54375

I got this error message:

![img](https://i.imgur.com/DFdp0SP.png)

> Le point d'entrée de la procédure _ZN5Audio9setVolumeEd est introubavle dans la bibliothèque de liens dynamiques .... qlcplusui.dll

Thx!

**Comment by mcallegari** [comment]
You are mixing v4 with v5
You need to install them in separate folders!

**Comment by X-Raym** [comment]
@mcallegari Then this means that there is a problem with the install/uninstall process.

I can confirm: I have both QLC+ 4 and 5 right now and none of them appears into Installed program of windows. 

I also confirm that running the Uninstaller of v4 manually doesnt do anything.
EDIT: seems I had to run it in administator mode, yet it still leaves plenty of folder https://i.imgur.com/yGPK91F.png

Also, both install install the same shortcut name in Start Menu, so I cant have v4 and v5 shortcuts at the same time (unless created manually). New version should probably have "5" has indicator (at least for beta)

Not of this issue are that problematic but there are definitely some things unsual here.

Thx!
