### ISSUE TITLE
Fade out overides sound loops

### ISSUE THREAD

**Issue by MerchantMage** [mcallegari/qlcplus#1467]
**Describe the bug**
Any sound with a fade out duration will not loop.

**To Reproduce**
1. Go to functions
2. Create a sound using any sound file
3. Give it a "fade out" duration
4. Set it to loop
5. Play it

**Expected behavior**
When a sound is set to loop, I would expect the fade out to only happen when the user chooses to stop it from playing, particularly when clicking a button the sound is assigned to in the virtual console. Because of this glitch, everything I would use QLC+ for in regards to audio isn't doable.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - QLC+ 4.12.8 (also 4.12.7) I checked and this is not a recent development
- Hardware setup: An Acer latop. I also reproduced it on my PC.

**Comment by mcallegari** [comment]
Thanks for reporting.
Should be fixed now.
