### ISSUE TITLE
Fade-out conflicts with Fade-in causing sounds to continue playing as the play button falls out of sync.

### ISSUE THREAD

**Issue by MerchantMage** [mcallegari/qlcplus#1469]
**Describe the bug**
I've noticed this bug since downloading your software, but I couldn't make sense of it until now. I've provided a recording which may better explain this, but I'll describe it anyway.

If you give a sound a fade-in and fade-out duration then attempt to stop the sound before the fade-in is complete, the sound will continue playing and the button you pressed will essentially exist in the wrong state. At this point the button appears to believe the sound has stopped.

So, if you let the fade-in complete, then attempt to stop it, the sound restarts and the button returns to the appropriate state for the sound file. 

Attempting to stop it again during the fade in repeats the glitch. Waiting for it to finish fading in before stopping it allows it to fade out.

**To Reproduce**
1. Create a sound then give it a fade-in and fade-out duration. For my test I used 3s 500ms for each.
2. Play the sound then attempt to stop it before the fade in is complete.

**Expected behavior**
The sound should fade-out when the sound is stopped even if it's still fading in.

**Screenshots (Video)**
https://github.com/mcallegari/qlcplus/assets/149114074/dc6004ff-b9cd-434b-9fea-947df5102962

**Desktop (please complete the following information):**
 - OS: Windows 11
 - QLC+ Version 4.12.8 (and earlier)
- hardware setup: Acer Laptop

P.S. Thank you for being so prompt about the sound loop issue. Once this one is solved as well, I should finally be able to move my audio over to QLC+.

**Comment by mcallegari** [comment]
Please test. Should be fixed.
Thanks for reporting
