### ISSUE TITLE
Clicking Virtual Console sound buttons too fast breaks the program

### ISSUE THREAD

**Issue by MerchantMage** [mcallegari/qlcplus#1470]
**Describe the bug**
If you click a virtual console sound button then quickly click it again, the button you click beomes highlighted and you cannot unclick it. The sound you activated will continue playing and you cannot stop it. If you press any other buttons, they will highlight, but nothing will be triggered. If you attempt to return to design mode, the software will freeze up. To fix it you have to close and relaunch the software.

From what I can tell, the conflict happens because you're clicking the button again before the sound actually starts playing.

**To Reproduce**
1. add a sound function and a scene or two
2. assign everything you created to buttons
3. click the sound button then quickly click it again (before the sound starts playing)

**Expected behavior**
The software should remain stable.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - QLC+ Version 4.12.8 (It also occurse in 4.12.7)
- hardware setup: Acer Laptop with a DMX USB input

**Comment by mcallegari** [comment]
Hey, I'm afraid you want things QLC+ is not designed for.
In general QLC+ is not primarily an audio player. For that, I suggest to use dedicated softwares.
Sorry but I won't pick this up.

**Comment by MerchantMage** [comment]
Ah, no worries. I think I found a workaround anyway.
