### ISSUE TITLE
[QLC+ 5] Crash when entering invalid command

### ISSUE THREAD

**Issue by kritzl** [mcallegari/qlcplus#1471]
**Describe the bug**

**To Reproduce**
1. Go to "Simple Desk"
2. On the bottom right enter: `40000 AT 1`
3. Press `ENTER`
4. QLC+ 5 crashes

**Console Output**
```
[Simple Desk] set value for fixture 4294967295 channel 39999 value 1
Got action: 0xC000, history length: 1 (1)
[Simple Desk] get fader for universe 78 fixture 4294967295 channel 39999
Segmentation fault (core dumped)
```

**Expected behavior**
A warning in Command history or just nothing.

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.10
 - QLC+ Version 5 beta2

**Comment by mcallegari** [comment]
Not reproduced. Please try the latest build
