### ISSUE TITLE
Hotkeys are detected when window is active, but not when it's only in focus

### ISSUE THREAD

**Issue by MerchantMage** [mcallegari/qlcplus#1472]
**Describe the bug**
I'm not sure if this fully qualifies as a bug, but it seems important and isn't quite a feature.
Taking your advice to use other software for my audio I've been trying to make use of hotkeys so I'm not constantly switching programs to run my lights, sound and other tools... However, the program can't currently listen for hotkeys while it's in the background. 

I tried to get around this by using scripts with the controlfocus command via autohotkey. This command gives a specified window focus so the script can send it a keyboard input, but doesn't make it active, so your workspace remains nice and neat without programs popping up all the time. It works great for my other programs, but not with QLC+. Apparently this software will only detect a hotkey if the window is active, so, even this workaround hits a brick wall. 

Suffice to say, Autohotkey is incompatible with QLC+ due to this problem and that makes it a lot harder to use it in a setup where you need to be quickly effective with more than just DMX lights. I'm not sure if it's easier to make QLC+ play nice with autohotkey or to just have a feature in the software that listens for hotkeys while it's in the background, but either would do the trick really.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - QLC+ Version 4.12.8

**Comment by mcallegari** [comment]
I think you're abusing of GitHub now.
Please use the forums for generic discussions.
You cannot really ask a software to listen to keys while it's in background. Surely not to QLC+ 4.
That's why most of the QLC+ users use specific controllers implementing industry standards like MIDI or OSC.

**Comment by ideen1** [comment]
@mcallegari  Just wondering if this is the case, why does QLC+ trigger a Mac system request to monitor keystrokes in the background? Is this for a different feature or a security loophole?

**Comment by MerchantMage** [comment]
That might be it actually. I certainly don’t agree that software can’t do
this as it’s a common feature in many programs. I thought it might have had
something to do with the way the GUI was built, but your suggestion seems
more likely.
