### ISSUE TITLE
Video format

### ISSUE THREAD

**Issue by JonnyTech** [mcallegari/qlcplus#1473]
**Describe the bug**
Videos are not recognised

**To Reproduce**
Add a video file to the show manager.

**Expected behavior**
Adding a video file should show its duration, resolution and codec..
Nothing is displayed.

**Screenshots**
![image](https://github.com/mcallegari/qlcplus/assets/3584732/26184525-3671-4b55-a95c-cb0d6fd5289e)

**Desktop (please complete the following information):**
 - OS: Windows 10 and Debian 12
 - QLC+ Version: Latest releases, betas and CI artifacts
- hardware setup (mandatory for audio/video issues)

**Additional context**
With audio I realised that it has to be a .wav format.
Tried .mp4, .avi, .mkv, .webm and .h264 files.

What format should the video file be encoded as for QLC+ to recognise it?

**Comment by JonnyTech** [comment]
I have found from

https://www.qlcplus.org/old/docs/html_en_EN/questionsandanswers.html

that Windows needs K-Lite_Codec_Pack installed.

Whats needs to be done for it to work in Linux?

**Comment by mcallegari** [comment]
https://www.qlcplus.org/forum/viewtopic.php?f=12&t=15225

Please use the forums for such generic support requests

**Comment by JonnyTech** [comment]
Thank you for the link, very much appreciated.

The search function on the forum does not work, else Ibwould have found the solution. Hopefully this helps others with the same issue.
