### ISSUE TITLE
/dev/ttyUSB0 disappears after closing QLC+

### ISSUE THREAD

**Issue by nospam2k** [mcallegari/qlcplus#1486]
**Describe the bug**
After starting QLC+ and exiting. /dev/ttyUSB0 is no longer showing.

**To Reproduce**
1. Reboot and don't run QLC+
2. ls /dev/ttyUSB* shows.
3. Start QLC+ and then exit.
4. ls /dev/ttyUSB* shows nothing.

**Expected behavior**
Should not lose ttyUSB0

**Desktop (please complete the following information):**
 - OS: Linux
 - QLC+ Version 4.12.7
 - Old Mac mini using Ubuntu w/Entec USB Pro

**Additional context**
I have written a little usbreset app in C and if I reset the root hub, ttyUSB0 comes back. I imagine (though I haven't tried) unplugging and replugging the Entec DMX Pro would restore as well.

**Comment by mcallegari** [comment]
Should be fixed, please test

**Comment by nospam2k** [comment]
I would love to but I downloaded 4.12.7 source for linux, edited the plugins/dmxusb/src/libftdi-interface.cpp file and tried to build but failing with simple things.

Can't find any CMakeLists.txt files to try and manually compile.

cmake -DCMAKE_PREFIX_PATH="/home/david/Qt/5.15.2/gcc_64/lib/cmake" ..
CMake Error: The source directory "/home/david/Src" does not appear to contain CMakeLists.txt.

cpack -G DEB
CPack Error: CPack project name not specified

On a whim I tried running create-deb.sh which isn't documented on the compile page. I get:
/usr/bin/env: ‘python’: No such file or directory

**Comment by mcallegari** [comment]
Every commit generates a build via Github actions
https://github.com/mcallegari/qlcplus/actions

**Comment by nospam2k** [comment]
Sorry for my ignorance, but where do these builds live?

**Comment by nospam2k** [comment]
Ok, thx. I'm new to appImage, can you use it with normal command line parameters or is there a way to install an appimage so I can test it?

**Comment by nospam2k** [comment]
Ok, I tried running and it looks like some of the command line params work but not all as it didn't auto start using qlcplus.appimage -p -w --open /home/church/.qlcplus/Workspaces/concert.qxw.

But... the port is still gone on closing. I tried just running with no params to just open and close the app and the port is still gone.
