### ISSUE TITLE
QLC+ does not load a saved file at startup

### ISSUE THREAD

**Issue by Luni-4** [mcallegari/qlcplus#1487]
**Describe the bug**
When a saved file is opened in `QLC+ 4.12.7` on Windows 10, the file is not opened immediately at startup. You have to open it manually in a second phase.

**To Reproduce**
1. Open `QLC+ 4.12.7` which already has a saved file
2. The file is not immediately shown

**Expected behavior**

Show the saved file immediately once the application is opened

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - QLC+ Version 4.12.7

Thanks in advance for your help!

**Comment by mcallegari** [comment]
It means you haven'tinstelled QLC+ with admin rights

**Comment by Luni-4** [comment]
It works! Thanks a lot for your help!
