### ISSUE TITLE
Crash when accessing web interface

### ISSUE THREAD

**Issue by mcallegari** [mcallegari/qlcplus#1488]
Reported 
https://www.qlcplus.org/forum/viewtopic.php?t=16811

Show file
[Virtual_Console_Template.zip](https://github.com/mcallegari/qlcplus/files/13493893/Virtual_Console_Template.zip)

**Comment by mcallegari** [comment]
@Itay-Lifshitz

**Comment by Itay-Lifshitz** [comment]
> @Itay-Lifshitz

Sorry. Forgot to check null pointer there.
Will test and check the codes thoroughly later.
Thanks for notifying me.
