### ISSUE TITLE
Unable to control single LEDs

### ISSUE THREAD

**Issue by JonnyTech** [mcallegari/qlcplus#1494]
**Describe the bug**
Single channel in QLC operates on three physical fixtures

**To Reproduce**
1. Connect a WS2811 LED strip
2. Add fixture Generic RGB
3. Go to Simple Desk tab
4a. Slider 1 operates red pixels on first three LEDs
4b. Slider 2 operates green pixels on same three LEDs
4c. Slider 3 operates blue pixels on sane three LEDs

**Expected behavior**
Each lider should only operate on a single LED

**Screenshots**
![image](https://github.com/mcallegari/qlcplus/assets/3584732/6817bda7-d4ca-4f66-b8fb-0f8e7a187531)
![image](https://github.com/mcallegari/qlcplus/assets/3584732/056ec9a0-f95c-4f22-bca4-333c220bf06b)
![image](https://github.com/mcallegari/qlcplus/assets/3584732/49ab855d-5868-4257-b6ea-3cf9b2216708)

**Desktop (please complete the following information):**
 - OS: Debian 
 - QLC+ Version: 4.2.17
 - hardware setup: DMXKing LeDMX4 PRO

**Additional context**
Please do explain if I am doing something wrong.

**Comment by yestalgia** [comment]
Bro this is how LED strip like this works.

You bought the cheap version which has 3 segment groupings.

Talk to your supplier if this is not expected

**Comment by JonnyTech** [comment]
Thank you, I was completely unaware of groupings. How would I know what to look for? There is no documentation showing that unless I do not understand the terminology.

**Comment by yestalgia** [comment]
> Thank you, I was completely unaware of groupings. How would I know what to look for? There is no documentation showing that unless I do not understand the terminology.

Your supplier will tell you if the strip is grouped like this, it's not really up to QLC+

For example, this strip is grouped:
https://www.enttec.com.au/product/led-pixel-strip/black-led-pixel-strip/

While this strip allows individual control of the LEDs:
https://www.enttec.com.au/product/led-pixel-strip/8px60-12-b2-5m-black-12v-single-led-control-pixel-strip/

Most of the time, the dead giveaway is the copper attachment points.

Notice that on your strip, the copper pads come every 3 LEDs where as on most individual controlled LED strips, the copper pads will be present after each LED.


Hope this helps. If you have any further questions please make a forum thread.

**Comment by JonnyTech** [comment]
Thank you very much for the clear and detailed reply.
