### ISSUE TITLE
RGBScript property type "integer" and "string" not available

### ISSUE THREAD

**Issue by Taste62** [mcallegari/qlcplus#1497]
The rgbscript property types "integer" and "string" only work in the developement tool and not in QLC+.

![image](https://github.com/mcallegari/qlcplus/assets/154439445/df830ffc-712b-4028-81c5-acbc1d7eb4fa)
in comparison to
![image](https://github.com/mcallegari/qlcplus/assets/154439445/099a2dda-fd00-4401-8771-c4ac173e4589)

Here is the file I used for testing, I had to add an aditional .txt file extension, because github wouldn't let me upload it.
[propertyDemo.js.txt](https://github.com/mcallegari/qlcplus/files/13779838/propertyDemo.js.txt)

**Comment by Taste62** [comment]
"integer" is not that important to me, because I could just use "range" with a low starting value and a high end value or if "string" works, I could use that.

In contrast "string" would enable me to:
a) Accept hex colors instead of using a drop-down menu to select colors, when more than two are needed.
b) Take large inputs in a single input field for example a list of colors to go through.
c) Take mathematical expressions as an input, which then could be drawn on the rgb-panel.

**Comment by mcallegari** [comment]
See 26e22a2300b8be5091f819b38bf85f2ae29f94cc and ad7ec2f62b074314c2a00e583b0e92132b65ea01
I have implemented 'string' and turned 'integer' into 'float' which could add more value (integer can be done via range)

Please test and report if everything works as expected.
And moreover, the usage you will do about it :wink:
