### ISSUE TITLE
RGBScript property "string" takes up all available width

### ISSUE THREAD

**Issue by Taste62** [mcallegari/qlcplus#1499]
Having at least one property of type "string" in the property list results in it taking up all available space, instead of just a bit as the other components.

Normal property window:
![image](https://github.com/mcallegari/qlcplus/assets/154439445/bb0d9c55-377d-4470-a3e5-ca3953dc20b4)
-> The property window has it's usual width.

Property window of the String function:
![image](https://github.com/mcallegari/qlcplus/assets/154439445/60d98b0a-6b43-4512-8552-c847d76d0340)
-> The property window has it's usual width.

Property window with "string" property and a large rgbmatrix:
![image](https://github.com/mcallegari/qlcplus/assets/154439445/c0e5fd9d-a501-4200-9c42-f220789b3655)
-> The property window width is limited by the size of the rgbmatrix.

Property window with "string" property and a small rgbmatrix:
![image](https://github.com/mcallegari/qlcplus/assets/154439445/cef807f8-3d03-4241-8abc-5ed49fab0bd3)
-> The property window width is limited by the direction control UI under the rgbmatrix.

Windows 10, QLC+ 4.12.8 from GitHub
DMX USB & Velleman are disabled

**Comment by mcallegari** [comment]
@Taste62 just checked. DMX USB is working as expected on GitHub Action Windows builds.

**Comment by Taste62** [comment]
I just couldn't figure out, what file to download from the drivers page for Windows 10 64bit, so i disabled it like I was told to do in the build instructions. I don't know if that somehow influenced the velleman plugin, but the build stoped with this error message, so just disabled it too.
`[ 55%] Automatic MOC and UIC for target midi_test
[ 55%] Built target midi_test_autogen
[ 56%] Built target midi_test
[ 56%] Automatic MOC and UIC for target velleman
[ 56%] Built target velleman_autogen
make[2]: *** No rule to make target 'C:/Qt/K8062D/K8062D.a', needed by 'plugins/velleman/src/velleman.dll'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:5850: plugins/velleman/src/CMakeFiles/velleman.dir/all] Error 2
make: *** [Makefile:156: all] Error 2`

**Comment by mcallegari** [comment]
Oh, I thought you were using automated builds.
Step back..do you know what GitHub action builds are and how to download the built artifacts?

**Comment by Taste62** [comment]
Nope, how do they work?

**Comment by mcallegari** [comment]
Every time I push a change to GitHub, 4 builds are automatically generated and can be downloaded from the "Actions" section of GitHub. Pick a commit and scroll down until you see the Artifacts section.

**Comment by Taste62** [comment]
Ok, thanks, found it!
