### ISSUE TITLE
Appimage command-line parameter

### ISSUE THREAD

**Issue by JonnyTech** [mcallegari/qlcplus#1500]
**Describe the bug**
Unable to start the AppImage with command-line parameters

**To Reproduce**
- Download the AppImage file 
- Make it executable 
- Start it with a command-line paramater 
- See error

```
$ wget https://www.qlcplus.org/downloads/5.0.0_beta3/QLC+_5.0.0_beta3-x86_64.AppImage
$ chmod +x QLC+_5.0.0_beta3-x86_64.AppImage
$ ./QLC+_5.0.0_beta3-x86_64.AppImage -w

Q Light Controller Plus version 5.0.0 Beta 3
This program is licensed under the terms of the Apache 2.0 license.
Copyright (c) Heikki Junnila (hjunnila@users.sf.net)
Copyright (c) Massimo Callegari (massimocallegari@yahoo.it)

Q Light Controller Plus: Unknown option 'w'.

```

**Expected behavior**
The command-line parameters should be passed to the application

**Desktop (please complete the following information):**
 - OS: Debian Linux
 - QLC+ Version 5.0.0 Beta 3

**Additional context**
Without that ability, I cannot use the web interface.
Maybe enabling the web interface can be implemented in settings?

**Comment by JonnyTech** [comment]
I am an idiot. Just checked the QLC+ 5 Status document and see that the web interface is missing from version 5.

Is there any other way to control QLC+ 5 remotely? I have scripts that run only on v5 and would like to trigger them from an external input.

**Comment by yestalgia** [comment]
> I am an idiot. Just checked the QLC+ 5 Status document and see that the web interface is missing from version 5.
> 
> Is there any other way to control QLC+ 5 remotely? I have scripts that run only on v5 and would like to trigger them from an external input.

You could use the Web Interface of v4 and use it to trigger an artnet output which could then trigger your script in V5

**Comment by JonnyTech** [comment]
> You could use the Web Interface of v4 and use it to trigger an artnet output which could then trigger your script in V5

Interesting, thank you very much @yestalgia - it sounds complicated but I shall try it
