### ISSUE TITLE
Audio Trigger updates VC slider value, slider value change is not propagated

### ISSUE THREAD

**Issue by hobb3r** [mcallegari/qlcplus#1509]
**Describe the bug**
With a Audio Trigger configured to update a VC slider, the slider correctly appears to have it's value changed. However, the updated value of the slider is not reflected in simple desk or fixture monitor when the slider is in level mode.

**To Reproduce**
1. Add a fixture
2. Go to VC
3. Add a slider
4. Modify slider, configure in Level mode, select a fixture channel, confirm changes
5. In VC, add Audio Trigger
6. Modify audio trigger, set Volume Bar to type "VC Widget", assign to the slider.
7. Enable operate mode, enable audio trigger

With audio playing the slider moves with the volume bar from the audio trigger. If you look in Simple Desk or Fixture Monitor the value is not propagated.

**Expected behavior**
The value of the slider is reflected in Simple Desk and Fixture Monitor regardless of how the value of the slider was set.

**Desktop (please complete the following information):**
 - OS: Linux (Ubuntu 22.04 and 23.10)
 - QLC+ Version: 4.12.4 (22.04) and 4.12.7 (23.10)
- hardware setup: N/A

**Additional context**
An interesting observed behavior: if you click and hold on the slider while in operate mode the value will propagate continually (while click is held).

**Comment by mcallegari** [comment]
Fixed, thanks for reporting
