### ISSUE TITLE
Two Audio Triggers Volume Sliders Do Not Work Independently

### ISSUE THREAD

**Issue by guidoffm** [mcallegari/qlcplus#1510]
I added two audio triggers (with 5 audio spectrum bars each). 

Each audio trigger shows a volume slider on the right,
If both audio triggers are activated at once and I change the volume slider for the first, it affects the 2nd audio trigger as well. But the volume slider in the 2nd audio trigger does not change.

 - OS: Windows 11
 - QLC+ Version 4.12.7

**Comment by mcallegari** [comment]
Volume faders are now in sync. Thanks for reporting.
Please keep in mind that there is only one audio source so multiple audio triggers can't have independent volume levels (it's like changing the Windows microphone input level)
