### ISSUE TITLE
Rounded rectangle icon on macOS

### ISSUE THREAD

**Issue by fwcd** [mcallegari/qlcplus#1512]
As of macOS 11, the convention is that all icons should use a rounded rectangle shape, as outlined by Apple's Human Interface Guidelines: https://developer.apple.com/design/human-interface-guidelines/app-icons#macOS

The current logo looks a bit out-of-place next to most other apps:

![image](https://github.com/mcallegari/qlcplus/assets/30873659/40051043-2260-48b7-816f-e28457d20f34)

Therefore it would be nice if QLC+ could adopt a corresponding shape on macOS (I am not proposing to change to icon on all platforms). Here are some ideas how the macOS icon could look like:

<img width="200" src="https://github.com/mcallegari/qlcplus/assets/30873659/6e4824dc-8ca1-4056-bd70-01941abe5b65">
<img width="200" src="https://github.com/mcallegari/qlcplus/assets/30873659/43ccd47e-b1c7-4bc6-aae3-b45e7dc793e6">
<img width="200" src="https://github.com/mcallegari/qlcplus/assets/30873659/1bde2357-f4fe-4455-8147-b10f2b91469e">
<img width="200" src="https://github.com/mcallegari/qlcplus/assets/30873659/f83ee4ec-2ac3-48f4-acd6-2c4116fccfe8">
<img width="200" src="https://github.com/mcallegari/qlcplus/assets/30873659/05ec72d7-e520-460e-9278-8327a6ca5356">
<img width="200" src="https://github.com/mcallegari/qlcplus/assets/30873659/4763f0bb-56ae-4465-876e-d27353e2b2c9">

Each of these icons is an SVG, so feel free to use/adapt any of them: [`qlcplus-macos-svg.zip`](https://github.com/mcallegari/qlcplus/files/14132698/qlcplus-macos-svg.zip)

**Comment by yestalgia** [comment]
What a great suggestion! Which one is your favourite? - I don't have a Mac to test with but I can have a look at the code and see what I can do. Hopefully we can use a different icon for the MacOS build.

**Comment by mcallegari** [comment]
I like the one with gray background. I think it will work OK either on dark or light mode.

**Comment by yestalgia** [comment]
> I like the one with gray background. I think it will work OK either on dark or light mode.

I'll get started on a separate branch to make sure we can ship it independently of the other icon work.

**Comment by mcallegari** [comment]
I have attempted to make a bundle with this but what looked "gray" to me is instead tranparent!

![Schermata 2024-02-03 alle 15 11 41](https://github.com/mcallegari/qlcplus/assets/2951337/6df8636e-4cb2-4412-a75e-2daaf8eaff00)

I'll have to do everything again 😢

**Comment by mcallegari** [comment]
Alright, this is it

![Schermata 2024-02-03 alle 15 54 58](https://github.com/mcallegari/qlcplus/assets/2951337/8420c4e4-3baf-4ecf-af3a-762d217c7001)

Now change a letter and tell VLC to do the same lol
