### ISSUE TITLE
HTP/LTP Question

### ISSUE THREAD

**Issue by guidoffm** [mcallegari/qlcplus#1519]
I create a one channel generic fixture. The I create a scene that sets the fixture to 255. When I activate the scene the output is set to 255 as expected and when I then deactivate the scene the output is reset to 0 as expected.

Now, I change the the channel from HTP to LTP. When I the activate the scene the output is set to 255 as expected. When I then deactivate the scene the output remains at 255. I expect it to be reset to 0.

When I read about the meaning of LTP and HTP I understand this setting affects the output when one channel is used in more than one scene at once. I do not understand the behaviour when I simply activate and deactivate a scene.

How did I find about out this behaviour? I have created my own fixture definition for a device and set some channels to "Intensity" and other channels e.g. to "Maintenance". Only the channels defined as "Intensity" are reset when I deactivate a scene.

QLC Version: 4.12.7

**Comment by mcallegari** [comment]
Please submit this question to the forums
https://www.qlcplus.org/forum/
Thank you
