### ISSUE TITLE
Corrupted Project

### ISSUE THREAD

**Issue by PLAYGEANT** [mcallegari/qlcplus#1521]
Hello everybody, yesterday, I think I closed QLC+ wrong and my project is now corrupted.
When I try to load it I have the message Error : 

"Unable to access resource"
![image](https://github.com/mcallegari/qlcplus/assets/54994647/29a530c6-afb2-4853-9787-631ea8131649)

I come to you to know how I can restore my file or "uncorrupt" the file ?
Thanks for the help
Cordially
Play Geant

 - OS: Windows 10
 - QLC+ 4.12.3

**Comment by PLAYGEANT** [comment]
Here is my file project corrupted : https://we.tl/t-j4gx7WCXXC

**Comment by mcallegari** [comment]
This project is gone. It's all zeroed.
Next time please submit this to the forums to get more chance of a faster help.
