### ISSUE TITLE
Blackout behaviour: EFX movements disrupted

### ISSUE THREAD

**Issue by yestalgia** [mcallegari/qlcplus#1523]
**Describe the bug**
The change to the way Blackout works in QLC+ is a welcome one. However there's a bug when it comes to EFX values.

When running a show, the desired result of a blackout button is to only stop light from exiting the fixtures.  However, when the blackout button is pressed it also temporarily disables EFX's 8-bit values. This results in the fixatures violently returning to their last set position. 

**To Reproduce**

I've created a test showfile with two universes to help reproduce this issue. The first universe contains the fixtures but the problem is observed in the second universe which is taking the output from the first. (This can also be tested with hardware.) NOTE: The DMX monitor shows what should be happening, not actually what QLC+ outputs.

1. Open QLC+
2. Open attached Show File
3. Switch to Live Mode
4. Activate the "Aura Base Position" scene from the Virtual console
5. Activate the "New EFX 01" EFX from the Virtual Console
6. NOTICE: the correct values in the simple desk for Universe 1
7. NOTICE: the incorrect (stuck) values for Universe 2

**Expected behavior**
We should see the output from QLC+ match the simple desk and DMX Monitor for Universe 1.

**Screenshots**
![image](https://github.com/mcallegari/qlcplus/assets/42596763/7ca73a41-8608-47f5-8910-56b68a1f330d)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - QLC+ Version [e.g. 4.12.7]

**Additional context**
[EFX Blackout Problem.zip](https://github.com/mcallegari/qlcplus/files/14417689/EFX.Blackout.Problem.zip)

[Video of Problem](https://youtube.com/watch?v=fqy60yNIisY)

**Comment by yestalgia** [comment]
I've created a YouTube video to show the problem. (Sorry about the quality it's downscaled from 4k)
https://youtube.com/watch?v=fqy60yNIisY

**Comment by mcallegari** [comment]
Is this still verified with 4.13.0 or latest build?

**Comment by yestalgia** [comment]
## Observation: 
I did a new test which found a problem still exists. The following change in behaviour:
Now all position channels for the fixtures "Pause" (They stop moving when blackout is active) not just the 8bit (fine) channels. 


## Test Methodology
Test conducted using Actions Build: https://github.com/mcallegari/qlcplus/actions/runs/8635670652

1. Uninstall QLC+4 and QLC+5
1. Download Actions Build - QLC+-qt5-4.13.1-20240410-d3cf816.exe
1. Install as administrator
1. Download EFX Blackout Problem.zip
1. Extract EFX Blackout Problem and open the file from QLC+
1. Activate the "Aura Base Position" scene from the Virtual console
1. Activate the "New EFX 01" EFX from the Virtual Console
