### ISSUE TITLE
Feedback vs Feedbacks

### ISSUE THREAD

**Issue by yestalgia** [mcallegari/qlcplus#1525]
English convention does not allow for the pluralisation of "Feedback"

There are a number of classes and dialogues that now refer to "Feedbacks" which need to be renamed.

![Screenshot_20240310_133017_Chrome.jpg](https://github.com/mcallegari/qlcplus/assets/42596763/608de92b-2e9b-47a1-99e7-309efdf9b5c2)

**Comment by mcallegari** [comment]
Fixed, thanks for reporting this.
Note that there was a "Feedbacks" tag in some input profiles. I fixed it too so user custom profiles might break with this change
