### ISSUE TITLE
[Feature] Add Possibility to Move Up/Down Channels in the Editor

### ISSUE THREAD

**Issue by Foul** [mcallegari/qlcplus#1531]
Asking to add a simple feature : Possibility to Move Up/Down (order them) Channels in the Editor(and maybe in QLC+ too)

<img width="397" alt="Channels" src="https://github.com/mcallegari/qlcplus/assets/829842/3db9d65c-4005-4125-a9a7-50e9c016885d">

thx :)

**Comment by mcallegari** [comment]
Channel order in that screen is irrelevant.
What is definitely relevant is the order in the Modes tab. There you have the button to move channels up/down.
