### ISSUE TITLE
Blackout not working anymore on QLC+ 4.13.0 

### ISSUE THREAD

**Issue by mishcazzulani** [mcallegari/qlcplus#1533]
**Describe the bug**
After upgrading QLC the blackout button doesn't work anymore

**To Reproduce**
1. Create a new show
2. Patch some dimmers
3. Create a virtual desk with some fader set to control the dimmers's levels
4. Go live
5. Toggle blackout doesn't work

**Expected behavior**
I expect the blackout button to set all dimmers to 0, as in previous versions
Please note that the grandmaster fader works so it isnt a patch issue

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - QLC+ Version 4.13.0
- Simple one universe setup with an Enttec dongle

**Additional context**
-

**Comment by yestalgia** [comment]
Hey, there has been a change to QLC+ dimming which actually came about in 4.12.7

This was done so only HTP (highest takes priority) channels were set to 0. Which means when you hit blackout the movement channels don't go to zero.

From Massimo on the forum: "Blackout was once resetting ALL channels (HTP+LTP)
As requested, I adapted it like all the consoles in the world do: reset only HTP channels
Stop all functions instead, stops ALL the running functions, leaving LTP channels where they were (so they're not reset too)"

I'm pretty sure that blackout still works for the generic dimmers but I don't have it in front of me.

Can someone else confirm?
