### ISSUE TITLE
Missing qlcplus-fixtureeditor icon on Program List (Launcher)

### ISSUE THREAD

**Issue by Foul** [mcallegari/qlcplus#1534]
Install QLC+ 4.13.0 on KDE Neon (plasma 6.0.2)

Q Light Controller Plus icon is on my Program Launcher but not qlcplus-fixtureeditor
Must launch in terminal to run it.

Was working on 4.12.7

edit : if i click on a .qxf file.. he doesn't know which program to open it with either.

**Comment by sbenejam** [comment]
I can confirm this issue on Ubuntu 22.04 and Plasma 5.24.7.

Missatge de Foul ***@***.***> del dia dj., 21 de març 2024 a
les 20:24:

**Comment by mcallegari** [comment]
Thanks for reporting. There's probably one file missing in the deployment of the fixture editor
I'll check it later today
