### ISSUE TITLE
cursor position don't change after moving it in Shows

### ISSUE THREAD

**Issue by EliotAmn** [mcallegari/qlcplus#1538]
**Describe the bug**

In the show editor, when I move the cursor somewhere and then hit "Play", the cursor returns to its last position without taking into account the change made. It seems that I have to hit "Stop" every time, and it's not very convenient when editing large shows, especially since there is no keyboard shortcut to do so.

**Desktop :**
 - OS: Windows 10
 - QLC+ Version 4.13

**Comment by mcallegari** [comment]
Not reproduced.
Please improve your report by attaching a workspace and exact instructions how to reproduce the issue

**Comment by mcallegari** [comment]
What is not practical? Hitting stop instead of pause?
