### ISSUE TITLE
[QLC+ 5] Cannot use the full 512 channels of a universe

### ISSUE THREAD

**Issue by mxdumas** [mcallegari/qlcplus#1542]
**Describe the bug**
QLC+ does not allow to use the full 512 channels on a universe. For example, if you try to add 16x 32 channels fixtures, it will patch the first 15 to universe 1 and the last one to universe 2, even though they should fit on a single universe.

**To Reproduce**
Add 16 Martin Mac Viper Performance in Basic mode to the patch.

**Expected behavior**
16x32=512, so it should fit in a single universe. Fixture 16 should be patched at 1.481.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - QLC+ 5.0.0 Beta 3

**Comment by mxdumas** [comment]
See proposed fix in PR #1543. Thank you!

**Comment by mcallegari** [comment]
Fixed by #1543
