### ISSUE TITLE
OSC error when an _ is present in the address

### ISSUE THREAD

**Issue by Andrea-169** [mcallegari/qlcplus#1547]
**Describe the bug**
When a _ (underscore) symbol is present in OSC address, in QLC+ this happens:
- The acquisition of the address during the creation of the input profile works correctly.
- The reception of an OSC message generated by the OSC software is correctly interpreted by QLC+.
- The OSC message generated by QLC+ presents the address truncated from _ to forward.

**To Reproduce**
In the OSC software, create a fader with "test_1" ID and associate it with a fader in QLC+.
1. In the OSC software, move the created fader and check that QLC+ correctly interpreters the OSC message (in the console log of the OSC software, the OSC address generated is "test_1").
2. In QLC+ move on the corresponding fader and verify that the fader in OSC software does not move (in the console log of the OSC software, the OSC address generated by QLC+ is "test").

**Expected behavior**
QLC+ should generate the correct OSC address (in the example "test_1").

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Windows 11
 - QLC+ Version 4.13.0

**Additional context**
The same problem is also present in the 4.12.7 release.

**Comment by mcallegari** [comment]
Underscore is a reserved character used by QLC+ and cannot be used in paths

**Comment by Andrea-169** [comment]
Thank you,
for feedback.
