### ISSUE TITLE
Feature: OSC (and MIDI, ...) resync

### ISSUE THREAD

**Issue by Andrea-169** [mcallegari/qlcplus#1548]
When starting the operating mode of the virtual console, QLC+ carries out a rapid sync of the objects values that have associated an external input, generating the relative OSC messages and, therefore, allowing a rapid setting of the values of the objects in the OSC software.

We kindly ask if it is possible to implement a button in the virtual console that allows at QLC+ to make a resync of values without having to stop and restart the operating mode of QLC+, impossible during a show. This would be extremely useful in case of presence of connection problems that cause a de-synchronization between QLC+ and the OSC software.
The pressure of this hypothetical button would allow a resync of values, without interrupting the active functions.

This is useful not only with OSC, but with any external Sync (MIDI, ...).

**Comment by mcallegari** [comment]
You can use a multiframe that should send feedbacks of the widgets

**Comment by Andrea-169** [comment]
Thank you,
tested now and this workaround works fine.
