### ISSUE TITLE
Waiting Fixtures validation.

### ISSUE THREAD

**Issue by Foul** [mcallegari/qlcplus#1550]
Hi !
I posted 5 weeks ago some new fixtures, and still not validated : 

https://www.qlcplus.org/forum/viewtopic.php?t=17117
https://www.qlcplus.org/forum/viewtopic.php?t=17123
https://www.qlcplus.org/forum/viewtopic.php?t=17119
https://www.qlcplus.org/forum/viewtopic.php?t=17118
https://www.qlcplus.org/forum/viewtopic.php?t=17116

I need them for next month.. if you can look at them... thx :)

**Comment by yestalgia** [comment]
Hi there thanks for this.

You can add these fixtures to your user folder to use them right away.

Read this: https://docs.qlcplus.org/v4/fixture-definition-editor

**Comment by Foul** [comment]
> You can add these fixtures to your user folder to use them right away.

Already done thx :)

**Comment by mcallegari** [comment]
Please don't use GitHub for your personal needs.
This is very unfair and disrespectful for all the other users that share fixtures and don't complain like you.
Moreover you always had a solution for this and probably didn't care to read the manual or solve it by yourself before opening this issue.
Don't do this again.
