### ISSUE TITLE
QLC Style file ignored

### ISSUE THREAD

**Issue by chalbin73** [mcallegari/qlcplus#1555]
**Describe the bug**
Hi i'm trying to apply a style to QLC+, however, after placing the file in the correct folder (`~/.qlcplus`), the style is ignored.

**To Reproduce**
1. Place style file in the correct folder
2. Open QLC+
3. The default style is still being used

**Expected behavior**
The style placed in `~/.qlcplus` should be applied to the interface

**Screenshots**
```shell
~/.qlcplus $ pwd
/home/<user>/.qlcplus
~/.qlcplus $ ls -lah
total 32K
drwxr-xr-x  7 <user> <user> 4.0K Apr 25 20:37 .
drwx------ 87 <user> <user> 4.0K Apr 25 20:36 ..
drwxr-xr-x  2 <user> <user> 4.0K Apr 25 20:37 fixtures
drwxr-xr-x  2 <user> <user> 4.0K Apr 25 20:37 inputprofiles
drwxr-xr-x  2 <user> <user> 4.0K Apr 25 20:37 miditemplates
drwxr-xr-x  2 <user> <user> 4.0K Apr 25 20:37 modifierstemplates
-rw-r--r--  1 <user> <user> 3.9K Apr 25 20:36 qlcplusStyle.qss
drwxr-xr-x  2 <user> <user> 4.0K Apr 25 20:37 rgbscripts
```
The folders (fixtures, inputprofiles ...) were automatically crated by QLC+.

**Desktop (please complete the following information):**
 - OS: Artix Linux, OpenRC, 6.8.4-zen1-1.1-zen. 
 - QLC+ Installed with the AUR : `https://aur.archlinux.org/packages/qlcplus`
 - QLC+ Version :  `Q Light Controller Plus version 4.13.0 GIT`
- hardware setup (mandatory for audio/video issues)

**Additional context**
The style file I used is the one at : `https://github.com/EmerickH/qlcplus-dark-theme`

**Comment by mcallegari** [comment]
That theme is no longer compatible with QLC+ 4.13.0 (it is with previous versions)
Ask the author to update it or read the documentation and fix it yourself.
https://docs.qlcplus.org/v4/advanced/custom-ui-style
