### ISSUE TITLE
WebAPI Test page doesn't contain Animation widget example

### ISSUE THREAD

**Issue by yestalgia** [mcallegari/qlcplus#1559]
### Issue Description:
One of our users recently brought up a concern regarding the lack of documentation for retrieving information about Animation widgets through the QLC+ Web API. Currently, the [Web API test page](https://www.qlcplus.org/Test_Web_API.html) does not include any information on how to access Animation widget data.

### User Report:
On our forum, a user expressed their difficulty in retrieving Animation widget information through the API. They mentioned that while the web access page visually displays all the added buttons inside the animation, accessing this information programmatically seems challenging as the page is prerendered and doesn't expose the actual API calls. Despite being able to control values manually by inspecting the websocket traffic, automating this process requires retrieving the information first.
https://qlcplus.org/forum/viewtopic.php?t=17313

### Action Needed:
It's imperative to address this issue by updating the Web API test page to include documentation specifically for retrieving Animation widget data. This would enable users to programmatically interact with Animation widgets and automate processes effectively.

### Proposed Solution:

- Add documentation to the Web API test page explaining how to retrieve Animation widget information through API calls.
- Provide examples and code snippets demonstrating the API calls necessary to fetch Animation widget data.
- Ensure clarity and comprehensiveness in the documentation to assist users in seamlessly integrating Animation widget functionality into their projects.

Additional Notes:
Ensuring comprehensive documentation for all features, including Animation widgets, is essential for empowering users to leverage the full potential of QLC+ through the Web API. By addressing this issue, we can enhance the usability and accessibility of QLC+ for our diverse user community.

**Comment by yestalgia** [comment]
@Itay-Lifshitz Can you take a look at this for us? The code for the Web API Test Page can be found here:
https://github.com/mcallegari/qlcplus/blob/master/webaccess/res/Test_Web_API.html

**Comment by mcallegari** [comment]
This is the added API:
https://github.com/mcallegari/qlcplus/blob/master/webaccess/res/virtualconsole.js#L707

**Comment by Binary-Vanguard-12138** [comment]
> @Itay-Lifshitz Can you take a look at this for us? The code for the Web API Test Page can be found here: https://github.com/mcallegari/qlcplus/blob/master/webaccess/res/Test_Web_API.html

OK, will check.

**Comment by Binary-Vanguard-12138** [comment]
@mcallegari In #1566 , I added some components for demonstrating the virtual console animation widget.
Currently, it is only for preset buttons.
I would like to ask what kind of Animation widget information we need to retrieve through API calls. @yestalgia

**Comment by RektByMemes** [comment]
@Binary-Vanguard-12138 I was the person who raised the question on the QLC+ forum. I checked your changes and can see you made an example on how to trigger the animation preset with a controlId. Is there any way to retrieve this Id of the preset buttons that are present on the animation?

**Comment by mcallegari** [comment]
@RektByMemes I have added an API to retrieve the sub-controls information. In conjunction with the recently added `MATRIX_*` commands in [virtualconsole.js](https://github.com/mcallegari/qlcplus/blob/master/webaccess/res/virtualconsole.js) there should be enough flexibility now.

Since this has been basically implemented for you and considering the effort that 3 people have put in it, please consider to recognize this as a custom feature by supporting the project in any way you can. Thanks

**Comment by RektByMemes** [comment]
Sure, no problem, I'll see how I'll be able to help you
