### ISSUE TITLE
QLC+ 5 Doesn't open (and can't register on forum to report there)

### ISSUE THREAD

**Issue by nigelorr** [mcallegari/qlcplus#1570]
**Describe the bug**
QLC+ 5.0.0 Beta 3 does not open (and forum registration fails)

**To Reproduce**
Not certain on reproduction, sequence of installation was
1. QLC+ 4.12 installed some time ago
2. QLC+ 4.13 installed in same directory as 4.12
3. Run QLC+4.13 and basic tests, appears to run OK
4. QLC+ 5.0.0 beta 3 installed from QLC+_5.0.0_beta3.exe in separate directory for beta testing (C:\QLC+5, 4.13 installed in C:\QLC+)
5. Open QLC+ 5
6. Approx Windows network access request (Public and Private selected)
7. Window does not appear
8. Run C:\QLC+\qlcplus-qml.exe from File Explorer
9. Window does not appear
10. Attempt to [register for web forum](https://forum.qlcplus.org/ucp.php?mode=register) to report issue
11. Enter username, password meeting criteria and valid email
12. Observe "The solution you provided was incorrect" error

**Expected behavior**
QLC+ 5 Window to open
Web forum accept registrations or provide useful feedback on what is wrong

**Screenshots**
N/A, no windows open

**Desktop (please complete the following information):**
 - OS: Windows 10.0.19045 Build 19045
 - QLC+ Version : 5.0.0 beta 3
 - hardware setup: Lenovo T410, testing without DMX hardware connected, runs QLC+ 4.13 without reported faults

**Additional context**
None

**Comment by mcallegari** [comment]
Unfortunately there's not much I can do about this.
The only thing that can make a difference is graphics drivers. Which graphics card do you have? Are your drivers up to date?
QLC+ 5 is much more eager of graphics resources and might require recent hardware.

As for forum registration, "The solution you provided was incorrect" means you haven't filled the proposed Captcha properly.
Try again.

**Comment by nigelorr** [comment]
Thanks @mcallegari . It is an old laptop so that is most likely the problem. It's just Intel HD Graphics 
`Adapter Type	Intel(R) HD Graphics (Core i5), Intel Corporation compatible`
I don't need to run QLC+ 5 on it, 4 already does everything I need and more, but I saw you weren't getting many responses on the beta so thought I'd try to 'do my bit' and check it out.

On the forum registration, I don't get a captcha offered- it looks like this even after being fully populated
![image](https://github.com/mcallegari/qlcplus/assets/812323/591b2bae-6e76-4c75-b688-95f5d6934d45)

Although it is an old laptop, it's not failed to display captcha's before ;-)

Thanks for the fast response.

**Comment by mcallegari** [comment]
That's weird. Have you accepted cookies?
If you notice, there is a Google reCaptcha banner on the right bottom side of the page.
Perhaps you have an extension that blocks parts of the page?

![image](https://github.com/mcallegari/qlcplus/assets/2951337/8e06c457-e1af-4545-b582-d976e9455755)

**Comment by nigelorr** [comment]
Thanks, must have been cookies, reject by default and not had problems with captchas previously. Turned on temporarily and it accepted the registration (without any captcha challenge).

On the presumed old graphics card failure, is there a log which will show the reason for it failing to open, or any information for others who get a similar failure? It probably doesn't matter as v4 does what I need, but I'm sure there are others with old laptops running v4 who might want to upgrade (or beta test). A 'minimum hardware' spec or informative failure message (or even just a log somewhere with an assert message) might be worth considering for production release.

Great work on the software though, doesn't get the praise it deserves for the quality and functionality of V4.

**Comment by mcallegari** [comment]
Unfortunately I believe the issue lays down in the Qt hardware abstraction layer.
Most likely QLC+ will crash without an explanation.
Unfortunately I don't have a PC to reproduce the issue but what I can do is to consider Intel cards "unsupported" or "not recommended" even though many other Windows system that I tried can open v5 without issues.
Are you sure your Intel drivers are up to date?

**Comment by mcallegari** [comment]
Probably this is it: https://doc.qt.io/qt-6/windows-graphics.html

**Comment by mcallegari** [comment]
Closing with no solution at the moment
