### ISSUE TITLE
Missing qlcplus-fixtureeditor.exe from QLC+ 5.0.0 Beta 3

### ISSUE THREAD

**Issue by Foul** [mcallegari/qlcplus#1575]
Uninstalled QLC+ 4.13
Downloaded and installed QLC+ 5.0.0 Beta 3

Installation folder is by default C:\QLC+5

Once installation is complete, Folder "Q Light Controller Plus" is created in the Start Menu Programs with in it :
a shortcut "Q Light Controller Plus" witch point to : C:\QLC+5\qlcplus-qml.exe
and another shortcut "C:\Program Files\QLC+\qlcplus-fixtureeditor.exe" **that does not exist !**

If you search for "qlcplus-fixtureeditor.exe" in C:\QLC+5, the file is missing too.

Last thing, if you want to uninstall QLC+, it's not listed in Parameters / Installed applications : You need to click on the file "uninstall.exe" on the QLC+ Folder.

Hardware : Dell Inspiron 16 plus 7630 / I i7-13620H / 16Go DDR5 / SSD Crucial T500 2To 
Soft : Windows 11 23H2 Build 22631.3593

**Comment by mcallegari** [comment]
Are you serious?
