### ISSUE TITLE
Issue with dylib linking on macOS

### ISSUE THREAD

**Issue by second-string** [mcallegari/qlcplus#1578]
### Template text
``` 
This area is reserved to developers.
If you are not a developer, you are in the wrong place and your issue will be closed.

For discussions, feedbacks, ideas and new fixtures, go to:
http://www.qlcplus.org/forum/index.php
and provide as many details as possible regarding your findings.

Before reporting new issue, please discuss it on the forum. Let's keep the issues tidy!

If you are a developer, you are supposed to have built QLC+ from sources, and started to debug the issue you have found.

Therefore, please provide a crash log or references to the code that are supposed to help the QLC+ developers to resolve the issue.
Also, if your issue concerns a specific platform, please indicate it in the issue title like [platform] description.
```

### Specs
* Machine: Macbook Pro M1 macOS Sonoma 14.4
* Qt: 5.15.13 install through homebrew
* All dependencies install through brew not macports, but I don't think that's the issue here.
* git commit: current master HEAD, `0ce5c5b3da9d2eeca405c961d84dc16812d90b45`

### Issue
`qmake` and `make` execution in the repo are both successful, the issue arises when `make install` is executed. The issue comes from executing targets in the 'platforms/macos/Makefile' file. Here is the log section where it `cd`s to that directory and fails:
```
cd macos/ && ( test -e Makefile || /opt/homebrew/opt/qt@5/bin/qmake -o Makefile /Users/user/Developer/qlcplus/platforms/macos/macos.pro ) && /Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile install
install_name_tool -id @executable_path/../Frameworks/libqlcplusui.1.dylib ~/QLC+.app/Contents/Frameworks/libqlcplusui.1.dylib
install_name_tool -id @executable_path/../Frameworks/libqlcpluswebaccess.1.dylib ~/QLC+.app/Contents/Frameworks/libqlcpluswebaccess.1.dylib
install_name_tool -id @executable_path/../Frameworks/libqlcplusengine.1.dylib ~/QLC+.app/Contents/Frameworks/libqlcplusengine.1.dylib
/opt/homebrew/opt/qt@5/bin/qmake -install qinstall /opt/homebrew/Cellar/libusb/1.0.26/lib/libusb-1.0.0.dylib /Users/user/QLC+.app/Contents/Frameworks/libusb-1.0.0.dylib
install_name_tool -id @executable_path/../Frameworks/libusb-1.0.0.dylib ~/QLC+.app/Contents/Frameworks/libusb-1.0.0.dylib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: warning: changes being made to the file will invalidate the code signature in: /Users/user/QLC+.app/Contents/Frameworks/libusb-1.0.0.dylib
/opt/homebrew/opt/qt@5/bin/qmake -install qinstall /opt/homebrew/Cellar/libftdi/1.5_2/lib/libftdi1.2.dylib /Users/user/QLC+.app/Contents/Frameworks/libftdi1.2.dylib
install_name_tool -id @executable_path/../Frameworks/libftdi1.2.dylib ~/QLC+.app/Contents/Frameworks/libftdi1.2.dylib
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: can't open file: /Users/user/QLC+.app/Contents/Frameworks/libftdi1.2.dylib (No such file or directory)
make[2]: *** [install_LIBFTDI_ID] Error 1
make[1]: *** [sub-macos-install_subtargets] Error 2
make: *** [sub-platforms-install_subtargets-ordered] Error 2
```

You can see the initial warning about invalidating the code signature in the libusb dylib, then it fully fails claiming it can't find the libftdi dylib that it copied to the app Frameworks dir. I have confirmed that the dylib is properly copied there. From my googling, it seems like both of these outputs are the result of some stuff getting mismatched during initial source compilation and the linker link step ([source](https://stackoverflow.com/questions/68061278/changing-dylib-library-path-with-install-name-tool-id-nothing-changes)).

I found where a few libraries are being called with `install_name_tool -change` above in the full log output:
```
install_name_tool -change /opt/homebrew/Cellar/libusb/1.0.26/lib/libusb-1.0.0.dylib @executable_path/../Frameworks/libusb-1.0.0.dylib libdmxusb.dylib && install_name_tool -change /opt/homebrew/Cellar/libftdi/1.5_2/lib/libftdi1.2.dylib @executable_path/../Frameworks/libftdi1.2.dylib libdmxusb.dylib
```

Here's the output of `otool -L /opt/homebrew/opt/libftdi/lib/libftdi1.2.dylib`:
```
/opt/homebrew/Cellar/libftdi/1.5_2/lib/libftdi1.2.dylib:
        /opt/homebrew/opt/libftdi/lib/libftdi1.2.dylib (compatibility version 2.0.0, current version 2.5.0)
        /opt/homebrew/opt/libusb/lib/libusb-1.0.0.dylib (compatibility version 4.0.0, current version 4.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.0.0)
```

Here's all the available dylibs:
<img width="751" alt="Bildschirmfoto 2024-05-30 um 19 07 03" src="https://github.com/mcallegari/qlcplus/assets/6549618/5cb7cbf9-2fbc-4302-bdbd-fa4185dd56c1">

Even if I comment out the `install_name_tool -id` call for the ftdi make target, there's another failure shortly after with a different library. I don't have too much experience with all of this dynamic linking on full-blown operating systems - is there something easy I'm missing here with fixing the link paths?

**Comment by mcallegari** [comment]
Homebrew is not yet supported. Closing, sorry
