### ISSUE TITLE
QLC+ 4.13.1 doesn't run, error on DLL ftd2xx64.dll

### ISSUE THREAD

**Issue by Power2All** [mcallegari/qlcplus#1587]
**Describe the bug**
Error when trying to load QLC+ 4.13.1
Event Viewer in Windows showing an error with ftd2xx64.dll

**To Reproduce**
1. Try to start qlcplus.exe
2. Check Event Viewer

**Expected behavior**
Starting the application just like 4.12.7 did

**Screenshots**
```
Faulting application name: qlcplus.exe, version: 0.0.0.0, time stamp: 0x665a03d0
Faulting module name: ftd2xx64.dll, version: 3.2.16.1, time stamp: 0x60e2fd3b
Exception code: 0xc0000005
Fault offset: 0x0000000000010dd9
Faulting process id: 0x1330
Faulting application start time: 0x01dac3125aacbcca
Faulting application path: C:\QLC 4.13.1\qlcplus.exe
Faulting module path: C:\QLC 4.13.1\ftd2xx64.dll
Report Id: 8d446c86-a506-4dd0-9a54-f9439844176b
Faulting package full name: 
Faulting package-relative application ID: 
```

**Desktop (please complete the following information):**
 - OS: Windows 11 21H2
 - QLC+ Version 4.13.1
 - Laptop

**Additional context**
Problem didn't occur with 4.12.7
Need to use still this version until 4.13.x works as expected.

**Comment by mcallegari** [comment]
Unfortunately this report doesn't add anything new compared to the discussion happened here
https://www.qlcplus.org/forum/viewtopic.php?p=73631

What I know so far is that 
1. version 4.13.1 works on several Windows 10 and 11 installations out of the box
2. removing the ftd2xx64 DLL (which is a dependency of the dmxusb plugin) allows QLC+ to start
3. the ftd2xx64 DLL was not necessary on 32-bit versions (this actually puzzles me)

To be honest I think the point worth to be investigated the most is number 3

**Comment by mcallegari** [comment]
Solution posted in the forums. Closing
