### ISSUE TITLE
Fixture Monitor labels don't display when first opened.

### ISSUE THREAD

**Issue by schofiel** [mcallegari/qlcplus#1593]
**Describe the bug**
When the Fixture Monitor window is opened, although the "Labels" button is selected, the fixtures on display do not show their labels.

**To Reproduce**
1. Start QLC+ with a project (QXW file) containing a collection of fixtures
2. Either with project running OR project not running, click on Fixture Monitor button on Tool Bar (top left) - FM is now displayed, showing fixtures in their defined "stage positions"
3. Verify no fixture labels are displayed, and that the "Labels" button on the FM toolbar is selected (default)
4. Deselect "Labels" button by clicking once. Verify button is now deselected, and that no fixture labels are visible
5. Select "Labels" button by clicking once. Verify button is now selected. Verify all fixture labels are now visible.

**Expected behavior**
When the FM is first opened, if the default window behaviour is "Labels" *selected*, the fixture labels should display immediately.
Alternatively, if the default behaviour is meant to be "Labels" *deselected*, then the button should be off by default and no fixture labels should show.

**Screenshots**
![QLCPlus Fixture Monitor problem](https://github.com/mcallegari/qlcplus/assets/1452433/52fd9283-e857-4a3b-8c16-9c26b8b32a5c)

**Desktop (please complete the following information):**
 - OS: Windows, Linux Mint, Ubuntu.
 - QLC+ Version: all versions to date, currently on 4.13.1
 - hardware setup (mandatory for audio/video issues): N/A - not a hardware problem

**Additional context**
N/A

**Comment by yestalgia** [comment]
Thanks for your report.
