### ISSUE TITLE
Fixture Groups toolbar button functions do not work as expected

### ISSUE THREAD

**Issue by schofiel** [mcallegari/qlcplus#1597]
**Describe the bug**
On the Fixtures Tab (main functions bar, bottom left), with the Fixture Groups tab selected (top left, grouped with Channel Groups), the Move group Up and Move group Down toolbar buttons are always disabled. It is not possible to re-order groups in the list.

**To Reproduce**

1. Start QLC+ with a project (QXW file) containing a collection of fixtures
2. Select Fixtures page using main functions toolbar (bottom left)
3. Verify the project's fixtures, groups, and Universe(s) are displayed in the Fixture group pane of the main window (left side)
4. Click on a defined fixture group to select the group
5. Verify that with the group folder selected, the four Fixture Group management buttons on the toolbar (above left pane) are greyed out and disabled (problem 1: screen shot 1)
6. Click on the "expand" arrow next to the selected group to expand the group
7. Verify the fixture(s) in that group are now displayed, and the  four Fixture Group management buttons remain greyed out and disabled (repeat problem 1: problem 2: screen shot 2)
8. Click on a single fixture displayed in group to select the fixture
9. Verify fixture is selected, and that "Add fixture to Group" and "Remove fixture from Group" on toolbar are now active, and the " (correct observed behaviour, screen shot 3)

**Expected behavior**
Problem 1: When the group is selected (and also when expanded) the "Move Group up" and "Move Group down" buttons should be active to permit re-positioning of group in group list (see screen shot 1)

Problem 2: When the group is selected (and also when expanded) the "Add fixture to Group" and "Remove fixture from Group" should be active (see screen shot 2)

Correct observed behaviour: When the group is expanded and a *feature* is selected,  the "Add fixture to Group" and "Remove fixture from Group" buttons should be active, and the "Move Group up" and "Move Group down" should be disabled (see screen shot 3)

**Screenshots**
Screen shot 1:
![QLCPlus Move Group Up Down problem](https://github.com/mcallegari/qlcplus/assets/1452433/3a5e4d93-791b-4900-9db8-beb818024af4)

Screen shot 2:
![QLCPlus Add Remove Fixture from Group problem](https://github.com/mcallegari/qlcplus/assets/1452433/e121dc46-c755-43bb-81a6-dceb5b87883f)

Screen shot 3:
![QLCPlus Add Remove Fixture from Group expected](https://github.com/mcallegari/qlcplus/assets/1452433/bb89199e-b6bc-4a14-9e69-8947116b9b79)

**Desktop (please complete the following information):**
 - OS: Windows, Linux Mint, Ubuntu.
 - QLC+ Version: all versions to date, currently on 4.13.1
 - hardware setup (mandatory for audio/video issues): N/A - not a hardware problem

**Additional context**
N/A

**Comment by mcallegari** [comment]
Not a bug.
Please read the documentation:
https://docs.qlcplus.org/v4/fixture-manager

Arrows are for **Channel** groups, not for fixture groups.
Frxture Groups are sorted alphabetically and that order cannot be changed.

**Comment by schofiel** [comment]
Then your mouseovers for these buttons are incorrect. I have been using QLC+ for over 6 years now, and regard it as a useful, if somewhat quirky, lighting package. Please do not denigrate your users with comments like this.
You should also note that your implementation breaks many of the Windows style guides, and likewise the Ubuntu style guides.
I have read through the forums, and found no clear answer, which is why I have posted these bugs. They are bugs, not design choices.

**Comment by yestalgia** [comment]
I've reviewed this and while small I think it's a valid issue.
https://github.com/mcallegari/qlcplus/blob/c465e168278937c39640b8e7206d3253c87ea3ae/ui/src/fixturemanager.cpp#L913

I'd propose that these icons are removed from this view and only appear when the channel groups tab is selected, since the order is determined by the column headers. (Name, Channel, Universe) 

If that's too painful - I'd be happy to change it to "Move channel group up" or equivalent.

**Comment by mcallegari** [comment]
To be honest, as a user I would think this:
- I click on something
- I see a disabled button and I think "why is it disabled"?
- then I go and read the documentation and find an answer (which IS a clear answer)
- end of the story

So you guys are mounting a case on a tooltip?
If this is what annoys users the most, then let's change the tooltips but to be honest my priorities for this project are others.
