### ISSUE TITLE
Contextual Speed Menu functions for Fixture Groups disabled

### ISSUE THREAD

**Issue by schofiel** [mcallegari/qlcplus#1598]
**Describe the bug**
With a Fixture Group selected, the right-click Speed Menu shows disabled Fixtures Group functions.

**To Reproduce**
1. Start QLC+ with a project (QXW file) containing a collection of fixtures
2. Select Fixtures page using main functions toolbar (bottom left)
3. Verify the project's fixtures, groups, and Universe(s) are displayed in the Fixture group pane of the main window (left side)
4. Click on a defined fixture group to select the group
5. Right-click on selected fixture group. Verify speed menu displays over the group.
6. Verify "Add Fixture to group" and "Remove Fixture from group" menu selections are greyed out and disabled.

**Expected behavior**
Problem: "Add Fixture to group" and "Remove Fixture from group" menu selections should be *enabled* as a context feature for the selected group (currently disabled)

**Screenshots**
![QLCPlus Speed Menu problem](https://github.com/mcallegari/qlcplus/assets/1452433/5f2b4fd6-6f54-4980-b97b-e98cfc8e6467)

**Desktop (please complete the following information):**
 - OS: Windows, Linux Mint, Ubuntu.
 - QLC+ Version: all versions to date, currently on 4.13.1
 - hardware setup (mandatory for audio/video issues): N/A - not a hardware problem

**Additional context**
N/A

**Comment by mcallegari** [comment]
Not a bug.
You're clicking a **group**, not a fixture. Therefore add **fixture** to group is not enabled.
Please consider reading some documentation and experiment with the software before opening issues here.
Otherwise please use the forums like everybody else. Someone will explain these mechanisms to you.
Thank you.
