### ISSUE TITLE
background images in virtual console (web) not working

### ISSUE THREAD

**Issue by caspermudde** [mcallegari/qlcplus#1601]
**Describe the bug**
I made a virtual console which includes some buttons with background images (png). Locally it all looks good but when i approach the console via the web interface the images dont show up. 

**Expected behavior**
Show the background images both local as via the web virtual console. 

**Screenshots**
PC:
![PC](https://github.com/user-attachments/assets/739d85ab-8492-4f91-bc7f-47a8a5148e3c)
Phone:
![smartphone](https://github.com/user-attachments/assets/523e8a24-42ec-4c6a-a48e-295c78a85a08)

**Desktop (please complete the following information):**
 - OS: Win11 + Android 14 (Chrome)
 - QLC+ Version 4.13.1

**Additional context**
Feature should be available, see commit:
https://github.com/mcallegari/qlcplus/commit/a97abd449f3e3a9d22973640f394743323108740

**Comment by mcallegari** [comment]
Hi, preliminary questions:
- what type are the pictures? png? jpg?
- can you share an example of path of a picture written in your project? Might be a Windows-specific issue

**Comment by yestalgia** [comment]
If you post your show file and images I can investigate.

**Comment by mcallegari** [comment]
I confirm this is a Windows-specific issue
