### ISSUE TITLE
External control of audio widget not working correctly

### ISSUE THREAD

**Issue by trendmonkey** [mcallegari/qlcplus#1602]
MacOS Ventura
QLC 4.13.1

When enabling and disabling the audio widget using external control, in this case by a loopback controlled by a button widget it does not work correctly.

If I use a toggle button to set the loopback, the first click enables the widget succesfully however when clicking the button again it does not disable the widget and requires an extra click to disable.
This results in the status of the button and the widget being out of sync.
The workaround is to use a flash button but then it is not possible to see the status of the audio widget on the button.
This is an issue if audio widgets are hidden in other frames.

**Comment by mcallegari** [comment]
See "Generate an extra Press/Release when toggled" here:
https://docs.qlcplus.org/v4/input-output/input-profiles

You probably need that in your custom input profile.
Please use the forums for such questions. Thank you

**Comment by trendmonkey** [comment]
This occurs when using a loopback and virtual console button, not using external hardware.
