### ISSUE TITLE
Fixture Fun-Generation-LED-Pot-12x1W-QCL-RGB-WW.qxf

### ISSUE THREAD

**Issue by luziuskloeti** [mcallegari/qlcplus#1605]
<Manufacturer>Fun Generation</Manufacturer>
should be changed to
<Manufacturer>Fun-Generation</Manufacturer>
otherwise errors may occur in the software.

**Comment by yestalgia** [comment]
Hey, thanks for the report,

I didn't run into any issues patching, editing or playing back a show using Fun-Generation fixtures. 
![image](https://github.com/user-attachments/assets/922a585c-9a56-4a81-b2bf-679b097b7a4e)
Notice that the fixtures are already listed as Fun-Generation in the software.

Can you please give me some additional steps to reproduce the errors you're seeing?

**Comment by mcallegari** [comment]
Fixed, thanks for spotting
