### ISSUE TITLE
crash after overly large or strange RGBW panel

### ISSUE THREAD

**Issue by swifty99** [mcallegari/qlcplus#1625]
**Describe the bug**
Create a panel as seen below.

**To Reproduce**
Set like this, and you are one click away("OK") away from crash
<img width="489" alt="Bildschirmfoto 2024-10-08 um 21 12 46" src="https://github.com/user-attachments/assets/37b71427-cc2a-49ae-b3a7-e0091f92979e">

**Expected behavior**
No, crash
- prevent strip spanning more than one universe?
- automatically adjust pixels to next universe?
- have a separate tool for strips?

**Desktop (please complete the following information):**
 - OS: MacOS
 - QLC+ Version 4.13.1
- hardware setup : E1.31 interfaces only

**Additional context**
Still a noob on QLC+, however it looks very promising!

**Comment by mcallegari** [comment]
Thanks for reporting.
I limited the maximum columns for RGBW to 128.

**Comment by yestalgia** [comment]
> Thanks for reporting. I limited the maximum columns for RGBW to 128.

This is a good crash fix for now. However; IMHO, this brings to the surface a bigger issue, and I think I may have a better solution. 

Let's start with an example: we have an RGB LED tape decoder with 171 RGB LEDs starting on Universe 3. This results in the need for a fixture which spans the gap between universe 3 and universe 4. 

## Fixtures which span multiple universes
![image](https://github.com/user-attachments/assets/e2728a5e-1849-4db2-a34f-423c7761e51a)

In the example, we need the blue channel of our 171th LED to be on universe 4. I didn't make the rules, this is just how the cookie crumbles with these decoders.

This would be a hard UX problem to solve. My gut tells me that the "decapitated" fixture shown in Universe 4 above should be greyed out. 

When the user changes the address of that fixture, the "virtual" fixture is deleted and only re-added as necessary. I've got a feeling this would require a lot of rework. 

## Potential Alternative
The RGB Panel creator is able to create custom fixtures. Perhaps this case can be fixed purely for the RGB Panel and not normal fixtures. Although, there are more and more multi-universe artnet fixtures coming onto the market. 

This would require a rework of groups though, allowing multiple heads to occupy the same square.

## Why bother

QLC+ has a flawed model of the LED tape problem. It assumes that a string of LED tape can only exist on 1 universe. The [WS2811](https://www.nooelec.com/files/WS2811.pdf) standard does not specify a limit, so it's only natural that long LED tape will result in more than 1 universe of data being required.

I would need to do some real thinking about how this would change the user experience, I'm sure you have some objections @mcallegari. But this would be a worthwhile thing to fix properly.
