### ISSUE TITLE
Starting QLC+ on Mac (M2 Pro) hangs at MidiEnumeratorPrivate::MidiEnumeratorPrivate(MidiEnumerator *)

### ISSUE THREAD

**Issue by kellertobias** [mcallegari/qlcplus#1626]
**Describe the bug**
When I start QLC+, it takes ages to load and hangs at "Starte Q Light Conrtoller plus - Loopback".
I have tried the Debug Build of 2.12.8 GIT from the forum and there I get some logs in the terminal.
The last Log before it hangs is 
```
MidiEnumeratorPrivate::MidiEnumeratorPrivate(MidiEnumerator *)
```

**To Reproduce**
Every time I start the application (tested with 2.12.8, 2.13.1 and 3. something) on my Macbook Pro M2 Pro,
the startup of the application hangs. the 2.x versions show "Loopback" in the loading window.

Sometimes it finally loads after a few minutes

**Expected behavior**
The application should start within at least 1 minute, ideally would be a few seconds.

**Screenshots**
![Bildschirmfoto 2024-10-11 um 17 15 28](https://github.com/user-attachments/assets/e92d55de-908d-40e0-b6f9-94000658cbad)

**Desktop (please complete the following information):**
 - OS: Mac OS 14.6.1
 - QLC+ Version Multiple
 - Macbook Pro M2 Pro 

**Additional context**
Got a lot Midi decives connected, but currectly turned off (so should not make any problem)

**Comment by kellertobias** [comment]
Edit: Now it's open. Took me 12 Minutes to load. CPU at 0%, nothing else of relevance running

**Comment by mcallegari** [comment]
Since this is not a developer report, please report to the forums to get some help.
QLC+ versions 2.12.x don't even exist.

Your issue might be related to corrupted settings file. Please remove it and start from scratch.
Closing.

**Comment by kellertobias** [comment]
Sorry, mixed it up. its 4.12.8, 4.13.1 and 5.0.0 Beta 3.
I didn't click developer report when selecting what kind of issue it is, I selected bug report and it nowhere said anything about any forum.
