### ISSUE TITLE
Show manager zoom and scroll with mouse wheel

### ISSUE THREAD

**Issue by wiibaker** [mcallegari/qlcplus#1629]
**Describe the bug**

It is quite common way in apps to zoom and scroll using the mouse wheel. In many apps the ctrl+wheel zoom and just the wheel scrolls horizontally. This could be very hany in te Show Manager.

**To Reproduce**
1. Go to 'Show Manager'
2. Add some long audio or effect
3. Scroll wheel
4. Nothing happens
5. Use ctrl+wheel
6. Nothing  happens

**Expected behavior**
In show manager when using ctrl+wheel it would zoom in/out.
When using just the wheel, it would scroll horizontally left/right if applicable.

**Desktop (please complete the following information):**
 - OS: Windows
 - QLC+ Version: dev build (4.13.2 GIT #980) https://github.com/mcallegari/qlcplus/actions/runs/11416185392

**Comment by mcallegari** [comment]
Regular wheel scrolls vertically, not horizontally.
CTRL modifier can be handled.

**Comment by wiibaker** [comment]
Excellent!

Yes true about that vertical scroll. I guess I just had that gut feeling or some intuitive idea from some other app.

The horizontal scroll does work when hovering over the bottom scroll bar. As one would expect.

**Comment by FloEdelmann** [comment]
Image editor software like Gimp, Inkscape or Figma use Shift+Scroll for horizontal scrolling. Maybe that would make sense here as well?

**Comment by wiibaker** [comment]
> Image editor software like Gimp, Inkscape or Figma use Shift+Scroll for horizontal scrolling. Maybe that would make sense here as well?

This could actually be something what I was thinking and just forgot how it actually might behave in some other apps
