### ISSUE TITLE
Track labels should be always visible in Show Manager

### ISSUE THREAD

**Issue by wiibaker** [mcallegari/qlcplus#1630]
**Describe the bug**

In show manager if you scroll right, the track labels disappear off the screen. This makes it difficult to mute etc a track when you are further down in the show doing stuff. Also it is difficult to know which track is currently active.

**To Reproduce**
1. Go to Show Manager
2. Add a long audio or effect
3. Scroll right
4. The track labels scroll of the screen to the left

**Expected behavior**

The track labels would stay always visible

**Desktop (please complete the following information):**
OS: Windows
QLC+ Version: dev build (4.13.2 GIT #980) https://github.com/mcallegari/qlcplus/actions/runs/11416185392

**Comment by mcallegari** [comment]
This is already solved in v5 and will not be solved in v4.
