### ISSUE TITLE
OS2L integration drops commands received in a short period of time

### ISSUE THREAD

**Issue by asdfMaciej** [mcallegari/qlcplus#1633]
Hello, first of all: thanks for maintaining this project!

**Describe the bug**
QLC+ ignores OS2L commands sent in a rapid succession.

I'm currently working on a OS2L application that sends packets to QLC+ based on physical inputs, for example:

```json
{"evt": "cmd", "id": 123, "param": 211}
{"evt": "btn", "name": "somebutton", "state": "on"}
```

**If packets are sent too often, QLC+ doesn't process them**. Example scenarios:
- rapidly tapping a button to the rhytm of a high BPM song and sending `btn` events
- quickly sending multiple `cmd` values due to changing a slider value

I've looked through the OS2L integration source code and I don't see a reason why (nor a path to avoid this issue other than artificial delays), so I assume this is a bug.

My application is sending packets correctly, as I've also tested this configuration via an OS2L server. 
I've also replicated this in a more natural behaviour in VirtualDJ via rapid pad taps - they also get ignored.
Also found this related discussion, which reported the same issue: https://www.qlcplus.org/forum/viewtopic.php?t=15642

**To Reproduce**
- Set up a slider or a pad mapped to OS2L input: 
![image](https://github.com/user-attachments/assets/3bba709f-132f-4a7c-8be8-b2ddb663ef5a)
![image](https://github.com/user-attachments/assets/55521d57-db9d-422a-ab6d-887c4c2b19d9)

- Send OS2L packets in a rapid succession

If necessary, I can provide a reproduction script, but this is very easily replicated via Virtual DJ.

**Expected behavior**
All commands are processed correctly

**Desktop (please complete the following information):**
 - OS: Windows 10
 - QLC+ Version: 4.12.7
- hardware setup: Ryzen 5 4500U

**Comment by asdfMaciej** [comment]
On my machine, creating a 50 milisecond gap between os2l requests appears to mitigate this issue, 30 miliseconds and below reliably fails 

This is however an infeasible workaround when attempting to for ex. press few buttons at the same time, as it introduces visible delay

**Comment by mcallegari** [comment]
This might be the line to check
https://github.com/mcallegari/qlcplus/blob/master/plugins/os2l/os2lplugin.cpp#L211

However I need some script to reproduce the issue and make sure it is resolved with a fix

**Comment by mcallegari** [comment]
Should be fixed. Please check the latest build and report if it works as expected now
