### ISSUE TITLE
Virtual Console Solo Frame give a delay when playing Audio

### ISSUE THREAD

**Issue by ThePlanplan** [mcallegari/qlcplus#1634]
**Describe the bug**
Starting songs in a solo frame have a delay if another one was playing.

**To Reproduce**
1. Add 2 songs or more in Functions
2. Add 2 buttons in a Solo Frame in Virtual Console
3. Attach each song to theses buttons
4. Click the first button to start the song attached with no delay, but clicking the other button while the previous song is active have a small delay (and all subsequent presses while a song is active)

**Expected behavior**
No delay should be present.
The bug is not present in a normal Frame.

**Workaround**
If I add a small Fade-out time (even 1ms) to the songs, there's no delay.

**Desktop**
 - OS: Windows 11
 - QLC+ Version 4.13.1
 - Laptop speakers

**Comment by mcallegari** [comment]
Please build QLC+ with Qt 6.8.x and try and see if the delay is still there

**Comment by mcallegari** [comment]
I have loaded a test version here
https://www.qlcplus.org/downloads/test/index.php?p=Windows

Please test and report if it solves the issue, thanks

**Comment by GGGss** [comment]
Improved results.
Where v4.13.1 measured a 378ms gap (mp3 vs 368ms with flac), the responsiveness with QT6 is improved.
Playing audio in a solo frame has an improved gap measurement of 29ms for mp3 and 29ms for flac. Great!

[test-tones.zip](https://github.com/user-attachments/files/18164609/test-tones.zip)
Observation: The qt5 however, showed a 'nice' 11ms fade out, where qt6 cuts the audio stream directly.
Observation 2: (bug) double-clicking a button, renders QLC+ (both versions) in an unresponsive state and even crashes.

*test environment: A 2 mp3 files, 2 flac files - a project with 2 buttons in a solo frame. v4.13.1 and v4.13.2 GIT
