### ISSUE TITLE
Reset button of override slider doesn't produce MIDI feedback

### ISSUE THREAD

**Issue by p-rogalski** [mcallegari/qlcplus#1635]
**Describe the bug**
Sliders in "Level" mode with "Monitor the selected channels and update the slider level" checkbox enabled act similarily like simple desk sliders (they can override). One can map a physical button to reset the override:

![grafik](https://github.com/user-attachments/assets/27dbd6bc-5a19-4e07-af42-52a7cc002e46)

However, I was not able to produce MIDI feedback via "Custom Feedback". The assigned button just doesn't light up, regardless of which "Custom Feedback" options I choose.

For normal VC buttons, "Custom Feedback" works as expected, so this isn't a hardware issue.

**To Reproduce**
1. Add a slider
2. Go to slider properties and enable "level" mode
3. Tick the checkbox "Monitor the selected channels and update the slider level"
4. Assign a button to "Override reset control"
5. Set "Custom Feedback"
6. Use the slider and the reset button --> No MIDI feedback

**Expected behavior**
- If the Slider monitors a channel, I would expect to see the "Lower Channel" MIDI feedback.
- If the slider was moved, the "override reset" button turns red. I would expect to see the "Upper Channel" MIDI feedback.
- If I press the "override reset" button, the slider resets and I would expect to see the "Lower Channel" MIDI feedback again.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - QLC+ Version [e.g. 4.13.1]
- hardware setup (mandatory for audio/video issues)
  - MIDI controller: Akai APC mini mk2

**Additional context**

**Comment by yestalgia** [comment]
I am able to reproduce the behaviour described in 4.13.1 on Windows per your instructions. Though I must admit, I don't tend to use this feature that much so I don't know what the expected behaviour should be. There has been a recent change to our feedback system which might have caused this regression.

Thank you for taking the time to write up such a detailed report with supporting screenshots.
