### ISSUE TITLE
Wrong Tab order in Custom Feedback Dialog

### ISSUE THREAD

**Issue by Loewe111** [mcallegari/qlcplus#1637]
**Describe the bug**
When using Tab to navigate through the options in the Custom Feedback Dialog, the order seems wrong, as seen in the image. The Monitor Value comes before the Lower Value, and the Ok/Cancel Buttons come before the midi options.

![current](https://github.com/user-attachments/assets/20734aaf-fd95-4423-ba84-bea09ced78a8)

**To Reproduce**
1. Open a Custom Feedback Dialog
2. Use Tab to navigate the options
3. See error

**Expected behavior**
I would expect the Monitor Value to be 3rd and the Midi options to come before Ok/Cancel, like this:
![expected](https://github.com/user-attachments/assets/749e57ef-c3da-4546-8563-ef903bdd9c4f)

**Desktop:**
 - OS: Windows 11
 - QLC+ Version: 4.13.1
 - APC Mini Mk2

**Comment by yestalgia** [comment]
Good pickup thanks
