### ISSUE TITLE
[Feature Request] Priorities for Virtual Console elements

### ISSUE THREAD

**Issue by PROPHESSOR** [mcallegari/qlcplus#1638]
### Description
I would like to request a feature that allows setting priorities for Virtual Console elements (such as buttons, sliders, etc.). The idea is to have a mechanism for controlling which elements take precedence over others when multiple are active, making it easier to manage complex lighting scenarios with overlapping controls.

### Use Case Examples

1. **Color Control vs. Strobe Effect**
   - We have a set of buttons that control the color of PAR lights.
   - There is also a button that runs a strobe effect on a specific color.
   - **Goal:** When the strobe button is active, its effect should override the color set by the PAR buttons. However, when the strobe button is deactivated, the PAR buttons should continue to control the color without interruption.
   - **Solution with Priority:** Assign a higher priority to the strobe button. When active, it overrides the PAR buttons' color settings. When inactive, the control seamlessly returns to the PAR buttons.

2. **RGB Slider and Color Preset Buttons**
   - We have several buttons for predefined color presets and an RGB picker slider to adjust custom colors.
   - On some days, the RGB slider should set the base color, while the preset buttons temporarily override the color for special effects.
   - On other days, the RGB slider should take full control and override any button presses, making the RGB picker the dominant control.
   - **Solution with Priority:** Allow setting priorities dynamically so that either the RGB slider or the preset buttons can take precedence depending on the scenario.

### Why This Feature is Important
Adding a priority system to the Virtual Console would:
- Simplify the creation of complex lighting setups by allowing clear, hierarchical control over elements.
- Reduce the need for complicated workarounds and scripting, making QLC+ more user-friendly.
- Enhance the flexibility of lighting design, enabling smoother transitions and more intuitive overrides for live performances.

### Possible Implementation
A priority system could be added as an additional parameter in the properties of each Virtual Console element. For instance:
- A default priority level for all elements (e.g., 0).
- Users can increase or decrease priority levels to determine which elements have precedence.
- The system would evaluate active elements based on their priority level, with higher priority elements overriding lower ones.

**Comment by mcallegari** [comment]
This is not quite the right place to discuss such big change.
Please submit your idea in the [dedicated forum area](https://www.qlcplus.org/forum/viewforum.php?f=18) and let's discuss there where many more can participate.
Thank you
