### ISSUE TITLE
[Feature Request] Ctrl+Z to undo Virtual Console adjustments

### ISSUE THREAD

**Issue by PROPHESSOR** [mcallegari/qlcplus#1639]
### Description
I would like to request an "Undo" function (Ctrl+Z) for the Virtual Console in QLC+. Currently, if an element (e.g., a button, slider, or widget) is accidentally moved or resized in the Virtual Console, there's no way to undo this action, which can lead to time-consuming adjustments to restore the original layout.

### Problem
Accidental changes to the Virtual Console layout, such as:
- Moving a control element to a different position.
- Resizing elements unintentionally.
- Shifting groups of controls out of alignment.
- Adding or deleting elements.

These changes can disrupt the console's layout and require manual corrections, which can be both time-consuming and prone to further mistakes.

### Proposed Solution
Implement an Undo function for Virtual Console that:
- Supports multiple levels of undo (not just a single step).
- Uses a common shortcut (Ctrl+Z) to undo the most recent changes.
- Tracks movements, resizes, and other layout adjustments of Virtual Console elements.
- Optionally, a Redo function (Ctrl+Y or Ctrl+Shift+Z) to reapply undone changes.
- Qt framework has [Undo framework](https://doc.qt.io/qt-6/qtwidgets-tools-undoframework-example.html#:~:text=In%20the%20Qt%20undo%20framework,is%20placed%20on%20a%20QUndoStack.) to implement this

### Why This Feature is Important
- **Saves Time:** It will significantly reduce the time needed to fix accidental changes, allowing for a more efficient workflow.
- **Increases Accuracy:** A simple Undo function would prevent mistakes from snowballing into larger layout problems.
- **User-Friendliness:** This feature is standard in most editing software, making QLC+ more intuitive for new users and lighting professionals alike.

Implementing an Undo function would make the Virtual Console much more robust and reliable for complex projects, minimizing frustration from accidental changes and improving overall usability.

**Comment by mcallegari** [comment]
Undo is already implemented in v5 and will not be implemented in v4.
Closing
