### ISSUE TITLE
VC speed dial title color not adjustable on Windows

### ISSUE THREAD

**Issue by p-rogalski** [mcallegari/qlcplus#1640]
**Describe the bug**
The title text color of the VC speed dial is not adjustable. It's always black.

**To Reproduce**
1. Add a "speed dial" control to VC
2. Change VC background color to black and speed dial text color to white
3. Title stays black

**Expected behavior**
VC speed dial title should have white color.

**Screenshots**
![grafik](https://github.com/user-attachments/assets/ce24fcef-b97b-4751-801e-95a23a89c224)
![grafik](https://github.com/user-attachments/assets/2a8e627c-3529-49b1-95c9-065e532ed431)

**Desktop (please complete the following information):**
 - OS: Windows
 - QLC+ Version 4.13.1
- hardware setup (mandatory for audio/video issues)

**Additional context**

**Comment by p-rogalski** [comment]
Unfortunately, the widget got worse. Please see the following comparision:

| | Old | New | Problem |
| --- | --- | --- | --- |
| Default Layout | ![grafik](https://github.com/user-attachments/assets/d20cb821-0cf7-46e9-aa8a-dd116866a245) | ![grafik](https://github.com/user-attachments/assets/d587987b-0a74-4a4a-9fbc-b3090d2f4349) | - |
| Buttons and Dial hidden | ![grafik](https://github.com/user-attachments/assets/a20c6e42-58c6-46a4-89e0-a85619fcef4c) | ![grafik](https://github.com/user-attachments/assets/d9a316d2-0e01-4e7f-a9aa-dd3a627b5426) | Title not visible at all |
| Black Background + White Text + Division/multiplication buttons | ![grafik](https://github.com/user-attachments/assets/46d3aeca-ef4e-4985-9faa-0f771c07cce6) | ![grafik](https://github.com/user-attachments/assets/51f72909-5f40-4791-88de-13cb621cb9ce) | Division/multiplication factor text color doesn't change |

**Comment by mcallegari** [comment]
Margins and text fixed.
Second case just use a separate label widget.
Please test the latest build

**Comment by p-rogalski** [comment]
LGTM, thank you!
