### ISSUE TITLE
Local Simple Desk is not updated when channels are reset via the Web API

### ISSUE THREAD

**Issue by jpue** [mcallegari/qlcplus#1647]
**Describe the bug**
In the Simple Desk view in QLC+, the faders of channels that are reset via the Web API/Web DMX Keypad only show the change locally after the view has been changed.

**To Reproduce**
1. Start QLC+ with `-w` to enable web access.
2. Switch to the `Simple Desk` page.
3. Open `http://127.0.0.1:9999/keypad.html` in a web browser.
4. Enter `1A100` there and press Enter. Click on `1` and then on `Reset Channel`.
5. The fader in the QLC+ window is not reset to inactive/grey, only the channel value is set to `0`.
The change only becomes visible if you switch to another page or click on the view mode button (folder icon).

**Expected behavior**
Changes made via the Web API should be visible without any interaction with the user interface.

**Desktop:**
- OS: Windows 10 / Ubuntu 22.04
- QLC+ 4.13.1 (latest official release) / QLC+ 4.13.2 GIT (on December 28, 2024)

**Comment by mcallegari** [comment]
Fixed, thanks for reporting
