### ISSUE TITLE
Wrong tab order in Fixture Monitor

### ISSUE THREAD

**Issue by jpue** [mcallegari/qlcplus#1648]
**Describe the bug**
Similar to #1637, when using the tab key to navigate through the options in the properties editor of the `Fixture Monitor`, the tab order is wrong: `Vertical` -> `Horizontal` -> `Rotation` -> `Gel color` -> `Gel color reset`.

**To Reproduce**
1. Start QLC+ and add some fixture(s), for example one `Generic Dimmer`.
2. Open the `Fixture Monitor` and switch to `2D View`.
3. Add the fixture and click on it to open the properties editor.
3. Use Tab to navigate the options.

**Expected behavior**
I suggest the following tab order: `Horizontal` -> `Vertical` -> `Rotation` -> `Gel color` -> `Gel color reset`.
A patch to fix this in the same way as #1637 is attached: [fixture_monitor_fix_tab_order.patch](https://github.com/user-attachments/files/18266886/fixture_monitor_fix_tab_order.patch).

**Desktop:**
- OS: Windows 10 / Ubuntu 22.04
- QLC+ 4.13.1 (latest official release) / QLC+ 4.13.2 GIT (on December 28, 2024)

**Comment by mcallegari** [comment]
Fixed, thanks for reporting
