### ISSUE TITLE
Local Simple Desk is not updated when changes are made via the Web API

### ISSUE THREAD

**Issue by jpue** [mcallegari/qlcplus#1650]
**Describe the bug**
If the "grouped view" is enabled on the local Simple Desk page, changes made via the Web API are not displayed.

**To Reproduce**
1. Start QLC+ with `-w` to enable web access.
2. Add some fixture(s), for example a `Generic Dimmer`.
3. Switch to the `Simple Desk` page.
4. Click on the folder icon to activate the grouping of channels.
5. Open the `Fixture Monitor`.
6. Open `http://127.0.0.1:9999/simpleDesk` in a web browser and modify the value of a channel which is mapped to a fixture.
7. The fader in the QLC+ window does not change, only the value of the channel in the `Fixture Monitor`.
   The local `Simple Desk` only shows the change if you switch the view mode (folder icon) again.

**Expected behavior**
Regardless of the selected view in the QLC+ window, the changes made via the Web API should be visible without any UI interaction.

**Desktop:**
- OS: Windows 10 / Ubuntu 22.04
- QLC+ 4.13.1 (latest official release) / QLC+ 4.13.2 GIT (on December 29, 2024; with patches for #1647 applied)

**Comment by mcallegari** [comment]
I've seen this. Won't fix this one sorry.
You can hire someone to submit a patch for this is it is vital for your workflow.

**Comment by jpue** [comment]
Please excuse my rudeness, it wasn't my intention to annoy you.

Of course, you are not responsible for fixing the problems that occur in my QLC+ workflow.
I agree with you that this is not the most important bug, but I don't think a patch would hurt either.

That's why I fixed it now myself. So if you are willing to accept a patch to fix this known issue, you can find it at #1652.
Otherwise, please close this again.

**Comment by mcallegari** [comment]
Fixed by b14855e6507aeb5e1b08b5af7a132b53cb818c0c
