### ISSUE TITLE
 function manager for chasers stops a running cuelist 

### ISSUE THREAD

**Issue by offtools** [mcallegari/qlcplus#226]
If you have a cuelist running and need  to change something  in your chaser (up and downfade times ...) the cuelist stops and produces a blackout.

This is not a real bug but can have nasty side effects if you need to change something or just hit a chaser entry instead of a scene entry by accident, in my case I actual produced a blackout (ups), luckily not in the show just in a run. 

regards offtools

**Comment by plugz** [comment]
Unable to reproduce the issue (QLC+ 4.10.2 GIT)
