### ISSUE TITLE
Undo functionality (CTRL-Z)

### ISSUE THREAD

**Issue by lcslouis** [mcallegari/qlcplus#28]
There is no undo support available in the program.

If I press Ctrl-Z nothing happens. What is supposed to happen is an undo action.

I know mac is a different command and ubuntu should be Ctrl-Z but undo is a feature that is needed during design mode.

**Comment by lcslouis** [comment]
This has been on here for 2 years any idea when this will be added?

**Comment by mcallegari** [comment]
We are waiting for you to implement it :wink:

**Comment by forresthopkinsa** [comment]
http://stackoverflow.com/questions/3541383/undo-redo-implementation

It seems to me that we should use the save state method, because many operations in QLC wouldn't be easily reversible.

**Comment by mcallegari** [comment]
@forresthopkinsa "we should" ?? And what would be your part in developing such functionality ?
Director ? Manager ? Grand jury ?

This is the most invasive feature that QLC+ will ever see, and a StackOverflow link won't surely implement it.
Sooner or later it will be implemented. Most likely QLC+ 5 only. No ETA at all.

**Comment by forresthopkinsa** [comment]
Yeah, I include myself when I say "we".

Once I have some free time on my hands (I'm already spending all my time operating the other half of QLC+) then I want to contribute to this project. I just wanted to test the waters, don't get upset.

**Comment by mcallegari** [comment]
Implemented in QLC+ 5.0.0 Alpha1
