### ISSUE TITLE
Fixture definitions loaded at startup only

### ISSUE THREAD

**Issue by markusb** [mcallegari/qlcplus#425]
It looks to me like all fixture definitions are loaded at startup only. This has the effect that for each fixture change you have to restart qlcplus completely.

Qlcplus should, when adding a fixture, re-load the fixture definition from the file, to get the latest changes to the fixture. You would still have to restart qlcplus if you add a new fixture tape, but this is less frequent.

An alternative solution would be to add a 'Refresh' button to the 'Add fixture' dialog, triggering a re-read of the fixture definitions. This would have the advantage that this would also cover the addition of new fixtures. If the reload is short enough, this refresh could even be automatic. But this may be problematic on slow computers.

One more thing: It would be useful to have a 'refresh' button in the fixture properties dialog who would reload the fixture properties from the fixture definition file. So you could make changes in the fixture and propagate them to a workspace without deleting and re-adding the fixture.

**Comment by mcallegari** [comment]
"one change could make sense: Move the scan for the user fixtures to be done when 'Add fixture' dialog is started"
This doesn't make sense at all actually.
Fixtures are loaded when they are needed. Most of the times they are needed when loading an existing project, not just when adding new fixtures.

Again, you cannot change fixtures while QLC+ is running, nor expect QLC+ to reload them at runtime.
I am not going to implement this request.
Gonna close this ticket in a couple of days if no one else has thoughts of implementing this without breaking the whole QLC+ fixture logic.

**Comment by markusb** [comment]
I can live with that. Thanks.
