### ISSUE TITLE
Submaster level ignored when launching a 

### ISSUE THREAD

**Issue by zfasel** [mcallegari/qlcplus#434]
Version: 4.8.3 and a Fresh compile from git
Issue: 

Using a combination of RGB lights that do and that do not have a separate intensity channel. When in the virtual console using a button associated with a scene within a tab with a submaster, launching the scene acknowledges the submaster level of the tab and the submaster of parents as set at the time of launch perfectly fine. 

However, when launching a Chase or sequence, the chase/sequence is at full intensity (on both RGBs and general intensity channel) at the time of launch, ignoring the submaster settings. The submaster settings are applied however upon a value change of the submasters.

**Comment by vjarvens** [comment]
Same bug reproduced QLC+ 4.8.5 on mac 10.9.5 using generic dimmers with submaster-fader in same frame. eg. current submaster value is ignored when launching new chaser.

**Comment by plugz** [comment]
Thanks,

fixed by https://github.com/mcallegari/qlcplus/commit/e392aae345bca9e52b5e9b0300ebaf5f76e52192
