### ISSUE TITLE
Build issue on openSUSE tumbleweed: nanodmx.cpp

### ISSUE THREAD

**Issue by nettings** [mcallegari/qlcplus#435]
Hi Massimo, hi everybody,

I'm trying to re-sync to the latest qlcplus git after updating my laptop, and I've been running into a number of build issues.
System is openSUSE tumbleweed of 2015-01-15, i.e. pretty recent.

g++ -c -pipe -Werror -Wno-unused-local-typedefs -g -Wall -W -D_REENTRANT -fPIC -DQT_WEBKIT -DLIBFTDI1 -DQT_PLUGIN -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/default -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I../../interfaces -I../../midi/common -I/usr/include/libftdi1 -I/usr/include/libusb-1.0 -I. -o nanodmx.o nanodmx.cpp
nanodmx.cpp: In member function ‘QString NanoDMX::getDeviceName()’:
nanodmx.cpp:84:52: error: invalid use of incomplete type ‘libusb_device {aka struct libusb_device}’
         if (dir.startsWith(QString::number(m_device->bus->location)) &&
                                                    ^
In file included from qlcftdi.h:36:0,
                 from dmxusbwidget.h:24,
                 from nanodmx.h:25,
                 from nanodmx.cpp:20:
/usr/include/libftdi1/ftdi.h:345:12: error: forward declaration of ‘libusb_device {aka struct libusb_device}’
     struct libusb_device *dev;
            ^
Makefile:312: recipe for target 'nanodmx.o' failed

I'm not using a nanodmx, so I'm currently working around the issue by commenting out the corresponding lines in the Makefile.

Best,

Jörn

**Comment by kripton** [comment]
Hello, thanks for the report. There are two API-incompatible version of libFTDI currently out there. You're using the 1.0-branch of libFTDI. I once fixed it for the plugins that existed at that time (#287) but was unable to fix build for the plugins introduced afterwards (tried several times though).

**Comment by nettings** [comment]
kripton, thanks for the feedback. I'm confused, though. This is what I have installed (from openSUSE tumbleweed repository):
i | libftdi1       | package | 1.2-1.1 | x86_64 | repo-oss  name: libftdi1
i | libftdi1-devel | package | 1.2-1.1 | x86_64 | repo-oss   name: libftdi1-devel
And according to http://www.intra2net.com/en/developer/libftdi/, this is indeed the most recent API version. Or has it been forked somewhere else and a slightly incompatible 2.0 version been released?

**Comment by janosvitok** [comment]
nettings, you are using 1.0 version of libftdi. QLC+ was written using 0.x version. As I understand it,  what you see are differences between 0.x and 1.x version.

**Comment by mcallegari** [comment]
This is related to libusb and not libftdi. Support for libftdi 1.x is there since a while now.
It seems nanodmx.h cannot resolve the libusb include, even though it finally includes qlcftdi.h.

Check if libusb-devel package is in the system (it's written in the build instructions)
Or try to add this to nanodmx.h includes:

#if defined(LIBFTDI1)
  #include <unistd.h>
  #include <libusb.h>
#endif

**Comment by nettings** [comment]
Massimo, thanks for your help. The libusb-devel package is installed, and in fact also a libusb.h header in /usr/include/libusb-1.0/libusb.h. But even your suggested addition does not fix the issue. I re-installed both libusb and libftdi1 including devel packages, and even tried a custom-built libftdi1, but they all show the same error message.

**Comment by mcallegari** [comment]
OK, then try this. Add 'struct' where libusb_device is used.
So from 
libusb_device ...
to
struct libusb_device ...

These are the places:
https://github.com/mcallegari/qlcplus/blob/master/plugins/dmxusb/src/nanodmx.h#L71
https://github.com/mcallegari/qlcplus/blob/master/plugins/dmxusb/src/nanodmx.cpp#L31
https://github.com/mcallegari/qlcplus/blob/master/plugins/dmxusb/src/qlcftdi-libftdi.cpp#L116
https://github.com/mcallegari/qlcplus/blob/master/plugins/dmxusb/src/qlcftdi-libftdi.cpp#L117

**Comment by nettings** [comment]
Tried that already, but it doesn't seem to be the root cause. Here's the compiler output with all types marked as struct:
nettings@hoppetosse:/local/build/qlcplus/plugins/dmxusb/src> make
g++ -c -pipe -Werror -Wno-unused-local-typedefs -g -Wall -W -D_REENTRANT -fPIC -DQT_WEBKIT -DLIBFTDI1 -DQT_PLUGIN -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/default -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I../../interfaces -I../../midi/common -I/usr/include/libftdi1 -I/usr/include/libusb-1.0 -I. -o nanodmx.o nanodmx.cpp
nanodmx.cpp: In member function ‘QString NanoDMX::getDeviceName()’:
nanodmx.cpp:84:52: error: invalid use of incomplete type ‘struct libusb_device’
         if (dir.startsWith(QString::number(m_device->bus->location)) &&
                                                    ^
In file included from qlcftdi.h:36:0,
                 from dmxusbwidget.h:24,
                 from nanodmx.h:25,
                 from nanodmx.cpp:20:
/usr/include/libftdi1/ftdi.h:345:12: error: forward declaration of ‘struct libusb_device’
     struct libusb_device *dev;
            ^
Makefile:312: recipe for target 'nanodmx.o' failed
make: *** [nanodmx.o] Error 1

**Comment by mcallegari** [comment]
I've got another idea.
It seems that in qlcftdi.h, libusb.h is included **after** ftdi.h

Try to build again by moving these lines
` #if defined(LIBFTDI1)`
`  #include <unistd.h>`
`  #include <libusb.h>`
`#endif`

at the beginning of the file (after `#include <QMap>`)

**Comment by nettings** [comment]
g++ -c -pipe -Werror -Wno-unused-local-typedefs -g -Wall -W -D_REENTRANT -fPIC -DQT_WEBKIT -DLIBFTDI1 -DQT_PLUGIN -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/default -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I../../interfaces -I../../midi/common -I/usr/include/libftdi1 -I/usr/include/libusb-1.0 -I. -o nanodmx.o nanodmx.cpp
nanodmx.cpp: In member function ‘QString NanoDMX::getDeviceName()’:
nanodmx.cpp:84:52: error: invalid use of incomplete type ‘libusb_device {aka struct libusb_device}’
         if (dir.startsWith(QString::number(m_device->bus->location)) &&
                                                    ^
In file included from qlcftdi.h:32:0,
                 from dmxusbwidget.h:24,
                 from nanodmx.h:25,
                 from nanodmx.cpp:20:
/usr/include/libusb-1.0/libusb.h:901:8: error: forward declaration of ‘libusb_device {aka struct libusb_device}’
 struct libusb_device;
        ^
Makefile:312: recipe for target 'nanodmx.o' failed
make[3]: *** [nanodmx.o] Error 1
make[3]: Leaving directory '/local/build/qlcplus/plugins/dmxusb/src'
Makefile:39: recipe for target 'sub-src-make_default-ordered' failed
make[2]: *** [sub-src-make_default-ordered] Error 2
make[2]: Leaving directory '/local/build/qlcplus/plugins/dmxusb'
Makefile:52: recipe for target 'sub-dmxusb-make_default' failed
make[1]: *** [sub-dmxusb-make_default] Error 2
make[1]: Leaving directory '/local/build/qlcplus/plugins'
Makefile:335: recipe for target 'sub-plugins-make_default-ordered' failed
make: *** [sub-plugins-make_default-ordered] Error 2


same old problem. I looked at /usr/include/libusb-1.0/libusb.h:901:8, and this is what I find:
/* libusb */

struct libusb_context;
struct libusb_device; 
        ^---- this is a forward declaration, no? so where is the actual declaration? is that what we have to include?
struct libusb_device_handle;
struct libusb_hotplug_callback;

**Comment by mcallegari** [comment]
Well, a little down below (around line 962 of libusb.h) there's also:
`typedef struct libusb_device libusb_device;`

Maybe we need to add it somewhere before including libusb.h....just guessing though

**Comment by axelvvd** [comment]
Hello everyone, I have the same issue on Fedora 21 with qlcplus-4.8.3

In nanodmx.cpp:84 replace m_device->bus->locator by  libusb_get_port_number(m_device)

In qlcftdi-libftdi.cpp:152 add
struct libusb_device_descriptor dev_descriptor;
libusb_get_device_descriptor(dev, &dev_descriptor);

then replace dev->descriptor by dev_descriptor

I'm working on it and I'll try to send you a patch with "#ifdef LIBFTDI1"  tomorrow.
I hope it is the good values cause I can't test now with real device

**Comment by axelvvd** [comment]
I sent my patch with the Pull Request #443 

I hope it's good :)

**Comment by mcallegari** [comment]
Thanks Axel. I've got the nanoDMX but not a system with FTDI1, so unfortunately I cannot test the patch.
If anyone reading this thread has both, please report feedbacks, thanks.
I'll merge the patch anyway cause at least it allows QLC+ to build on those systems.

**Comment by kripton** [comment]
Thanks for the patch Alex. While I don't have a nanoDMX (I usually connect my anyma uDMX clone but have access to ENTTEC USB DMX Pro) but libFTDI1 here, I cannot currently test you patch:
```
webaccess.cpp: In member function 'mg_result WebAccess::beginRequestHandler(mg_connection*)':
webaccess.cpp:262:48: error: 'WEBFILESDIR' was not declared in this scope
       if (sendFile(conn, QString("%1%2%3").arg(WEBFILESDIR).arg(QDir::separator()).arg(clUri), "text/css") == true)
```

**Comment by axelvvd** [comment]
Are you sure your build error is linked to the libftdi1 ?

**Comment by kripton** [comment]
No, my one's not but it makes testing the actual patch harder

**Comment by janosvitok** [comment]
Kripton, this is usually case for make distclean && qmake && make...

**Comment by kripton** [comment]
Yep, this seems to have been my fault. Patch looks good to me, thanks again! (Compiled fine and FTDI-based RS-485 started to send data. Content of sent data not verified due to the lack of fixtures)

**Comment by mcallegari** [comment]
OK guys, gonna close this.
If you still find problems, I'll reopen

Thanks to everyone for feedbacks and tests
