### ISSUE TITLE
Can only use ArtNet-Input if first universes are set to ArtNet-Input

### ISSUE THREAD

**Issue by prauscher** [mcallegari/qlcplus#437]
Hey,

when I configure only universe 2 to use ArtNet for Input, ARTDMX-Packets get received (packet counter increases), but the universe will not get into "managed" mode (no joystick appears in overview). Also no sliders get set.
When I configure universe 1 to use ArtNet for input too, Universe 2 gets "managed" and sliders get updated.
I think the issue is in line 205 of artnetcontroller.cpp (https://github.com/mcallegari/qlcplus/blob/master/plugins/artnet/artnetcontroller.cpp#L205), as the reference counter has nothing to do with _which_ universe is in Input-mode. I would either remove line 205 & 206 or add a list which universes are currently managed.

Thank you,
prauscher

**Comment by prauscher** [comment]
Update: Same issue when Universe 1 is in Output-Mode too for ArtDmx. But I don't know why in this case.

**Comment by mcallegari** [comment]
Hi, sorry for the huge delay.

You're absolutely right, the ref count is not the universe number.
However, removing those 2 lines, leads to another issue at line 212, cause m_dmxValues is built upon m_inputRefCount.

I need to think carefully how to find an efficient solution for this

**Comment by mcallegari** [comment]
Should be fixed with this: 84eb380acbe8588b761a8c564dcbacf652d76855

Gonna close this issue. If it's still not OK, I'll reopen it.
