### ISSUE TITLE
Scenes do not get previewed without tab view

### ISSUE THREAD

**Issue by prauscher** [mcallegari/qlcplus#438]
In Design-Mode selected Scene does not get shown on output when tab view is disabled (all fixtures are shown in one tab), regardless of blind toggle.
Try selecting a Scene and disable tab view, then select another scene and reselect the first scene. The changed lines will only be visible on output after you re-enable tab view.

**Comment by mcallegari** [comment]
@plugz  David, is this fixed ?

**Comment by plugz** [comment]
Yes it is,

cf https://github.com/mcallegari/qlcplus/commit/cf853faae63ebabf61eccf6e66c10dfa70cf36cf

**Comment by mcallegari** [comment]
Great, closing
