### ISSUE TITLE
Allow more than 16 pages in a Frame

### ISSUE THREAD

**Issue by Moehritz** [mcallegari/qlcplus#444]
By modifying the save-file you can get more than 16 pages, but it resets when editing it. Is there a good reason for this limit?

**Comment by janosvitok** [comment]
It was discussed some time ago: https://sourceforge.net/p/qlcplus/discussion/general/thread/883d0a80/
but the change was not committed yet. Please let's continue with the discussion there.

**Comment by mcallegari** [comment]
Increased to 100.
Closing this
