### ISSUE TITLE
Linux video playback issues

### ISSUE THREAD

**Issue by offtools** [mcallegari/qlcplus#446]
playing videos under linux causing several problems.

Stopping Videos Functions:
when a stopped video function is started again, the video does not start at the beginning but at the position where the playback was stopped.

Playback with vdpau:
With vdpau enabled, qlcplus freezes sometimes completly. Sometimes only audio is played and the screen stays black. Sometimes qlcplus crashed or freezes in the middle of the playback.

Playback without vdpau:
Sometimes only audio works, the video screen stays black or froozen.

**Comment by mcallegari** [comment]
Hi, I think at some point I noticed the "resume" unwanted feature as well. I'll check it again. Thanks for reminding me.

In general, though, QLC+ is using some very high level API of the Qt Multimedia library.
Basically what I do is: play a video with this URL, stop a video.
Not much more.

So I'm afraid any playback issue is most likely into the Qt framework.
I've started a thread in the Qt development ML a while ago, but they didn't seem so much interested in improving a super buggy component of Qt. See here: http://lists.qt-project.org/pipermail/development/2014-November/019035.html
In the last two months they only worked on the camera input support !

Now, to complete the issue report:
- which Qt version are you using ?
- which type of videos are you testing ?
- since Qt Multimedia is based on a GStreamer backend, are those videos working well with a GST based player (I think totem is one of them) ?

**Comment by offtools** [comment]
Hi, 

thanks for the information about Qt multimedia, although the news are not so good.

Here are the infos concerning my system:

System / Distro:
Archlinux - Linux Kernel 3.18.6-1-ARCH #1 SMP PREEMPT  x86_64 GNU/Linux

Graphic:
X.Org version: 1.16.4
Driver:  NVIDIA 346.35

QT-Version:
Qt 5.4.0 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 4.9.2 20141224 (prerelease)) on "xcb"  

Video Playback was tested with MP4 (h264, mp3) and MPEG2 files

The videos are working with gstreamer. I tried totem and gst-launch with playbin.
GStreamer version 1.4.5

**Comment by mcallegari** [comment]
OK, got it. Thanks for the info.
For a moment I hoped you were using some old Qt version (5.2.x was buggy as hell)

Qt5 on Linux is still using GStreamer 0.1x. They have GST 1.x support upstream but by default they don't compile it yet.
I think somewhere I have the command line instructions to play a video on GST 0.1x.
If I find them I'll post here.

I need to find the time to process some pending feedbacks, including yours

**Comment by offtools** [comment]
Hi,

Thanks about the information concerning gst versions. If I find the time I will run some tests with gst-0.1. Maybe somethings come out on this. The main thing seems not to be the playback or decoding side, than displaying the images. I dont know if QT is using gstreamer modules for displaying the images like (xvimagesink, ...) or using their own backends. Anyway the most problematic thing was using vdpau, could be, that vdpau was buggy in the gst-0.1x tree. But I'm just guessing here.

offtools

**Comment by offtools** [comment]
Hello Massimo,

I did some testing with gst-launch-0.10 and Videoplayback in qlcplus:
Pipeline:
gst-launch-0.10 -v playbin uri=file:///[FILE] [video-sink=[xvimagesink || ... ]]

These are two observations I made:

1. output of mpeg2 videos in qlcplus is laggy, around only 1fps on my system. They can possibly also crash the qlcplus. My gst pipeline plays them smooth. (files rendered from kdenlive and with ffmpeg standalone) 

2. h264/avc videos with very high framerates (30Mbs) are also laggy. In general: files that produce frame drop warnings in the gst pipeline or sometimes hang a bit, become much more laggy in qlcplus. 
Every problem on I've produced or noticed with gst pipline gets increasing in qlcplus.

3. In general the output of working videos are a bit laggy. I downloaded Sintel with lowest resolution from the Sintel site. The opening sequence is quite good to check the playback. Gst plays it smooth. In qlcplus it looks like 18 fps.

 
offtools

**Comment by mcallegari** [comment]
Hi @offtools ,I tested a couple of Sintel clips: sintel-1024-surround.mp4 and sintel-1280-surround.mp4
I also tested a full HD MPEG2 transport stream.

No lags, no crashes. CPU stays low (7% on Sintel and 20% on MPEG2)
Consider that I am on Acer i5 laptop with a crappy Intel card. 
I suspect there is something wrong in your system, either with ffmpeg or using vdpau.

As I said, I have no control over the video decoding, so it all depends on how the system is configured.
Now, to cut the issue in a half, do you have any chance to do some tests on another Ubuntu system, maybe with a different video card ?

On my desktop PC I've got a GTX970 card, so I can do the same tests there on Ubuntu 14.04

**Comment by mcallegari** [comment]
I think I solved the linux video playback (resume) issue.
There is no explanation for it, as most of the QtMultimedia things I've encounter so far.

Now the tricky part is test the changes on Windows and OSX and cross the fingers for having broken something...

**Comment by mcallegari** [comment]
@offtools this is it 9180c14e115646fb76da422589588a1a08d5e5cd

**Comment by mcallegari** [comment]
Closing for now.
In case open a new one with a specific case
