### ISSUE TITLE
channel modifiers issue

### ISSUE THREAD

**Issue by Tolmino** [mcallegari/qlcplus#476]
I have some problem with Star-Lights-mini-Wash-Moving-Head.qxf:
appling invert channel inverter on RGB channels some machines during show do not give light.
In forum Jano and Massimo had different ideas about.....

https://sourceforge.net/p/qlcplus/discussion/general/thread/87f529f6/?limit=25#236f

Jano sayd "The modifiers are applied too soon in the code. They are applied before HTP check and before Grand Master, but they should be applied at the very end of the processing chain"
and Massimo sayd "Channel modifiers are applied before HTP check and Grand Master on purpose.
Please DO NOT change this logic in the code until this discussion explains why it is necessary."

Please, what we can do to resolve that issue?

**Comment by mcallegari** [comment]
Tolmino, the forum is frozen cause I'm migrating it somewhere else. (it's written)

Please do not post here requests for support. This is mostly a development area.
Be patient and post this on the new forum once it's public.

Thanks

**Comment by Tolmino** [comment]
you are right, excuse me, i'll use forum in the future. but Jano define it that as a bug!

**Comment by mcallegari** [comment]
Closing this then
