### ISSUE TITLE
Function Wizard Multi-head issues

### ISSUE THREAD

**Issue by lcslouis** [mcallegari/qlcplus#491]
The function wizard doesn't work well with multi-head fixtures.

It only enables the last RGB head and doesn't create the proper size Fixture group for the amount of heads.

http://www.qlcplus.org/forum/viewtopic.php?f=5&t=8560

**Comment by lcslouis** [comment]
Any idea on when this may be fixed?

**Comment by mcallegari** [comment]
Tested again.
This seems to be fixed as of today.
