### ISSUE TITLE
XY PAD Filtering

### ISSUE THREAD

**Issue by lcslouis** [mcallegari/qlcplus#492]
When Adding fixtures to XY PAD it needs to filter out heads that don't have Pan or tilt.

http://www.qlcplus.org/forum/viewtopic.php?f=5&t=8560#p37135

**Comment by plugz** [comment]
Thanks,

Fixed by https://github.com/mcallegari/qlcplus/commit/6984eb0037656c9ba88dfe1ee6d7438a2099f4c0
