### ISSUE TITLE
Speed Dial infinite broken

### ISSUE THREAD

**Issue by mcallegari** [mcallegari/qlcplus#499]
I'm afraid some recent change to the speed dials broke the infinite functionality.

To reproduce:
- create a scene
- create a chaser
- add the scene to the chaser
- open the speed dial
- click on infinite

Seems like the signal is disconnected. Haven't checked the code yet
This needs to be fixed before 4.9.0 otherwise a rain of shit will fall :smile:

**Comment by plugz** [comment]
@mcallegari Fixed. Sorry, I did not catch this.

**Comment by mcallegari** [comment]
No problem. Lucky me that I have found it in time :wink:
