### ISSUE TITLE
Tilt/Pan do weird movements in frames with multiple pages

### ISSUE THREAD

**Issue by neutrinopower** [mcallegari/qlcplus#506]
yesterday I tried to have several XY Pads for two moving heads with different fixture-settings in different pages in qlcplus 4.9.1 on archlinux.
1. The joystick control after the first page isn't relative anymore, only on the first page.
I could avoid this by using XY Pad in a child-frame with single page in every pages.
1. after switching from operate-mode to design-mode, the frame is always active/sensitive but the movements are strange and doesn't make sense until I switched the page for once.
2. maybe it is handy when a frame is always deactive when switching back to operate-mode?
3. maybe it would be nice to can change the relative/absolute and sensitive setting from joystick by adding as input to XY Pad to virtual console separately

(I have more time to describe my trials later if needed)

**Comment by mcallegari** [comment]
Outdated and pretty vague reporting.
Unless the reporter improves this with a project workspace, it can't even be taken into account.
Closing.
