### ISSUE TITLE
Switching "Tab"/"All Channels" view

### ISSUE THREAD

**Issue by Acubed** [mcallegari/qlcplus#511]
When switching between tab view/all channels view, and on a fixture, the new tab should be set to All fixtures not General.

1. Open the Functions tab
2. Select a scene with fixtures. The editor will open with the "General" tab selected.
3. Select a fixture to edit
4. Click the "Switch between tab view and all channels view" button
5. Fixture tabs are replaced with "All fixtures" tab and tab switches to the "General" tab

Expected behavior:

5. "All fixtures" tab is selected

(The extra click to switch to the "All fixtures" tab that should be default is somewhat annoying.)

Alternatively:

Remove button for "Switch between tab view and all channels view" and show "General", "All fixtures", *and* individual fixture tabs.

**Comment by mcallegari** [comment]
Fixed
