### ISSUE TITLE
Changing fixture model changes fixture address

### ISSUE THREAD

**Issue by Acubed** [mcallegari/qlcplus#512]
Actual behavior:

1. Open "Fixtures" screen that has added devices
2. Select a fixture and edit its properties. The "Change fixture properties" window opens.
3. Change the fixture's model to one that uses an equal number of channels. The address will change to the last used address plus one.

Expected behavior:

The fixture address remains the same.

**Comment by mcallegari** [comment]
Can you please tell me which fixtures/modes I should use to reproduce the issue ?
That would save me some time to debug it. Thanks

**Comment by Acubed** [comment]
Any fixture should do it. Try:

1. Open "Fixtures" screen
2. Add a "Generic RGB" fixture"
3. Select the fixture and edit its properties. The "Change fixture properties" window opens.
3. Change the fixture's model to e.g. "Generic Smoke". The address will change from 1 to 4.

**Comment by mcallegari** [comment]
Reproduced.
Actually if you manually change the address back to the original one, it doesn't turn to red, so it's allowed.

Must be a silly check in the code.
