### ISSUE TITLE
"Channels Groups" shows channels in use by unused channels

### ISSUE THREAD

**Issue by Acubed** [mcallegari/qlcplus#513]
To reproduce:

1. Create a fixture
2. Create a channel group and assign a channel from the fixture to it
3. Delete the fixture
4. "Channels groups" will still report 1 channel in use, but no checkboxes appear when the channel group is edited. When another fixture is added, the channel will again be assigned to the channel group, even if the channel is of another type altogether (e.g. the group is for intensity, but the new channel controls an effect)

Expected behavior:

Channel should be un-assigned from channel group when a fixture with channels assigned to channel groups is deleted.

**Comment by mcallegari** [comment]
Please specify which fixtures you used because I tried it and 4 is not the same for me.
When I delete a fixture, one empty channels group is listed and if I edit it, there is no fixture available.
If I then add a fixture, and edit the empty channels group, I see the new fixture, but no channels are selected.

So basically it's all working as expected here.

**Comment by Acubed** [comment]
This is Q Light Controller Plus 4.9.1 downloaded off the website.

1. Create a "Generic RGB" fixture
2. Create a channel group and assign Generic RGB channel 2. The group will list "G / New Group / 1"
3. Delete the Generic RGB fixture
4. "Channels groups" will report "New Group /1", but the G is gone, and when editing the group, no checkboxes appear.

**Comment by mcallegari** [comment]
Done and nope, step 4 for me is New Group / 0
I started from an empty project.
Unless some change from 4.9.1 has changed things, there's something missing in this issue report.
Can you build QLC+ from sources ?

**Comment by mcallegari** [comment]
3 months and no updates from who reported this.
Closing.
