### ISSUE TITLE
uDMX communication issues with Laserworld ES-100G

### ISSUE THREAD

**Issue by croxxx** [mcallegari/qlcplus#562]
When using my USB-DMX interface to control the laser no stable output can be achieved. Laser "resets" rapidly and only displays correct image sometimes.
I had this problem on Windows before and found the solution here:
http://www.illutzminator.de/udmxfirmware.html?&L=1

The cause for this behaviour seems to be a bug in some DMX devices not behaving correctly if there is no pause between 2 frames.
I tried changing the refresh rate but had no success.

Is it possible to include options for configuration of uDMX parameters similar as [shown here](http://www.illutzminator.de/udmxdriver.html?&L=1)?

**Comment by mcallegari** [comment]
1- why didn't you post this in the QLC+ forums ?
2- is your uDMX device actually recognized and "working" with QLC+ on Windows ?
According to the supported hardware chart, it shouldn't be even supported on Windows.
3- QLC+ doesn't implement the DMX timings on a uDMX interface. (it does only on Enttec Open devices) so there is no control of frame timings.
Instead, from what I read on the links you provided, the uDMX driver does it, so I guess you need to follow their instructions and change the Break/Mark/GAB using the uDMX Windows tools. Have you tried that ?

**Comment by croxxx** [comment]
You are probably right, I should have posted this elsehere - sorry for that.

You are right what concerns the use of QLC on Windows. uDMX is not recognized there.
Also, when further researching the topic I found out that the timing control is only present in a special variant of uDMX firmware.
My issue occured on Linux but I guess I will have to work around this some other way.

Thank you for the fast reply. I will close the issue as this is not the proper place for it.
