### ISSUE TITLE
Toggle Scene with non-intensity channels

### ISSUE THREAD

**Issue by oobayly** [mcallegari/qlcplus#60]
I've set up a sample scene in which I want to only modify the Maintenance & Speed channels of a fixture. Whilst I can create a Flash Function Button, The Toggle Function Button doesn't behave properly - When the button is clicked it will set the values as per the scene (as long as the Reset Universe button has been clicked in the Simple Desk - Issue #20), however it doesn't remain pushed, and the scene can't be stopped.

In my test case I have a single Stairville PAR56 with the following channels - Mode (Maintenance), RGB (Intensity) & Speed (Speed).

Function - Set Mode = 192, RGB = 0, Speed = 11

* Actually, sometimes the Flash Function Button doesn't work either:
<a href='http://pastebin.com/mmuupFnF'>Simple Desk Bug.qxc</a>
1. Load sample qxc
1. Switch to operate mode
1. Show Fixture Monitor
1. Hold "3 Colour Change - Fast" flash button - Channels change as expected
1. Now click "3 Colour Change - Fast" toggle button - Channels remain on.
1. Toggle "White" on and then off to reset all channels.
1. "3 Colour Change - Fast" flash button now doesn't operate properly (the Simple Desk sliders now have had the Mode & Speed values set)

I'm putting it down to the fact that the Simple Desk picks up the changes, and due to the channels being LTP (Latest Takes Preference) it is overriding the values being set by the Virtual Desk. This is also noticeable as sometimes the sliders can't set the the Mode & Speed (the slider moves, and the Fixture Monitor shows the change, but then the value is immediately set to the value chosen in Simple Desk)

As useful as the simple desk is, it's causing quite a few issues as it likes to take precedence - it'd be nice to optionally disable it. In fact I'm looking through the source for a way to disable it and recompile.

<a href='http://youtu.be/uofyC3_Dc1Q'>Quick video on how to reproduce</a>

**Comment by mcallegari** [comment]
No feedbacks from the submitter.
Closing now.
