### ISSUE TITLE
QLC+ 4.10 not finding ENTTEC USB DMX Pro

### ISSUE THREAD

**Issue by forresthopkinsa** [mcallegari/qlcplus#613]
I've been using 4.9.1 for some time now, using the DMX USB i/o, with no issues. I'm using Lubuntu 15.04.

When 4.10 came around, I uninstalled 4.9.1, and installed 4.10-qt5.

Now, it is sending zilch to the DMX universe. The USB-DMX box (ENTTEC USB DMX Pro) doesn't even turn the light on that shows that it's receiving data. One of my lights is stuck in "Presentation Mode", because it hasn't received anything over DMX ever since I first opened QLC+ 4.10.

I ran it in Debug Mode, and it gave me this on startup:

>bool QLCFixtureDefCache::loadMap(const QDir&) Unknown Fixture Map tag:  "FixturesMap"
bool QLCFixtureDefCache::loadMap(const QDir&) Unknown Fixture Map tag:  ""
virtual bool LibFTDIInterface::open() "DMX USB PRO" device not found
virtual bool LibFTDIInterface::clearRts() "DMX USB PRO" USB device unavailable
virtual bool LibFTDIInterface::open() "DMX USB PRO" device not found
virtual bool LibFTDIInterface::clearRts() "DMX USB PRO" USB device unavailable

I have no idea what's going on. The device is plugged in exactly like before. The I/O page says that the device is operating correctly, and it's using libFTDI.

Could someone please give me a hand? I have a big event coming up in two days, and I'll probably have to rollback to the previous version until this is sorted out.

**Comment by forresthopkinsa** [comment]
So, yeah, I rolled back to 4.9.1 (not before giving 4.10-qt4 a try, just for kicks and giggles), and it's now functioning correctly again. The I/O config is exactly the same, minus the changes in what it displays, i.e. 4.9.1 doesn't mention libFTDI anywhere.

**Comment by forresthopkinsa** [comment]
By the way (sorry for the triple post) another oddity I experienced with 4.10 was that it wasn't displaying any of my Audio devices in the I/O tab. 4.9.1 displays all four fine, even though it only half-works (audio spectrum RGB matrices don't work at all).

**Comment by mcallegari** [comment]
Fixed by 1b863bf98a2e8d41dc1923dae6b6445aea5bdeb7

**Comment by forresthopkinsa** [comment]
Are you planning on making a 4.10.1 version from this commit? Because this is a pretty severe issue

**Comment by mcallegari** [comment]
http://www.qlcplus.org/forum/viewtopic.php?f=2&p=39745#p39745

**Comment by forresthopkinsa** [comment]
Perfect, thank you!!
