### ISSUE TITLE
Fixtures with missing physical dimensions

### ISSUE THREAD

**Issue by mcallegari** [mcallegari/qlcplus#629]
Just a reminder for who wants to pick this up. @boxy321 ? :wink: 
The following fixtures miss physical dimensions.

EDIT 20151102: shortened list
EDIT 20151103: thanks to Jano now we have also Pan/Tilt information

```
BeamZ-LS-3DRG.qxf: PAN TILT
Eurolite-TB-250.qxf: PAN
JB-Lighting-Varyscan-2.qxf: PAN TILT WIDTH HEIGHT DEPTH WEIGHT
Laserworld-EL-200RGY.qxf: PAN TILT
Lite-Works-ColorChanger.qxf: WIDTH HEIGHT DEPTH WEIGHT
Sagitter-Miniscan-2001.qxf: WIDTH HEIGHT DEPTH WEIGHT
StageTech-LeaderScan-Roto.qxf: PAN TILT
```

**Comment by janosvitok** [comment]
Do we want to change Fixture Editor so that it doesn't allow zero values? Alternatively add button to do final checks on the definition?

**Comment by mcallegari** [comment]
Well, for personal use I don't care what people do. So a fixture without physical information is OK as long as they don't submit it in the forum.
As for a validation button, it is a good idea but I have higher priority tasks to carry on. If you want to implement it please do it :)

**Comment by boxy321** [comment]
Regarding backward compatability here's an example:

Robe ClubSpot 150CT

Physical data: no problem, can add. Modes: there is one missing. If I add the missing one we have to rename the existing ones as nobody uses the names in the manual, ever. What effect would this have? Not good I expect, if somebody has a bunch of effects etc.

**Comment by mcallegari** [comment]
> If I add the missing one we have to rename the existing ones as nobody uses the names in the manual, > ever. What effect would this have? Not good I expect, if somebody has a bunch of effects etc.

If you rename a mode, it breaks backward comaptibility. If you just add one it doesn't.

**Comment by mcallegari** [comment]
Alrighty, closing this for now.
Thanks everyone for the efforts
