### ISSUE TITLE
Peperoni Rodin1 is not recognigned by qlc

### ISSUE THREAD

**Issue by Tolmino** [mcallegari/qlcplus#645]
I think that this issue has happen after hotplug.
the device is recognized in older version of qlcplus, but the git one in input/output tab give me none where are listened peperoni interfaces

**Comment by mcallegari** [comment]
Fixed by bcc315283228c9f4a4dfc09597b1f08baf1c5d43

**Comment by Tolmino** [comment]
Thanks
