### ISSUE TITLE
Peperoni Rodin1 input line is not affected by hotplug

### ISSUE THREAD

**Issue by Tolmino** [mcallegari/qlcplus#666]
Hi,
today i have recompiled and tested last git version.....Peperoni rodin1 are correctly recognized and working.

i have tried too hotplug on different usb interfaces and it is working correctly:
when unplug, interfaces aren't listed
where i plug, interfaces come back in the last universes where was configured.

Peperoni Rodin1 not:
if i unplug, they are still in the universe where are assigned
if i replug, they are still there.

thanks in advance

**Comment by mcallegari** [comment]
Tolmino, since you come directly on GitHub without writing on the forum like everybody else does, at least try to be more accurate in your reports.

The Peperoni Rodin1 MK2 has 1 input and 1 output.
The issue you see is on the input line only.
The output line is removed/added correctly.

**Comment by Tolmino** [comment]
You are right..... I haven't tested it as output device. Because i use it only as an input interface.

**Comment by mcallegari** [comment]
Fixed by a5ab338d5971d5e3c0b7bd62292b241064941f64
