### ISSUE TITLE
Loading a workspace with 2d monitor open does not update the 2d monitor dimensions

### ISSUE THREAD

**Issue by plugz** [mcallegari/qlcplus#669]
http://qlcplus.org/forum/viewtopic.php?f=5&t=9137

- Save a workspace with 1x1 monitor size.
- Set the monitor size to 5x5.
- Open 1x1 workspace with the monitor open -> the size it not updated
- Closing and reopening the monitor fixes the issue

**Comment by mcallegari** [comment]
Update: the actual 2D preview is correctly rendered.
What is not updated are only the spin boxes in the toolbar.

**Comment by mcallegari** [comment]
Fixed by 736b87a526b311cc3dbb51dadef3215e19f2e6ac
