### ISSUE TITLE
Animation widget not clickable everywhere in edit mode

### ISSUE THREAD

**Issue by siegmund42** [mcallegari/qlcplus#670]
When adding a new animation widget, it's only clickable outside of the click&go areas. When clicking inside of them nothing happens.

I would expect to be able to click these areas, too. Especially for drag and drop in edit mode. These areas are very large compared to the whole widget size and placed in the center so it's the typical place where most of the users might click the widget - and don't recognize any reaction.

Recognized in QLC+ 4.10.1 on xUbuntu 14.04 64Bit installed from official packages (Qt 4.8.3)

**Comment by mcallegari** [comment]
This issue report is incomplete.
Please state the OS and the Qt version where you see it.

If it is the same thing I've noticed, it's related to Qt4. On the Speed Dial widget is even more visible.

**Comment by siegmund42** [comment]
Sorry for that!

I added the OS and QLC+ version information but I don't know the Qt version - how can I figure it out?

**Comment by mcallegari** [comment]
Ubuntu 14.04 32bit or 64bit ?
Did you compile it yourself or do you use the official packages ?
In the second case, you're on Qt4.

You can check it by opening the documentation window and by clicking on the Qt logo on the top right corner.

**Comment by siegmund42** [comment]
Thank you for your explanations! Hope the informations are completely now.

**Comment by mcallegari** [comment]
I suggest you to use QLC+ on Qt5. Either build from released sources or use an automated build on Qt5:
http://www.qlcplus.org/downloads.html

https://software.opensuse.org/download.html?project=home%3Amcallegari79&package=qlcplus-qt5
https://software.opensuse.org/download.html?project=home%3Amcallegari79&package=qlcplus-qt5-git

At this point I don't think it's worth to fix Qt4 specific issues as Qt4 is phasing out from distros.

**Comment by siegmund42** [comment]
Although I'm still using xUbuntu 14.04, which is not supported for automated builds I'm completely with you!

**Comment by mcallegari** [comment]
After 758cb08eea5fbff99fecf583771cfaca34cfdc33 Qt5 GIT automated builds now work.
Closing this for now
