### ISSUE TITLE
Bug with cue list hitting next, then crossfader and then next again

### ISSUE THREAD

**Issue by anorod** [mcallegari/qlcplus#672]
I have a cue list with different scenes, some of them have the fade timing set, but others I need to fade it manually because the scene depends on some actors. The problem with 4.10.1 that was not before is that when I hit next and then do the crossfade, when I hit next again later it continues since the last cue I did with the next button.

Eg:
I have 10 scenes in a cue list. The first 5 with timing so I hit the next cue button. After the 5th, I use the crossfader with 3 more so I am in cue 8th. If I hit next now instead of use the crossfader, I will jump to cue 6 instead of 9.

I've tested it with MacOS 10.9.5 and Windows with the same results. Also I've tested versions 4.10.1, 4.9.1, 4.8.5 and it's the same.

I've been looking at the code and while hitting the next button just do ch->next() in line 619:
  https://github.com/mcallegari/qlcplus/blob/master/ui/src/virtualconsole/vccuelist.cpp#L619

In the sliders it change manually and it doesn't seem to update the current cue number. Maybe the bug could be solved updating the current cue number after the following lines:
 - For Slider1: https://github.com/mcallegari/qlcplus/blob/master/ui/src/virtualconsole/vccuelist.cpp#L998
 - For Slider2: https://github.com/mcallegari/qlcplus/blob/master/ui/src/virtualconsole/vccuelist.cpp#L1048

I'm guessing it may be something similar to *ch->setCurrentStep(ch->currentStepIndex() + 1);* but not sure.

Thank's for a great software!

**Comment by anorod** [comment]
Tested plugz fix on the 4.10.1 and seemed to work fine except one thing:
- If at the end of using the sliders they slider are "upside down" (slider #1 to 0 and slider #2 at 100%) it does the next cue without the fade in value and then all times you hit next the DMX values are all 0 (probably because they are multiplying by the slider #1)

**Comment by mcallegari** [comment]
Fixed by #674
