### ISSUE TITLE
Bug when using crossfaders in vc cue lists

### ISSUE THREAD

**Issue by anorod** [mcallegari/qlcplus#677]
When you use the crossfaders, the numbers at the bottom of each crossfade change every time you make a crossfade, but it should only change the number of the cue that just finished:

Eg:
 - Crossfader 1 at 100% cue 1
 - Crossfader 2 at 0% cue 2

-> You crossfade, it should end:
 - Crossfader 1 at 0% cue 3
 - Crossfader 2 at 100% cue 2

Instead it reads:
 - Crossfader 1 at 0% cue 2
 - Crossfader 2 at 100% cue 3

When you crossfade again it works well, but if you press the next button it will do something strange because at some point you will have the active cue multiplied by the crossfader that is 0%.

**Comment by anorod** [comment]
Maybe related, after using the crossfaders if you hit next the fade in time is not respected because the next cue is on the crossfader that is 100%.

**Comment by anorod** [comment]
I've been seeing that when you hit next, the cue associated with each crossfader works well because in that case it should change like it does:

* Crossfader 1 at 100% cue 1
* Crossfader 2 at 0% cue 2

-> You crossfade, it should end:

* Crossfader 1 at 100% cue 2
* Crossfader 2 at 0% cue 3

Maybe assigning the crossfaders depending on if you use them or hit next is going to make some trouble, because someone may move a bit the crossfaders, then come back and then hit next or some other scenarios. I thought that maybe a good approach would be:

* Assign the current (the one that has just change) cue to the crossfader that is highest and the next one to the one that is lowest. If both are the same, assign the current to the crossfader 1 and next one to crossfader 2.

Probably to fix the fade in time, also when using next check if the next crossfader is above 98% and perform the timed fade in of that scene. If it's less than 98%, then bring up the scene with the fade time of the scene or right away.

**Comment by anorod** [comment]
Hi again:

Maybe the problem is when assigning the value of the variable *m_primaryLeft*, it should take in account what fader is at 100%. So far I've seen:
* https://github.com/plugz/qlcplus/blob/cuelist-fix/ui/src/virtualconsole/vccuelist.cpp#L535

In here it just return "1.0" when it's in crossfade mode, but probably it would be a good place to also assign the variable *m_primaryLeft* true or false depending on which crossfader is at 100% (or as said in the previous comment the highest one).

* https://github.com/plugz/qlcplus/blob/cuelist-fix/ui/src/virtualconsole/vccuelist.cpp#L909

Maybe here it will also be good to check what fader is at 100% (or highest one) and assign *m_primaryLeft* accordingly.

* https://github.com/plugz/qlcplus/blob/cuelist-fix/ui/src/virtualconsole/vccuelist.cpp#L985

In here I think that what messes up is the if conditions *(m_primaryLeft == true && value == 0 && m_slider2->value() == 100)* and *(m_primaryLeft == false && value == 100 && m_slider2->value() == 0)* because when there is a problem is when the *m_primaryLeft* is wrong assigned. Same happens in line:
https://github.com/plugz/qlcplus/blob/cuelist-fix/ui/src/virtualconsole/vccuelist.cpp#L1020


Hope I've helped

**Comment by plugz** [comment]
Hello,

Can you test this branch and tell me if you can spot any more issues related to the Cue List : 
https://github.com/plugz/qlcplus/tree/cuelist-fix-2

Thanks

**Comment by anorod** [comment]
Hello David,

Not quite, but closer. After using the faders, when you hit the next button, the next cue will not follow the fade in time. Also, when you move the fader, the one that gets to 0 has a little timing at the end don't know why. -> I move them quickly and I see the channel moving quickly but at the end the fader is at 0% and I can see the channel doing 3, 2, 1, 0.

Other than that, it seems to work fine.

**Comment by plugz** [comment]
> After using the faders, when you hit the next button, the next cue will not follow the fade in time.

Well, when you start using the fader, the next cue is in "manual fade in" mode, so it seems logical that is does not follow the step fade in time.
But going back to an intensity of 0 should indeed reset this "manual fade in" state.

> Also, when you move the fader, the one that gets to 0 has a little timing at the end don't know why. -> I move them quickly and I see the channel moving quickly but at the end the fader is at 0% and I can see the channel doing 3, 2, 1, 0.

This happens on steps with a fade out time. I guess the step should be in "manual fade out" state.


I'll get back to you when I've made some more fixes

**Comment by anorod** [comment]
>> After using the faders, when you hit the next button, the next cue will not follow the fade in time.
> Well, when you start using the fader, the next cue is in "manual fade in" mode, so it seems logical that > is does not follow the step fade in time.
> But going back to an intensity of 0 should indeed reset this "manual fade in" state.

Not exactly, I think I expressed myself wrong. The process is the following:
* Hit next a few times.
* I do a manual crossfade with the faders linked and I finish the crossfade completely. (I do them by dragging with the mouse, not MIDI)
* After I finish the crossfade, I don't start the following one at any moment.
* I hit next again and it doesn't follow the fade in time.

I'm thinking that maybe it's because when the fade finishes the mouse is still holding the faders so the program thinks that next fade is also manual.

>> Also, when you move the fader, the one that gets to 0 has a little timing at the end don't know why. -> >> I move them quickly and I see the channel moving quickly but at the end the fader is at 0% and I can >> see the channel doing 3, 2, 1, 0.
> This happens on steps with a fade out time. I guess the step should be in "manual fade out" state.

Ok. It's just a detail because even with that it's not a problem because the levels are very low.

> I'll get back to you when I've made some more fixes

Thank you very much David. Are you also fixing #439 in this branch?. Just to know if I should test that too.

**Comment by plugz** [comment]
>Not exactly, I think I expressed myself wrong. The process is the following:
* Hit next a few times.
* I do a manual crossfade with the faders linked and I finish the crossfade completely. (I do them by dragging with the mouse, not MIDI)
* After I finish the crossfade, I don't start the following one at any moment.
* I hit next again and it doesn't follow the fade in time.

Ah yes, this happens too... Yes, this issue is more annoying.

> Thank you very much David. Are you also fixing #439 in this branch?. Just to know if I should test that too.

Nope

**Comment by anorod** [comment]
Perfect. I will use #439 to find a way to fix the transitions when you use the crossfaders. When hitting next it do it correctly but with the faders it always go to the middle. :)

**Comment by plugz** [comment]
Updates have been made, it would be nice if you could re-test this branch:

https://github.com/plugz/qlcplus/tree/cuelist-fix-2

Thanks :)


> Perfect. I will use #439 to find a way to fix the transitions when using the crossfaders. When hitting next it does it correctly but with the faders it always go trough the middle. :)

Nice

**Comment by anorod** [comment]
I don't have my laptop with me right now but I will test it in the theatre in 3 hours approx and tell you :).

**Comment by anorod** [comment]
Hi David, So far it seems it works perfect. Even with moving the faders a bit and then hit next or similar it seems to respond great.

Very very good work. Thank you very much.

**Comment by mcallegari** [comment]
#678 merged. If all is ok, please close this.

**Comment by anorod** [comment]
Closing. Thank you very much.
