### ISSUE TITLE
Strobo preview improvements

### ISSUE THREAD

**Issue by mcallegari** [mcallegari/qlcplus#696]
I'm opening this as a reminder, for who wants to pick up this task.
Sooner or later this has to be done anyway, cause I want to have a reliable preview in QLC+ 5.

The changes have to start from the ground up. The involved components are:

1) Fixture Editor: a Shutter channel should expose the following capabilities:
- shutter open
- shutter close
- specific frequency
- frequency range
  If the frequencies are not specified in the fixture manual, and instead there is something like "Strobe (slow to fast)" I would say the default behaviour should be an implicit range of 1Hz to 10Hz

2) QLCCapability class: likewise the color/resource properties we could add:
- shutterType: Enum { Close, Open, Fixed, Range }
- shutterMinFreq
- shutterMaxFreq
  In case of Open/Close the Freq variables will be ignored
  In case of Fixed, shutterMinFreq will be used and shutterMaxFreq will be ignored

3) 2D Monitor: when we have all the information we need in a QLCCapability, then the monitor will be easy to implement, as long as every FixtureItem has a QTimer to handle the strobe frequency

**Comment by janosvitok** [comment]
3) partially fixed: cf58886f4ccd (added strobing timer using currently available info)

**Comment by janosvitok** [comment]
See also http://www.qlcplus.org/forum/viewtopic.php?p=45107

**Comment by mcallegari** [comment]
This can finally be closed. Addressed with #1026
