### ISSUE TITLE
Bug copying and pasting frames with submasters

### ISSUE THREAD

**Issue by anorod** [mcallegari/qlcplus#704]
Hi, I saw this bug while working with the VC:

- First we make a frame with a few sliders and one of them in submaster mode to control all the frame.
- Then we copy and paste the frame and change the sliders to control other scenes or channels.

When using the submaster on the second, doesn't work with the sliders of the frame.

Hope it helps :)

**Comment by plugz** [comment]
Fixed by https://github.com/mcallegari/qlcplus/commit/f71a156c08112090a74ca5fafc651131507be460

Thank for reporting :)

**Comment by anorod** [comment]
Happy to help!
I will prepare the example of the other bug later today :).
Thanks!
