### ISSUE TITLE
Bug in chaser when going from a show to the same scene as the end of the show

### ISSUE THREAD

**Issue by anorod** [mcallegari/qlcplus#705]
Hi again:

I have a few shows working on a chaser, that when the show finish I have a scene at the end that is the same as the next scene of the chaser. This is because after the show I want to get back in control of the cues so I can continue hitting "next" or fading as usual.

What I saw is that when I use the same scene after the show that the one I use at the end of the show inside the show, I have a blackout. Eg:

I have scenes 5 scenes with different channels on. I have a show that goes 2->3->4 automatically with some timing, but scene number 4 is infinite duration. If I make a chaser that goes: 1->show->4->5, when I hit next after the show it should not make any change, but instead it makes a blackout.

Probably this is because at the same time the system is fading up 4 and fading it down.

Hope it helps too :)

**Comment by plugz** [comment]
Hello,

Can you post a workspace file demonstrating the issue ?
You can post it in a forum thread there : http://qlcplus.org/forum/ and link the thread here.

Thank you

**Comment by anorod** [comment]
Hi!,
Here is the example:
 - http://qlcplus.org/forum/viewtopic.php?f=5&t=9492
Thanks

**Comment by plugz** [comment]
Fixed by #787
