### ISSUE TITLE
qmake: use standard variables

### ISSUE THREAD

**Issue by daveol** [mcallegari/qlcplus#729]
attempting to package QLC+ for fedora, I stumbled upon some things. Namely the assignment of directories where things get installed.  I noticed you don't use the [standard](http://doc.qt.io/qt-5/qmake-environment-reference.html) environment variables to install all the libraries, plugins and bin files. Most of these variables work in qmake-qt4 too (not the "QT_HOST" ones).

For the ["LIBSDIR"](/mcallegari/qlcplus/blob/master/variables.pri#L81) variable can just be "$$[QT_INSTALL_LIBS]" this would also solve the issue where libraries are always installed in "/usr/lib" while 64 bit libs usally go in "/usr/lib64" or some variation. 

For the ["PLUGINDIR"](/mcallegari/qlcplus/blob/master/variables.pri#L172) the variable can just be
"$$[QT_INSTALL_PLUGINS]/qlcplus".

There are probably more examples, to show these "build-in" variables just run in a shell
```bash
qmake -query
``` 
or your platform specific equivalent and it will show the variables and their values.

**Comment by mcallegari** [comment]
Fedora packages are built automatically here:
https://build.opensuse.org/project/show/home:mcallegari79

What's wrong with them ?

**Comment by daveol** [comment]
I was talking about the official fedora repository, since I am a packager there now, I already packaged [ola](https://apps.fedoraproject.org/packages/ola). and I plan on packaging QLC+, the repository you mentioned has to be enabled by a user, the repository I'm talking about is the official one and is where fedora get's it's packages from by default.

**Comment by mcallegari** [comment]
Alright, questions:
- are you packing QLC+ on Qt4 or Qt5 ?
- how is QT_INSTALL_LIBS set to in your environment ?

On Ubuntu 14.04 (qt4) is
QT_INSTALL_LIBS:/usr/lib/x86_64-linux-gnu

I suppose changing LIBDIR to $$QT_INSTALL_LIBS should be OK.
I need to double check on OBS if it is OK on Arch and OpenSUSE as well

**Comment by daveol** [comment]
> - are you packing QLC+ on Qt4 or Qt5 ?

Qt5, since that is the newest version of qt and fedora has a preference to keep packages as new as possible (rolling release).
> - how is QT_INSTALL_LIBS set to in your environment ?

Qt5 gives
QT_INSTALL_LIBS:/usr/lib64

and Qt4 gives
QT_INSTALL_LIBS:/usr/lib64
 
This was tested on fedora 23

**Comment by mcallegari** [comment]
OK, thanks. Just in case, are packages generated automatically (e.g. sources from a git tag) or are they built manually and uploaded in the official repos ?
For which Fedora versions will QLC+ be available ? 23 and afterwards ?

**Comment by daveol** [comment]
The update process is manual, so if a new version comes out I will update the spec file to match (the source tag has to be an url though). [This](https://gist.github.com/daveol/aee914a9eda710547891) is my spec file now, be aware I just started.

For fedora versions, if i would publish the package now i could publish it on EPEL 5, 6 and 7 (extra packages for Redhat and CentOS) and Fedora 21, 22, 23 and Rawhide (24) (this may change depending on the EOL of some of these distributions and/or new versions coming out)

**Comment by daveol** [comment]
Also while the update process is manual, fedora uses [release monitoring](https://release-monitoring.org/project/8358/) to keep track of new versions and notify their packagers.

**Comment by mcallegari** [comment]
I see, but I was wondering. Even if I make the change now, it won't be tagged in a release build until the next QLC+ version.
Normally git sources produce a debug build for testers and developers.
I will come up with a patch but I'm afraid for the current version you need to apply it manually or wait for the next upstream version

**Comment by daveol** [comment]
I don't mind making my own patches, however fedora has the [requirement to stay close to upstream](https://fedoraproject.org/wiki/Staying_close_to_upstream_projects) and keep the number of patches as low as possible by submitting them/ask about them upstream.

**Comment by daveol** [comment]
Basically this is a heads up that patches may come in the future, and that a fedora package is in the making.

**Comment by mcallegari** [comment]
@daveol this is the patch you're looking for: 16b6728e5066a041297bc4d424ada515e85a1e75

It passes Travis builds and now I'm testing it on OBS.
Basically it replaces the hardcoded paths (libs and plugins) if QT provides install paths starting from /usr. I had to do this weird check, cause I normally don't use system Qt versions, but prebuilt ones, and they install in /home/something. In that case I fall back to the old /usr/lib, which for development shouldn't hurt anybody.

**Comment by mcallegari** [comment]
[Update] building on OBS, I realized some Qt installations provide different QT_INSTALL_PREFIX, so please create a patch against the current variables.pri GIT version

**Comment by daveol** [comment]
This is fixed
