### ISSUE TITLE
Retina support on Mac

### ISSUE THREAD

**Issue by jpxd** [mcallegari/qlcplus#733]
Currently the application gets rendered and upscaled on a MacbookPro Retina resulting in a blurry UI and ugly font renderings.
See http://blog.qt.io/blog/2013/04/25/retina-display-support-for-mac-os-ios-and-x11/
Example screenshot:
<img width="470" alt="screenshot 2015-12-21 09 39 57" src="https://cloud.githubusercontent.com/assets/10384363/11926704/37f22104-a7c7-11e5-8ba6-d7512e2189c3.png">

**Comment by mcallegari** [comment]
Have you tried the Info.Plist changes the blog post you linked talks about ?

**Comment by jpxd** [comment]
That was definitely too easy.... Sorry, I didn't try it beforehand, I thought there were adjustments in the code to make. Looks good now except the images, but I can live with that. I'll submit a PR :smile:

**Comment by jpxd** [comment]
PR #737
