### ISSUE TITLE
Wrongly Licensed files?

### ISSUE THREAD

**Issue by daveol** [mcallegari/qlcplus#736]
While packaging for fedora I ran fedora-review and came across some licenses which I have some questions about. (if you want to look at the full license check output look [here](https://gist.github.com/daveol/c6c88ef13183122d1619))

First of all there are a lot of files that don't have licenses like all the png files (which can be given licenses by setting a [Exif](https://commons.wikimedia.org/wiki/Commons:Exif#License_information) tag), but also some source files like [hotplugmonitor/test/hpmtest.cpp](https://github.com/mcallegari/qlcplus/blob/master/hotplugmonitor/test/hpmtest.cpp) (there are way more, look at the [full output](https://gist.github.com/daveol/c6c88ef13183122d1619) for more)

- BSD (3 clause)
 - Is this still an example from qt? If no, why does it have the BSD license?
 - **files:**
    - [ui/src/flowlayout.cpp](https://github.com/mcallegari/qlcplus/blob/master/ui/src/flowlayout.cpp)
    - [ui/src/flowlayout.h](https://github.com/mcallegari/qlcplus/blob/master/ui/src/flowlayout.h)
- GPL (v2) (with incorrect FSF address)
 - Aren't these supposed to be Apache license? The address is incorrect so if these files need to be GPL v2 then the address needs to be updated.
 - **files:**
    - [plugins/midi/common/miditemplate.cpp](https://github.com/mcallegari/qlcplus/blob/master/plugins/midi/common/miditemplate.cpp)
    - [plugins/midi/common/miditemplate.h](https://github.com/mcallegari/qlcplus/blob/master/plugins/midi/common/miditemplate.h)
    - [ui/src/functionstreewidget.cpp](https://github.com/mcallegari/qlcplus/blob/master/ui/src/functionstreewidget.cpp)
    - [ui/src/functionstreewidget.h](https://github.com/mcallegari/qlcplus/blob/master/ui/src/functionstreewidget.h)
    - [ui/src/palettegenerator.cpp](https://github.com/mcallegari/qlcplus/blob/master/ui/src/palettegenerator.cpp)
    - [ui/src/palettegenerator.h](https://github.com/mcallegari/qlcplus/blob/master/ui/src/palettegenerator.h)
- LGPL (v2 or later) (with incorrect FSF address)
 - Same story as the GPL (v2) (with incorrect FSF address) ones.
 - **file:**
    - [plugins/udmx/src/libusb_dyn.c](https://github.com/mcallegari/qlcplus/blob/master/plugins/udmx/src/libusb_dyn.c)

I'm making a issue because I don't know how you want the licenses. If you want a (proper) list of the files that still need a license just ask.

**Comment by mcallegari** [comment]
I quickly fixed a few headers (your second item). Thanks for spotting.

1) In the files I've taken from other projects, I left the original license header. Apache is quite flexible in that sense, but I have to admit I haven't checked every single detail
2) PNG does not contain EXIF. Those are for JPEG files
3) Some files are so old that they have outdated information (libusb_dyn.c). I'll update them with a proper up to date header

**Comment by daveol** [comment]
[well okay "chunks" then](http://stackoverflow.com/questions/9542359/does-png-contain-exif-data-like-jpg)

**Comment by mcallegari** [comment]
To be honest I don't really have time to check every single PNG file and set the attribution.
Is that mandatory ?

P.S. Disregard everything inside the qmlui folder. It's a work in progress and it's not built in QLC+ 4

**Comment by daveol** [comment]
1) Never mind it's not required (i believe).... but it could be automated (I could write a python script if you want to)

2) well okay... but fedora considers it still part of the source

**Comment by mcallegari** [comment]
I've pushed some more fixes

> 2) well okay... but fedora considers it still part of the source
FontAwesomeVariables.qml has been taken from a blog post. It's just the definition of some variables and I think I can license it under Apache. Not sure if Apache and MIT can go together

**Comment by daveol** [comment]
Here is a list from parsing the "no licence" files:
- [ ] [hotplugmonitor/src/hpmprivate-win32.h](https://github.com/mcallegari/qlcplus/tree/master/hotplugmonitor/src/hpmprivate-win32.h)
- [ ] [hotplugmonitor/test/hpmtest.cpp](https://github.com/mcallegari/qlcplus/tree/master/hotplugmonitor/test/hpmtest.cpp)
- [ ] [hotplugmonitor/test/hpmtest.h](https://github.com/mcallegari/qlcplus/tree/master/hotplugmonitor/test/hpmtest.h)
- [ ] [hotplugmonitor/test/main.cpp](https://github.com/mcallegari/qlcplus/tree/master/hotplugmonitor/test/main.cpp)
- [ ] [launcher/launcher.cpp](https://github.com/mcallegari/qlcplus/tree/master/launcher/launcher.cpp)
- [ ] [launcher/launcher.h](https://github.com/mcallegari/qlcplus/tree/master/launcher/launcher.h)
- [ ] [launcher/main.cpp](https://github.com/mcallegari/qlcplus/tree/master/launcher/main.cpp)
- [ ] [plugins/hid/hidapi.h](https://github.com/mcallegari/qlcplus/tree/master/plugins/hid/hidapi.h)
- [ ] [plugins/hid/linux/hidapi.cpp](https://github.com/mcallegari/qlcplus/tree/master/plugins/hid/linux/hidapi.cpp)
- [ ] [plugins/hid/macx/hidapi.cpp](https://github.com/mcallegari/qlcplus/tree/master/plugins/hid/macx/hidapi.cpp)
- [ ] [plugins/hid/win32/hidapi.cpp](https://github.com/mcallegari/qlcplus/tree/master/plugins/hid/win32/hidapi.cpp)
- [ ] [plugins/hid/win32/pthread.c](https://github.com/mcallegari/qlcplus/tree/master/plugins/hid/win32/pthread.c)
- [ ] [plugins/hid/win32/pthread.h](https://github.com/mcallegari/qlcplus/tree/master/plugins/hid/win32/pthread.h)
- [ ] [plugins/hid/win32/sleep.cpp](https://github.com/mcallegari/qlcplus/tree/master/plugins/hid/win32/sleep.cpp)
- [ ] [plugins/peperoni/common/main.cpp](https://github.com/mcallegari/qlcplus/tree/master/plugins/peperoni/common/main.cpp)
- [ ] [plugins/peperoni/win32/peperoni/usbdmx-dynamic.cpp](https://github.com/mcallegari/qlcplus/tree/master/plugins/peperoni/win32/peperoni/usbdmx-dynamic.cpp)
- [ ] [plugins/peperoni/win32/peperoni/usbdmx-dynamic.h](https://github.com/mcallegari/qlcplus/tree/master/plugins/peperoni/win32/peperoni/usbdmx-dynamic.h)
- [ ] [plugins/udmx/src/libusb_dyn.h](https://github.com/mcallegari/qlcplus/tree/master/plugins/udmx/src/libusb_dyn.h)
- [ ] [webaccess/src/commonjscss.h](https://github.com/mcallegari/qlcplus/tree/master/webaccess/src/commonjscss.h)

If they have the checkbox crossed out they have been done

**Comment by mcallegari** [comment]
Fixed some more.
For plugins/hid/* see above.
For plugins/peperoni/win32/* same as hid

**Comment by daveol** [comment]
I think GPL for the hid and peperoni stuff is fine

**Comment by mcallegari** [comment]
I pushed some changes to make HIDAPI and Peperoni DLL loader GPLv2 sources

**Comment by daveol** [comment]
[new output](https://gist.github.com/024f76a035d79810fed0)

**Comment by mcallegari** [comment]
Looks OK to me now, no ?

**Comment by daveol** [comment]
seems okay... I'll write something small that can be run on travis using [licensecheck](https://github.com/rgeissert/devscripts/blob/master/scripts/licensecheck.pl) from [devscripts](https://packages.debian.org/sid/devscripts) if you want

**Comment by mcallegari** [comment]
Uhm, Travis checks every single commit including pull requests. Seems like a waste of resources to check licenses for each one of them.
I'd prefer to have a script that I can run manually and offline (mostly when new files are added)

**Comment by daveol** [comment]
see #748 for a script which lists files with unknown license, also "waste of resources" is not really a big deal for Travis, for [ola](/OpenLightingProject/ola) we currently have 9 [tasks](https://travis-ci.org/OpenLightingProject/ola) running of which 3 are lint tools, one of which includes a license checker tool and it still finishes pretty fast.

**Comment by daveol** [comment]
- [ ] [webaccess/res/websocket.js](/mcallegari/qlcplus/blob/master/webaccess/res/websocket.js)
- [ ] [webaccess/res/simpledesk.js](/mcallegari/qlcplus/blob/master/webaccess/res/simpledesk.js)
- [ ] [webaccess/res/virtualconsole.js](/mcallegari/qlcplus/blob/master/webaccess/res/virtualconsole.js)
- [ ] [webaccess/res/networkconfig.js](/mcallegari/qlcplus/blob/master/webaccess/res/networkconfig.js)
- [ ] [resources/docs/utility.js](/mcallegari/qlcplus/blob/master/resources/docs/utility.js)
- [ ] [resources/rgbscripts/randomfillsingle.js](/mcallegari/qlcplus/blob/master/resources/rgbscripts/randomfillsingle.js)
- [ ] [resources/rgbscripts/randomsingle.js](/mcallegari/qlcplus/blob/master/resources/rgbscripts/randomsingle.js)
- [ ] [resources/rgbscripts/randomcolumn.js](/mcallegari/qlcplus/blob/master/resources/rgbscripts/randomcolumn.js)
- [ ] [resources/rgbscripts/randomfillcolumn.js](/mcallegari/qlcplus/blob/master/resources/rgbscripts/randomfillcolumn.js)
- [ ] [resources/rgbscripts/fillunfillsquaresfromcenter.js](/mcallegari/qlcplus/blob/master/resources/rgbscripts/fillunfillsquaresfromcenter.js)
- [ ] [resources/rgbscripts/squaresfromcenter.js](/mcallegari/qlcplus/blob/master/resources/rgbscripts/squaresfromcenter.js)
- [ ] [resources/rgbscripts/randomrow.js](/mcallegari/qlcplus/blob/master/resources/rgbscripts/randomrow.js)
- [ ] [resources/rgbscripts/devtool.js](/mcallegari/qlcplus/blob/master/resources/rgbscripts/devtool.js)
- [ ] [resources/rgbscripts/randomfillrow.js](/mcallegari/qlcplus/blob/master/resources/rgbscripts/randomfillrow.js)

**Comment by mcallegari** [comment]
Fixed ! c7ef20a12dfc1cb15c0b6cbdd10aaabc06a6bbcb

**Comment by janosvitok** [comment]
Just partly related (and IANAL): is it legal to include GPL-licenced (not LGPL, the plain GPL) software (e.g. mongoose) in an APL-licenced software (QLC+)?

See for example http://www.apache.org/licenses/GPL-compatibility.html

**Comment by daveol** [comment]
Missing licenses have been resolved further issues with the licenses themselves can be found in the issue #760
