### ISSUE TITLE
High definition icons

### ISSUE THREAD

**Issue by jpxd** [mcallegari/qlcplus#738]
Hi, after updating the Info.Plist file to support Retina display, QLC+ renders in the right definition and the fonts are crisp again. The only exception are the icons (see screenshot).
<img width="172" alt="screenshot 2015-12-24 12 44 15" src="https://cloud.githubusercontent.com/assets/10384363/11994313/4b95142e-aa3c-11e5-8e03-97c25ca1e92d.png">
Now I noticed that there already are SVG icons which can render at any definition (like [the knob](https://github.com/mcallegari/qlcplus/blob/49a0a6d29070bc17a632f84f0a18add8ba859573/resources/icons/svg/knob.svg) from the screenshot) in the resources but they are either not used or rendered in the correct definition.
I would be willing to test changes or to implement them If one can give me a hint where to look :)

**Comment by mcallegari** [comment]
Calm down.
SVG icons are for QLC+ 5 and not QLC+ 4. Plus, rendering SVG icons requires an extra Qt library.

Until I release some QLC+ 5 version, you need to live with PNG icons.
