### ISSUE TITLE
Split the audio decoders off into plugins (libmad, libsndfile)

### ISSUE THREAD

**Issue by daveol** [mcallegari/qlcplus#755]
Packaging for fedora I can't require libmad since it is not available of the standard repository (it is in the [rpmfusion](http://rpmfusion.org/) repository). Is libmad required for core features? QLC+ builds without it but does it take away from support?

**Comment by mcallegari** [comment]
QLC+ builds without libmad, but it will have no MP3 playback support.
Since it is a quite popular feature, we normally build with it.
How do other audio packages do on Fedora ?

**Comment by daveol** [comment]
Fedora doesn't have any mp3 libraries in their repositories because of patent issues (libmad is in violation of those). But most audio libraries are there. Is there a way to use g-streamer for this? Since that is very much expandable and allows to just install gstreamer-plugins-ugly (from rpmfusion) to add mp3 support.

**Comment by daveol** [comment]
libsndfile and libfftw3 are both in the main repository

**Comment by mcallegari** [comment]
I think I could use gstreamer through Qt on Linux.
Problem is that I evaluated the audio decoding part of Qt and I preferred not to use it.
QtMultimedia is incredibly buggy and has a very bad support.
Also there might be issues on OSX. See this
http://wiki.qt.io/Qt_5.5.0_Multimedia_Backends

**Comment by daveol** [comment]
then why not just use [Gstreamer](http://gstreamer.freedesktop.org/) it selft or [Gstreamermm](https://developer.gnome.org/gstreamermm/stable/) (the cpp bindings), since gstreamer is pretty stable on it self and available on all platforms

**Comment by kripton** [comment]
I've use qt-gstreamer (http://gstreamer.freedesktop.org/modules/qt-gstreamer.html) in the past and found it pretty straight-forward. Is that included in the fedora repos?

**Comment by daveol** [comment]
yes it is [here](https://apps.fedoraproject.org/packages/qt5-gstreamer)

**Comment by daveol** [comment]
I checked more distro's:
- [ubuntu](http://packages.ubuntu.com/source/vivid/qt-gstreamer) has it but only in qt4 flavor
- [debian](https://packages.debian.org/source/sid/qt-gstreamer) has it

**Comment by mcallegari** [comment]
In OBS we build against a fake libmad, so users are 'forced' to download the real libmad themselves.
See here: https://build.opensuse.org/project/show/home:mcallegari79
Best thing would be to turn QLC+ audio decoders interfaces into Qt plugins loaded at runtime. The "mad" plugin will link against libmad, so if it is not found in the system, it will not load.

Fair enough ? (however...who has time to implement it ? :cry:  )

**Comment by daveol** [comment]
> In OBS we build against a fake libmad, so users are 'forced' to download the real libmad themselves.
See here: https://build.opensuse.org/project/show/home:mcallegari79
Best thing would be to turn QLC+ audio decoders interfaces into Qt plugins loaded at runtime. The "mad" plugin will link against libmad, so if it is not found in the system, it will not load.

So like the other plugins for QLC+ (ola, gpio, uart, etc.) ?

**Comment by mcallegari** [comment]
> So like the other plugins for QLC+ (ola, gpio, uart, etc.) ?

Exactly

**Comment by daveol** [comment]
so there would be:
- plugin-audio-ftww3
- plugin-audio-libsnd
- plugin-audio-libmad
- plugin-audio-alsa?

or did you *just* want to split off the libmad part?

**Comment by mcallegari** [comment]
Nope.
There are audio decoders (mad, sndfile), audio capture (ALSA, WAVEIN, PortAudio, Qt) and audio renderers (ALSA, WAVEOUT, PortAudio, Qt). 
FFTW is a topic on its own and it is related to audio capture.

I think turining audio decoders into plugins would be enough, so the names would be:
libmadplugin.so
libsndfileplugin.so

**Comment by daveol** [comment]
> I think turining audio decoders into plugins would be enough, so the names would be:
libmadplugin.so
libsndfileplugin.so

Okay, but these would still be located in the same directory as the existing QLC+ plugins?

**Comment by mcallegari** [comment]
> Okay, but these would still be located in the same directory as the existing QLC+ plugins?

Good question. The answer is no, cause QLC+ would try to load them as DMX input/output plugins.
I guess we should need to create a new path for those plugins like:
/usr/lib/qt5/plugins/qlcplus/audio

**Comment by daveol** [comment]
sound like a good idea, I could try and get the subpackage for the plugin that uses libmad in rpmfusion so people can still get the mp3 support for QLC+

**Comment by mcallegari** [comment]
Done and upstream

@plugz @janosvitok if you have the chance, please let me know if there's something wrong with the migration
