### ISSUE TITLE
RGB matrix fadein is broken when starting an RGB matrix from a VC slider

### ISSUE THREAD

**Issue by plugz** [mcallegari/qlcplus#758]
Because of this:
https://github.com/mcallegari/qlcplus/pull/699
(sorry)

This can be fixed by simply ignoring overridefadein and overridefadeout.
Or use them differently (use them as global fade in and fade out speed instead of step fadein and fadeout speed).
Or revert 699.

The issue is the same for chasers, and a fix could fix this issue too: https://github.com/mcallegari/qlcplus/issues/445

**Comment by mcallegari** [comment]
Fixed by 0707e7e4513a83c2e4c57846d890096b3880809c by reverting #699 until a better solution is found
