### ISSUE TITLE
missing call to setgroups before setuid

### ISSUE THREAD

**Issue by daveol** [mcallegari/qlcplus#759]
The code in mongoose [here](https://github.com/mcallegari/qlcplus/blob/master/webaccess/src/mongoose.c#L5096-L5101) does a ```setuid()``` but doesn't do a ```setgroups()``` call. The description this issue has the description
```
   This executable is calling setuid and setgid without setgroups or initgroups.
   There is a high probability this mean it didn't relinquish all groups, and
   this would be a potential security issue to be fixed. Seek POS36-C on the web
   for details about the problem.
```
Judging from the code we don't use this to drop privileges. 

This issue has been found in the package review for fedora [here](https://bugzilla.redhat.com/show_bug.cgi?id=1297821)

**Comment by janosvitok** [comment]
Current version of mongoose doesn't have this problem. They don't use setgid/setuid at all.
It seems that they committed on Sept. 8, 2015 quite substancial rewrite (https://github.com/cesanta/mongoose/commit/8927c9d22b3ff9b9bdadabde18b1eb808a4cec16) which is a merge from https://github.com/cesanta/fossa so they lost the intermediate history somehow.

Executive summary: using the latest mongoose release will fix this problem (although there still seems to be the problem of GPLv2 vs. APL...)

**Comment by mcallegari** [comment]
Merging a new version of Mongoose shouldn't be very difficult, however version 6.0 introduced new API breaking the backward compatibility.
Unfortunately at the moment I don't really have time to do the port, so if someone volounteers to do it and test I would really appreciate it.

**Comment by mcallegari** [comment]
Closing this. Mongoose is going to be abandoned
See https://github.com/mcallegari/qlcplus/tree/newweb
