### ISSUE TITLE
Man pages

### ISSUE THREAD

**Issue by daveol** [mcallegari/qlcplus#761]
Add simple man pages for qlcplus and qlcplus-fixtureeditor since they are executable binaries that will be located in ```/usr/bin```

This issue has been found in the package review for fedora [here](https://bugzilla.redhat.com/show_bug.cgi?id=1297821)

**Comment by janosvitok** [comment]
I've added simple man pages: https://github.com/mcallegari/qlcplus/commit/ac9be429f242b0bf8b984c332f87d5c69c4b9a66
They are not installed anywhere, because I'm not sure where do they belong.

**Comment by daveol** [comment]
I think they belong in ```/usr/share/man/man1/``` since they are both section 1 pages because they are both user commands ([reference](http://linux.die.net/man/1/man))

**Comment by mcallegari** [comment]
done

**Comment by daveol** [comment]
solved in a88cfa5 and ac9be42
