### ISSUE TITLE
ArtNet bind error popup prevents QLC+ from starting up

### ISSUE THREAD

**Issue by mcallegari** [mcallegari/qlcplus#794]
I have Capture Argo opened and listening to ArtNet data coming from QLC+ on 127.0.0.1:6454

When I open QLC+, the new error popup message appears. Twice. 
Once when I open QLC+ and once when I open the project to send ArtNet data to Capture Argo.
QLC+ is supposed to send data, so the input binding would be useful only to receive ArtPoll packets.

It is annoying, and moreover it prevents QLC+ to startup.
If this happens on the Raspberry Pi, there's no way to recover from it unless connecting a TV, a mouse and a keyboard to click OK on the popup.

We need to either:
- silently fail without a popup
- investigate the reason why the binding fails and find a proper solution

The current way of dealing with it is not OK for me.

**Comment by plugz** [comment]
> investigate the reason why the binding fails and find a proper solution

Because Capture Argo is already bound to the ArtNet port.


The solution I'd choose is to silently fail without a popup. But in the case of using QLC+ ArtNet input, we won't know when QLC+ is not able to receive ArtNet. (unless having access to the qWarning() logs)


If you're OK with this I'll make the changes.

**Comment by janosvitok** [comment]
Since loopback is 127.0.0.1/8, would it help to use for QLC+ e.g. 127.0.0.2 (user editable loopback address? or at least loopbackaddress override somewhere in the settings)?

**Comment by mcallegari** [comment]
> Because Capture Argo is already bound to the ArtNet port.

Yes, and they haven't opened the socket as "shared"

> The solution I'd choose is to silently fail without a popup. But in the case of using QLC+ ArtNet input, we won't know when QLC+ is not able to receive ArtNet. (unless having access to the qWarning() logs)

Maybe we can add an error message in the plugin line description ?
Something like in the DMXUSB open when the line is "good" or "bad"

> Since loopback is 127.0.0.1/8, would it help to use for QLC+ e.g. 127.0.0.2 (user editable loopback address? or at least loopbackaddress override somewhere in the settings)?

I would avoid to add more options that can cause more issues and confusion. In any case QLC+ wouldn't be able to receive polls from the ArtNet node keeping the socket busy.
