### ISSUE TITLE
Audio input changes regression

### ISSUE THREAD

**Issue by mcallegari** [mcallegari/qlcplus#795]
As reported by @sbenejam here http://www.qlcplus.org/forum/viewtopic.php?f=12&t=9556&p=41999

@plugz: I went back in the GIT history and found that PR #757 caused it.

Basically, in the current code, this call  https://github.com/mcallegari/qlcplus/blob/master/engine/audio/src/audiocapture_qt.cpp#L132 always returns 0 bytes available. Commenting it seems to make the capture working.
However, even the call https://github.com/mcallegari/qlcplus/blob/master/engine/audio/src/audiocapture_qt.cpp#L135 always returns that 0 bytes have been read.

I've seen this kind of things before, and the explanation I gave myself is that QtMultimedia is crap.
It is VERY sensitive to threads and if you create an instance in one thread, you cannot use it in another thread, OR, it shows weird behaviour like the above.

Needless to say that this has to be fixed before 4.10.3.

**Comment by plugz** [comment]
http://stackoverflow.com/questions/9664309/qaudioinputbyteready-and-qiodeviceread-giving-different-number-of-bytes

fix will come tonight

**Comment by mcallegari** [comment]
As I feared...audio input is not working anymore on OSX :disappointed:

**Comment by plugz** [comment]
OK I'm on it

**Comment by plugz** [comment]
What's the output after this ? Is it 

```
[QT readAudio]  0 bytes read -> ( 7464 / 8192 )
```

forever ?

**Comment by mcallegari** [comment]
> forever ?

yes

Basically you cannot force Apple to do what you want. They tell you what to do.
In my previous code I was requesting: m_input->read((char *)m_audioBuffer, maxSize * 2);
And this still works. (just tested)

Your code requests a number of bytes that the Apple driver cannot provide (bufferSize - m_currentBufferPosition)...at some point forever.

Can we revert to my code ? Is there any specific reason why you wanted to change it ?

**Comment by plugz** [comment]
I explained the reasons for the change in #796.

A fix is on the way, wait for 30 minutes :)

**Comment by mcallegari** [comment]
> I explained the reasons for the change in #796.

We talked about start/stop and threads...not why we needed a buffer with an offset

**Comment by plugz** [comment]
because bytesAvailable() and bytesReady() are not reliable, so we have to call read() several times until the buffer has been filled.

**Comment by mcallegari** [comment]
Ok, got it, but the check m_currentBufferPosition == bufferSize is too strict.
It should be m_currentBufferPosition >= bufferSize, with the handling of the exceeding bytes, in case

**Comment by plugz** [comment]
The check is good, the issue is QAudioInput refusing to read less that 3k bytes.

> It should be m_currentBufferPosition >= bufferSize, with the handling of the exceeding bytes, in case

Yes, if we try to please QAudioInput.



A cleaner solution is on the way, I'm compiling and testing right now

**Comment by plugz** [comment]
I pushed directly on the master branch, can you test ?

**Comment by mcallegari** [comment]
It works.
Would be nice to avoid the memcpy if possible.

In the meantime I attemped something like this: http://pastebin.com/qnKiktwn
but with m_audioBuffer twice the size when allocated

**Comment by mcallegari** [comment]
and for the record, if you want to laugh, on OSX this message appears when starting audio capture:

2016-02-17 22:02:45.688 qlcplus[42807:94651] 22:02:45.688 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.

Like always...I have no words...

**Comment by mcallegari** [comment]
And the current code doesn't work on Windows.
Debug messages seem to be OK, but the audio triggers bars don't move :disappointed:

**Comment by plugz** [comment]
> with my Sennheiser headphones (with mic) audio trigger bars don't move. Debug messages seem to be ok though.

Are you sure it's not a volume settings issue ?

**Comment by mcallegari** [comment]
Of course I've tested it before with the Windows monitor :)

Alright, let's close this for now. Thanks for the help David !
