### ISSUE TITLE
VCXYPad EFX preset crash

### ISSUE THREAD

**Issue by mcallegari** [mcallegari/qlcplus#799]
As reported here: http://www.qlcplus.org/forum/viewtopic.php?f=5&t=9594

I think this is related to the new Function start/stop mechanism.
XYPad EFX is a special case, cause the EFX is a temporary copy of the project EFX, that gets deleted when the user requests to stop it [here](https://github.com/mcallegari/qlcplus/blob/master/ui/src/virtualconsole/vcxypad.cpp#L629)

The crash happens [here](https://github.com/mcallegari/qlcplus/blob/master/engine/src/mastertimer.cpp#L248) and most likely it is a thread related thing, cause MasterTimer refers to a pointer freed by VCXYPad

@plugz  ideas ?

**Comment by mcallegari** [comment]
Callig m_efx->stopAndWait() seems to solve the crash, but I don't know if it is the proper way to go.

**Comment by plugz** [comment]
> Calling m_efx->stopAndWait() seems to solve the crash, but I don't know if it is the proper way to go.

It's a good solution for now, but someday the efx copy will have to disappear
