### ISSUE TITLE
Slider ignores fade out time of scene when in playback mode

### ISSUE THREAD

**Issue by JonBlackwell** [mcallegari/qlcplus#81]
When a slider is set to playback mode, and a scene is attached, increasing the value will honor the fade in time set on the scene. However, when decreasing the value, the scene will jump immediately to the value of the fader and ignore the fade out time of the scene.

**Comment by plugz** [comment]
Fixed by 56fd32bb5058fd926be0e5bf7d1c42dc66d71a46

The fade in time is ignored when a function is started by a VCSlider.
The fade out time is ignored when a function is stopped by a VCSlider.

Discussed here: http://qlcplus.org/forum/viewtopic.php?f=5&t=9228
