### ISSUE TITLE
Nested solo frames not working as expected

### ISSUE THREAD

**Issue by fourbytes** [mcallegari/qlcplus#812]
I'm trying to use nested solo frames to have either 2 moving heads controlled individually or them both controlled together and as can be seen in the example gif below, when selecting either individually it disables any button that controls both but does not work vice versa.

http://g.recordit.co/yeERcqZ4DO.gif

**Comment by plugz** [comment]
I don't see any issue with solo frames here.

When you click on a button, it will look for the nearest solo frame behind the button.
Then every other button contained in this solo frame an its children will be disabled.

If you want a solution for your needs, please post in the forum: http://qlcplus.org/forum/

And attach an example workspace.

Thank you.
