### ISSUE TITLE
Linux/Qt4 - Audio decoder plugins not loaded in release mode

### ISSUE THREAD

**Issue by mcallegari** [mcallegari/qlcplus#820]
Tested on Ubuntu 14.04 64bit.
The plugins files are installed correctly and looked up in the right place, but printing the QPluginLoader errorString gives this:
"Plugin verification data mismatch in '/usr/lib/x86_64-linux-gnu/qt4/plugins/qlcplus/audio/libmadplugin.so'" 
"Plugin verification data mismatch in '/usr/lib/x86_64-linux-gnu/qt4/plugins/qlcplus/audio/libsndfileplugin.so'" 

This happens with Qt4. I haven't check on Qt5 yet.
Apparently there is no issue on Windows and OSX releases.

A bit of help is appreciated.

**Comment by kripton** [comment]
I can confirm that I'm unable to load audio files (tested: flac, mp3, wav) when using Qt4 on Linux. No error on the console. I'll try Qt5 when compilation is done ;)

**Comment by kripton** [comment]
Using Qt5, the audio files are opened correctly (flac, wav and mp3). However, I've had another issue using Qt5 which works using Qt4. I'll open a separate issue.

**Comment by mcallegari** [comment]
Fixed by f2f994a89874ef85b04d1c84df0f04b08e4e1653
