### ISSUE TITLE
RGB Matrix with generic dimmers

### ISSUE THREAD

**Issue by mcallegari** [mcallegari/qlcplus#827]
Opening this so it doesn't get forgotten
As explained by @janosvitok here: http://www.qlcplus.org/forum/viewtopic.php?f=5&t=8088&start=10#p42488

When creating a RGB matrix with generic dimmers, the bahaviour is not correct, as all the heads go to 100% intensity.

This is because the RGB Matrix function doesn't handle properly the intensity channel. We need to add an extra check for generic dimmers.

**Comment by janosvitok** [comment]
https://github.com/janosvitok/qlcplus/tree/rgbmatrix-dimmer is working code for this problem. TODO: tests.
