### ISSUE TITLE
Special scene

### ISSUE THREAD

**Issue by mihaiandrei1489** [mcallegari/qlcplus#830]
I come up with the idea of adding a very useful feature ..
often used are many forms fixtures (moving heads or LED) of the same type so when you want to make a function associated with that fusion for almost all do before to turn them on ...
and if you have 8 moving heads with a single effect do they move all together and one slider opens the dimmer of all, and so far so good ..
Now if I make a fixed scene with 2 or 4 heads can not act on the dimmer because the slider that turns every head and lit ..
then pointing is always on with no adjustable lights from that scene that I have set up ...
it is feasible to introduce a type scene function with high priority or chess ... important?

For discussions, feedbacks, ideas and new fixtures, go to:
http://www.qlcplus.org/forum/index.php

Before reporting new issue, please discuss it on the forum. Let's keep the issues tidy!

**Comment by mcallegari** [comment]
> Before reporting new issue, please discuss it on the forum. Let's keep the issues tidy!

Did you read it ??

This area is reserved to developers. Please use the forum.
