### ISSUE TITLE
Virtual console frame: size resets when properties are edited

### ISSUE THREAD

**Issue by plugz** [mcallegari/qlcplus#835]
Steps to reproduce:

- Create a frame in the Virtual Console
- Resize it
- Open its properties
- Click "OK" in the properties dialog
-> The frame goes back to its original size

Forum post:
http://qlcplus.org/forum/viewtopic.php?f=5&t=9752&p=42822

**Comment by plugz** [comment]
https://github.com/mcallegari/qlcplus/commit/075d05ee0657a73ef74df47ec296ed55fdd22623#diff-9d3bf91cd0d096946d2609967398f462R774

This seems to be the faulty line.
I don't know what purpose is serves so I'm not going to touch anything.

**Comment by mcallegari** [comment]
I think I know what that is.
A Frame can have (or not) a header. When multipage mode is on, the header must be shown.
Most likely that resize was added to correctly repaint the header stuff.
I think the call is correct. Probably the fix has to be done on m_width and m_height. They have to be updated on a resize event, which is handled here
https://github.com/mcallegari/qlcplus/blob/master/ui/src/virtualconsole/vcwidget.cpp#L1342

**Comment by mcallegari** [comment]
Fixed by eff388715d42b58dc7a32c6a97f6114717eaf10a
