### ISSUE TITLE
QLC+ 4.10.3 crashes via web interface

### ISSUE THREAD

**Issue by susobaco** [mcallegari/qlcplus#841]
Hi.
Hi, I'm using qlc in Trisquel (Gnu-Linux based on Ubuntu trutsy) and version 4.9.1 does not give me problems. But, when you install any version 4.10, installed from the repository opensuse, when handling the program from the Android browser, the first time you open the browser, it works bie, but segunada, close the program. I can not install qlcplus-qt4-dbg because it asks me qlcplus 4.10 I can not install. Thank you.

**Comment by mcallegari** [comment]
1- ubuntu TRUSTY
2- version 4.10.what ?
3- qlcplus-qt4-dbg is a dummy (empty) package and should not be installed
4- how can we reproduce the issue ? Where's the workspace to reproduce ? What do you do to make QLC+ close ? 
5- Which Android version are you using ?

It was probably better is you used the forum instead of coming directly here...
This isssue report is incomplete as usual

**Comment by susobaco** [comment]
Sorry, my English is very bad. I beg your pardon. The problem is with all versions 4.10. With versions 4.9 works perfectly. I meant that, with version 4.10 the first time you connect from the android (kit kat) web browser works well. If I close the browser and try again to enter the web control, the program closes giving a violation segment.
If you wish, I can write the bug in the forum.
Thank you very much for your time

**Comment by mcallegari** [comment]
Not reproduced.
I have just done some tests with the Android 6.0.1 stock browser and had no issue at all.
I left the browser in background for a few minutes and then resumed it. Everything was still working.

So I need more details of what you exactly do to see the issue.

**Comment by susobaco** [comment]
Hello, I share with you two videos, one with and another version 4.9 with version 4.10, reproducing the problem:
https://cloud.openmailbox.org/index.php/s/RrJwD5rnluc8FNQ
https://cloud.openmailbox.org/index.php/s/SoGtHwCxpY3eDDF

**Comment by mcallegari** [comment]
OK thanks. I've tried to reproduce again, but I am really not able.
I am starting to suspect it depends on how the browser handles websockets.
I tried with an old 4.1.1 android tablet that I have and I couldn't do nothing with the stock browser.
Chrome instead works perfectly.

So, can you please try with Chrome and tell me if it works ?

**Comment by mcallegari** [comment]
Update: as a few users reported crash issues using iOS, I gave it a try and finally reproduced them !
There's a bunch of issues and I need to understand what's going on.

This indeed depends on how mobile OSes send applications to background, which is something that doesn't happen on PCs

**Comment by mcallegari** [comment]
This should be fixed by 75c9fc151312961edae6462f9a728d3e06157ef8
@susobaco can you please try a -git version from OBS and tell me if it works for you ? Thanks

**Comment by mcallegari** [comment]
Wow. Closed.

**Comment by susobaco** [comment]
Sorry, I had not read the message. A git version, uff, I have to compile, I try to do next week. Thanks for your job

**Comment by mcallegari** [comment]
You don't have to compile anything.
You opened this issue using a OBS version, then use a OBS GIT version !

https://software.opensuse.org/download.html?project=home%3Amcallegari79&package=qlcplus-qt4-git
https://software.opensuse.org/download.html?project=home%3Amcallegari79&package=qlcplus-qt5-git

**Comment by susobaco** [comment]
Ok, I had not seen Oh, thank you very much ... I've tried it and it works perfectly. Good job!
