### ISSUE TITLE
Script systemcommand: "arg" can be replaced with anything

### ISSUE THREAD

**Issue by plugz** [mcallegari/qlcplus#844]
When writing a systemcommand line in a script, passing args is done like this:

systemcommand:ls arg:-l

but it's currently possible to write this:

systemcommand:ls hi:-l

and "-l" will be passed as an argument to the command.

Like the doc suggests, "arg" should be the only way of passing args.

**Comment by mcallegari** [comment]
There should be a filter here, to discard unknown keywords
https://github.com/mcallegari/qlcplus/blob/master/engine/src/script.cpp#L752
