### ISSUE TITLE
Function Tree Widget crash

### ISSUE THREAD

**Issue by mcallegari** [mcallegari/qlcplus#848]
As reported here: http://www.qlcplus.org/forum/viewtopic.php?f=22&t=9933

With the shared example project it is easy to reproduce the issue.
The assert happens here: https://github.com/mcallegari/qlcplus/blob/master/ui/src/functionstreewidget.cpp#L192

I noticed that it happens only when "Chasers" are enabled as function filter in the function selection dialog

**Comment by plugz** [comment]
A patch is on the way

**Comment by plugz** [comment]
Here:

https://github.com/plugz/qlcplus/tree/fix-functionstreewidget-crash

Waiting for Travis' approval to push to the master branch.

**Comment by plugz** [comment]
Fixed by f59de8995df4a682dea43acf65e108159d69d55c
