### ISSUE TITLE
patch need on plugins/dmxusb/src/dmxusbwidget.h

### ISSUE THREAD

**Issue by gilbsfr24** [mcallegari/qlcplus#869]
If no defined(FTD2XX) ||  defined(LIBFTDI) || defined(LIBFTDI1) || defined(QTSERIAL)
I have got and undefined type for DMXInterface

Index: dmxusbwidget.h
===================================================================
--- dmxusbwidget.h	(revision 4391)
+++ dmxusbwidget.h	(revision 4392)
@@ -21,6 +21,8 @@
 #ifndef DMXUSBWIDGET_H
 #define DMXUSBWIDGET_H
 
+#include "dmxinterface.h"
+
 #if defined(FTD2XX)
   #include "ftd2xx-interface.h"
 #endif

**Comment by mcallegari** [comment]
What kind of issue report is this ??
You haven't even stated which compiler (and version) and which OS you are building on.

QLC+ builds on 13 different OS targets and none of them have the issue you encountered.

Please provide the required details or I'll close this.

**Comment by gilbsfr24** [comment]
Sorry I dont know how to explain.
When I compile on windows with Qt Creator 4.0 with Qt 5.5.1minGw 32Bits;

I dont need qtserial nor FTD2XX
then FTD2XX, LIBFTDI, LIBFTDI1 and QTSERIAL a undefined
and then the DMXInterface type definition is not included 
So I have got an error

E:\qlcPlus.dev\qlcplus-4.10.3\plugins\dmxusb\src\dmxusbwidget.cpp:24: In file included from ..\..\..\..\qlcplus-4.10.3\plugins\dmxusb\src\dmxusbwidget.cpp:24:0:
E:\qlcPlus.dev\qlcplus-4.10.3\plugins\dmxusb\src\dmxusbwidget.h:46: erreur : expected ')' before '*' token
     DMXUSBWidget(DMXInterface *interface, quint32 outputLine);
                               ^
E:\qlcPlus.dev\qlcplus-4.10.3\plugins\dmxusb\src\dmxusbwidget.h:66: erreur : 'DMXInterface' does not name a type
     DMXInterface* interface() const;
     ^
I hop it will help

**Comment by mcallegari** [comment]
Windows build instructions are here. I suggest you to follow them. Anything else is unsupported:
https://github.com/mcallegari/qlcplus/wiki/Windows-Build-Qt5

> I dont need qtserial nor FTD2XX
> then FTD2XX, LIBFTDI, LIBFTDI1 and QTSERIAL a undefined

What does that even mean ? The DMXUSB plugin is built by default and on Windows you need to have the D2xx SDK installed. If you don't need the plugin at all, just comment it in the plugins.pro file, as explained in the wiki above
