### ISSUE TITLE
Midi loosing links when editing on another computer

### ISSUE THREAD

**Issue by imayoda** [mcallegari/qlcplus#878]
Hi there, I'm new to this awesome program but maybe it's good for you to know about this behavior.
Last night I was editing a project I've recently made for a friend on a mac (basic dmx fixtures controlled by midi keyboard).. I was editing the perfectly working setup (just to add some new fixtures) on a windows pc with no midi hw attached. 
Saved that, and transferred the file to my friend's mac, just in time to find that midi channels linked in the first version were lost after I modified the project on the "alien" pc. Had to re-link them all.
Not a big real problem indeed, but should be easy to cure in future.
Kudos to you :)

**Comment by mcallegari** [comment]
Hi, this area is meant mainly for developers.
Please use the forum like everyone else, and report exactly all the details to understand and reproduce the issue, including a sample test project to speed up the analysis.
