### ISSUE TITLE
qmlui fails to build (qlcplus/qmlui/functionmanager.cpp:228: undefined reference to `Video::Video(Doc*)')

### ISSUE THREAD

**Issue by kripton** [mcallegari/qlcplus#901]
Hi, just out of curiosity I tried building the qmlui and it failed to link:

> cd qmlui/ && ( test -e Makefile || /usr/lib64/qt5/bin/qmake /home/kripton/dmx/qlcplus/qmlui/qmlui.pro 'CONFIG += qmlui' -o Makefile ) && make -f Makefile 
> make[1]: Entering directory '/home/kripton/dmx/qlcplus/qmlui'
> g++ -Wl,-rpath-link,/usr/lib64 -o qlcplus-qml main.o app.o audioeditor.o actionmanager.o chasereditor.o collectioneditor.o contextmanager.o fixturebrowser.o fixturemanager.o functioneditor.o functionmanager.o inputoutputmanager.o listmodel.o mainview2d.o mainviewdmx.o modelselector.o previewcontext.o rgbmatrixeditor.o sceneeditor.o showmanager.o treemodel.o treemodelitem.o virtualconsole.o vcwidget.o vcframe.o vcsoloframe.o vcpage.o vcbutton.o vclabel.o vcslider.o vcclock.o qrc_qmlui.o qrc_svgicons.o qrc_fonts.o moc_app.o moc_audioeditor.o moc_actionmanager.o moc_chasereditor.o moc_collectioneditor.o moc_contextmanager.o moc_fixturebrowser.o moc_fixturemanager.o moc_functioneditor.o moc_functionmanager.o moc_inputoutputmanager.o moc_listmodel.o moc_mainview2d.o moc_mainviewdmx.o moc_modelselector.o moc_previewcontext.o moc_rgbmatrixeditor.o moc_sceneeditor.o moc_showmanager.o moc_treemodel.o moc_treemodelitem.o moc_virtualconsole.o moc_vcwidget.o moc_vcframe.o moc_vcsoloframe.o moc_vcpage.o moc_vcbutton.o moc_vclabel.o moc_vcslider.o moc_vcclock.o   -L../engine/src -lqlcplusengine -lQt5Quick -lQt5Svg -lQt5MultimediaWidgets -lQt5Widgets -lQt5Multimedia -lQt5Gui -lQt5Qml -lQt5Network -lQt5Core -lGL -lpthread 
> functionmanager.o: In function `FunctionManager::createFunction(int)':
> /home/kripton/dmx/qlcplus/qmlui/functionmanager.cpp:228: undefined reference to `Video::Video(Doc*)'
> collect2: error: ld returned 1 exit status

If it's temporary and work in progress, feel free to close. I just thought I'd mention it here

**Comment by mcallegari** [comment]
Which Qt version ?
qmlui should build from around Qt 5.5.x and above.
The requirement though will be set to Qt 5.7 if not 5.8

**Comment by kripton** [comment]
Indeed, "make distclean" makes the build error vanish. Sorry for the noise
