### ISSUE TITLE
[MacOS] Cannot access virtual MIDI ports

### ISSUE THREAD

**Issue by bome** [mcallegari/qlcplus#907]
Hi, users of my software, which allows to create virtual MIDI ports, have reported that QLC+ does not work with those virtual MIDI ports. All other MIDI applications do. Looking at the source code of QLC+, I have found that the MIDI device discovery has a number of problems, causing virtual ports to not be listed:

looking at plugins/midi/macx/coremidienumerator.cpp  version 81b9dcd on 16 Dec 2013:

1) line 105: MidiEnumeratorPrivate::rescan()
This method iterates Devices, then Entities, then Endpoints (Source/Destination).
However, the Apple documentation says:
> Note: If a client iterates through the devices and entities in the system, it will not
> ever visit any virtual sources and destinations created by other clients.  Also, a
> device iteration will return devices which are "offline" (were present in the past but
> are not currently present), while iterations through the system's sources and
> destinations will not include the endpoints of offline devices.
> 
> Thus clients should usually use MIDIGetNumberOfSources, MIDIGetSource,
> MIDIGetNumberOfDestinations and MIDIGetDestination, rather iterating through devices and
> entities to locate endpoints.

Therefore, the rescan() method should be changed to iterate the Sources and Destinations.

2) Dependency on UniqueID
The rescan() method fails for a MIDI port if its Entity does not provide a UniqueID. After being fixed using the above proposal, the UniqueID should be retrieved from the Endpoint (the source/destination object) if there is no Entity for the Endpoint.

3) Using model name as MIDI port name
CoreMIDI provides 3 names for a MIDI object: the name, the model, and the DisplayName. Apple  recommends to use the DisplayName for display to the user (using kMIDIPropertyDisplayName). Only if the DisplayName is not available (e.g. OS X 10.4 or earlier), use the Model. It might be worthwhile to display the Name + Model -- unless the Model already contains the Name. Note that with the fix from 1) above, you should get the DisplayName/Model/Name from the Endpoint and not the Entity.

I can provide more info if needed. Thanks for considering.

**Comment by mcallegari** [comment]
> Hi, users of my software
...which is... ?

>  looking at plugins/midi/macx/coremidienumerator.cpp version 81b9dcd on 16 Dec 2013:
It's 2016 here...and by the way you're talking about MacOS device scan only. Might be worth to mention it in the issue title, since MacOS is not the only OS supported by QLC+

> I can provide more info if needed. Thanks for considering.
Please provide some quick instructions to check the issue and then I'll have a look at the Apple docs and find a solution which work for every device.
I am not a MacOS expert, so I need a few indications how to create these virtual MIDI ports and how to check they exist in MacOS and they don't get listed in QLC+.

Thanks

**Comment by bome** [comment]
Thanks for the quick reply and for fixing the title. ("2013" is the date of the given (latest) git revision of coremidienumerator.cpp)

The software in question is [Bome MIDI Translator Pro](http://www.bome.com/products/miditranslator). You can use the demo version for testing the virtual MIDI ports. The current version 1.8.1 does not set the _Model_ property, only the _Name_. Go to Settings, Virtual MIDI, and make sure virtual MIDI ports are enabled with at least one pair of virtual ports. Then, e.g. the port "Bome MIDI Translator 1" should exist in 3rd party MIDI applications, as can be seen e.g. in Garage Band or MIDI monitor.

The cited Apple spec comment is here: [MIDIGetDevice()](https://developer.apple.com/reference/coremidi/1495368-midigetdevice).

It's very easy for me to fix the QLC+ code (and request to push it to the QLC+ repository), but I assume it's not so straight forward for me to build and test QLC+... Is there a minimal build for just this plugin available?

**Comment by mcallegari** [comment]
> It's very easy for me to fix the QLC+ code (and request to push it to the QLC+ repository), but I assume it's not so straight forward for me to build and test QLC+... Is there a minimal build for just this plugin available?

Unfortunately there isn't. The build instructions are here: https://github.com/mcallegari/qlcplus/wiki/OSX-build-Qt5

Thanks for offering to fix the code, however if you can kikndly share some code snippet showing the "good" way of scanning for MIDI devices on MacOS, I think I can manage to do some fix faster.
Otherwise I'll start from the links you provided (thanks) and do some tests myself. 
I have plenty of MIDI devices that I can check

**Comment by bome** [comment]
cool, I'll post the code here in the next days.
Thanks

**Comment by mcallegari** [comment]
Done. However, before committing the code I need to address/understand two things:
1- I always get a source and a destination endpoint from each device, even Bome. I tried to open/close in/out ports and nothing changes on QLC+ side. Is that expected ?
2- MIDI hotplug doesn't work anymore. Apparently, MacOS sends the USB plug event too early and when I perform the rescan, the new device is not listed yet

I any case, attached the modified version of the MIDI plugin. You need to place it in a QLC+ bundle, in the path QLC+.app/Contents/PlugIns
[libmidiplugin.dylib.zip](https://github.com/mcallegari/qlcplus/files/613827/libmidiplugin.dylib.zip)

**Comment by bome** [comment]
Thanks!
Separate endpoints for IN and for OUT are expected.
It would surprise me if the order of gathering the endpoint list makes a difference for hotplugging. In my code, device scan is performed 200ms after the OS hotplug event from the OS, and then after 7 seconds again (to be sure).

I cannot easily try the binary, but I'd like to review coremidienumerator.cpp if you can post your modified version (or point to your cloned repository)?

**Comment by mcallegari** [comment]
> device scan is performed 200ms after the OS hotplug event from the OS, and then after 7 seconds again (to be sure).

Seems like trying some luck instead of doing the proper way. If I block the scan for some time, the MIDI plugin would delay the hotplug of other plugins, and maybe the user didn't actually plug a MIDI device

> I cannot easily try the binary, but I'd like to review coremidienumerator.cpp if you can post your modified version (or point to your cloned repository)?

You just need to download QLC+ and replace a file. What's the hard part in that ? :stuck_out_tongue_closed_eyes: 
I am the owner of the repository...I don't work on clones :smiley: 
Anyway, I'll commit the changes once I find a proper solution for hotplug

**Comment by bome** [comment]
Thanks for the further info. 

> Seems like trying some luck instead of doing the proper way. If I block the scan for some time, the MIDI plugin would delay the hotplug of other plugins, and maybe the user didn't actually plug a MIDI device

No, there are race conditions difficult to prevent. My scheme is the result of a lot of testing many different scenarios -- which can happen in live situations. For example, rapidly plugging out + in different devices, or dozens of devices at once (by plugging in a hub), and so on. Usually, after 200ms, the list as provided by the OS is correct, but every once in a while, it would be inconsistent. Therefore the "after burner" after a few seconds. I don't say it's the only robust scheme, but it is one.

And of course, the delayed device scan is performed asynchronously without blocking. If multiple callbacks come in during 200ms, only the last callback + 200ms will trigger the rescan.

**Comment by mcallegari** [comment]
Should be fixed by 1c0de7c06dee02f1e0126f63742d764b6fe109ee
Complete test version [available here](http://www.qlcplus.org/downloads/test/QLC+_4.10.5-TEST-20161129.dmg)

In the end, there's no need to use magic numbers for hotplugging like you did.
When you create your MIDI client, you can register a callback and MacOS MID core will notify you about changes on devices.
See here: https://github.com/mcallegari/qlcplus/blob/master/plugins/midi/macx/coremidienumerator.cpp#L46
So I've disabled the main QLC+ hotplug call on the MIDI plugin (only for MacOS) and used the  kMIDIMsgObjectAdded and kMIDIMsgObjectRemoved message IDs

**Comment by bome** [comment]
Hi, thanks. I've reviewed your fix and it looks OK. I have not tested the binary, sorry.

My bad that I did not ask if you actually use a MIDIClientCreate callback for triggering rescan(). Because rescan() was called from outside, I assumed you are using a separate MIDIClient for hotplug events as I do in my code base.

Directly rescanning endpoints from within the callback works fine in general -- I assume that pretty much all CoreMIDI apps work like that. But as indicated, I have been able to produce conditions where the resulting endpoint list is inconsistent. Then, only the next rescan will fix the list.

**Comment by mcallegari** [comment]
Alright, closing this for now.
If you can gather feedbacks from your users using both QLC+ and BMT, please report here.
If there are still issues, we'll reopen this
Thanks

**Comment by mcallegari** [comment]
Alright, closing this for now.
If you can gather feedbacks from your users using both QLC+ and BMT, please report here.
If there are still issues, we'll reopen this
Thanks

**Comment by bome** [comment]
perfect. A user indicated he wanted to try the binary you've posted above, I'll report here.
Thanks a lot for the quick turn-around.

**Comment by bome** [comment]
test result from that user:
the virtual ports of BMT are now visible in the port list of QLC+. However they still can't be used as they appear to have a "closed" status as input ports, at all times regardless of what I do.
The IAC port, for example, appears to be closed but when I select it as a QLC+ input it changes status into "open", however the virtual ports change status to "open" only as output ports (e.g., when selected as "feedback" ports) but not as input ports.
The same virtual ports can function perfectly if for example I select them as input ports for other programs, like Ableton Live, but in QLC+ they refuse to function as viable input ports.

**Comment by bome** [comment]
Hi, any news on this? While the ports appear in the port list in QLC+, it seems that they cannot be used.

Looking at the QLC+ source, I see that while you're enumerating endpoints, only the _entity_ reference is stored in the respective CoreMidiInputDevice/CoreMidiOutputDevice instances. I recommend to store the _endpoint_ reference instead. For CoreMidiInputDevice:

- remove `m_entity` without replacement
- in the constructor, replace `MIDIEntityRef entity` with `MIDIEndpointRef source`, and initialize m_source with it
- in `CoreMidiInputDevice::open()`, remove the line `m_source = MIDIEntityGetSource(m_entity, 0);`

and of course the equivalent for `CoreMidiOutputDevice`.

Thanks,
Florian

**Comment by mcallegari** [comment]
Sorry but I totally missed your post 11 days ago ! GitHub didn't send me a notification, but today it did.
Pity that I missed it cause in the meantime I have released a new version of QLC+.

I definitely need to test this myself, but I don't know your software enough and I kind of hate macOS.
Do you have an online wiki or manual that I can look at ?
I guess the simplest test is connecting a MIDI controller to your software and forward events through a virtual port. Is that feasible without spending a whole day on the Apple nightmare ? :laughing:

**Comment by bome** [comment]
Hi, thanks a lot for the ultra-fast turnaround. I'll ask my users to check it out.

**Comment by mcallegari** [comment]
@bome any feedback yet ?

**Comment by bome** [comment]
In general, it works now. The only problem is for feeding MIDI from MT to QLC+, if there are multiple MIDI messages in one CoreMIDI event packet (as is possible), only the first MIDI message is considered by QLC+. 

I hesitated to report this, because it's not necessarily a general problem. Most hardware and software only ever sends one MIDI message per CoreMIDI event packet. With MT, however, it is possible to do so, and my customer does it.

This can be fixed in MT Pro (i.e. split up multiple messages to as many event packets). We will do that in a future version, because it has the potential to make it more interoperable with "simple" 3rd party software.

It's also possible for you to fix it in QLC+: parse the incoming event packets, and split up by MIDI message. It's not particularly hard, just inspect the event packet byte by byte, and wherever the high bit is set (byte value >= 128), a new MIDI message begins. For a full implementation, there are some MIDI oddities to consider, in particular running status and interspersed realtime messages. Fragmented messages, i.e. one message spanning multiple event packets, also occur with CoreMIDI.

Season's greetings!

Thanks,
Florian

**Comment by mcallegari** [comment]
Alright ! Thanks for the feedback.
I'd say for now we can close this issue report and eventually open a new one for parsing multiple packets on macOS.
However i've got higher priority issue to tackle these days :)

Have a happy Christmas
