### ISSUE TITLE
[Linux] DMX Input from Enttec USB Pro MK2 does not work

### ISSUE THREAD

**Issue by nkaminski** [mcallegari/qlcplus#912]
After updating to 4.10.4 to 4.10.5a, DMX input from my Enttec DMX USB Pro MK2 no longer works. I have also tested with both the Qt4 and Qt5 Git builds and this issue is present on all current builds after 4.10.4. QLC+ reports that the device is operating correctly, even while this issue is occurring, and that the driver in use is libftdi. DMX output works but is not particularly reliable, with the lights/interface occasionally no longer responding to QLC+ after it has been running for some time. I am running Ubuntu 16.04, fully updated at the time of opening this issue. Downgrading back to 4.10.4 fixes both issues, therefore this appears to be a regression in 4.10.5a. Also, I have removed the ~/.config/qlcplus folder when switching between versions as well.

**Comment by mcallegari** [comment]
I understand you might have encounter an issue, but I don't quite understand why everybody is ignoring the message that is displayed when opening a new issue.

Where is the related forum discussion to your issue report ?
Where are the debug messages supposed to help us resolving the issue ?
Saying "does not work" doesn't help much, does it ?
Same goes for "is not particularly reliable". Doing what ? After how long ? How many channels ? How many universes ? Debug messages ?
