### ISSUE TITLE
vcmatrix not sending feedback data

### ISSUE THREAD

**Issue by enbyted** [mcallegari/qlcplus#913]
It appears that the rgb matrix control widget is not sending feedback data to it's custom controls. 
Or rather it's sometimes sending them (I found only one case - when starting live mode).

I've never done anything with Qt before or done any major changes in QLC+ itself. However after some debugging and trying different approches it seems that adding `updateFeedback()` call in the end of `slotUpdate()` is sufficient to fix this issue.

It looks like the update timer is started after every change. 

I've seen this issue in 4.10.5 and current (751fef4499ec0ea7085754202c421ef67de1cc57) git version. I haven't tried earlier versions.

**Comment by mcallegari** [comment]
Hi, thanks for reporting.
Your observation makes sense, but to test the change myself, I would appreciate a simple test project to speed up the task, and the steps to reproduce the issue you noticed.
Thanks

**Comment by enbyted** [comment]
I don't know how to properly setup feedback through loopback interface and I have no idea what device you would be using to test it. Thus it would not be easy for me to provide a test project.

Reproduce with:

- Given a midi device setup as input and feedback in 'Universe 1'
- Given 2 or more RGB fixtures grouped in fixture group 'Group 1'
- Given a RGB matrix function set to fixture group 'Group 1' named 'RGB matrix'
- Given a Animation widget in Virtual Console connected to 'RGB matrix' named 'Animation 1'
- Given that the 'Animation 1' widget has 2 different presets conneted to external input from 2 different midi device's buttons that have LEDs or some other visual feedback on the same note as the button itself
- Given that you enter 'operate mode'
- Given that you press one of the buttons then the other
- You would expect the buttons to properly light up when you press them and turn light off under the other
- In current version the lights either don't light up at all
- OR only one of them lights up when entering operate mode
- OR they all light up when pressed, but the others don't turn off

If you point me to some documentation on how to properly setup a buttons with feedback with loopback interface or provide me information on hardware you would be using I will gladly proide a test project.

**Comment by mcallegari** [comment]
Should be fixed now. I've also done more. It is now possible to use custom feedbacks for presets.
Tested with an AKAI APC Mini
