### ISSUE TITLE
Web console password protection

### ISSUE THREAD

**Issue by enbyted** [mcallegari/qlcplus#933]
It would be nice if there was an option to protect web console with basic auth, nothing fancy and really secure - just to stop curious eyes.

I'll work on in, but would love to hear comments from others - how would you see it in the web ui?

My personal rationale: I'm using QLC+ in my company for controlling architectural lighting and web console is great tool for that. More often than not clients put these drivers in the same network that clients can access, that creates a risk that someone might try to be funny and for example changes the IP address or plays with simple desk. I would live it if it made it's way into master, cause I don't really have the time to figure out ARM builds myself.

**Comment by siegmund42** [comment]
Such a feature would be great. But still in most cases the user don't want authentication by default so it should be adjustable somewhere - maybe another command-line-parameter?
Maybe it could be done by configuration of the web server (I don't know how the web server is implemented at the moment) to require an authentication.

**Comment by enbyted** [comment]
I though about adding tab in settings that would allow setting of username and password and if they are empty don't require authentication.

I like the idea of overriding credentials from command line, might be useful.

**Comment by mcallegari** [comment]
Sorry, but I have no plans in taking an adventure through this.
And by the way, as explained before, features request go through the forum, not here

**Comment by mcallegari** [comment]
Implemented by #980 ! :+1:
