### ISSUE TITLE
MIDI faders do not reach 100%

### ISSUE THREAD

**Issue by janosvitok** [mcallegari/qlcplus#938]
See QLC+ Forum [discussion](http://www.qlcplus.org/forum/viewtopic.php?f=7&t=10787).

Most probably CHAR_MAX == UCHAR_MAX == 255 for Raspberry.

TODO: Change [this line](https://github.com/mcallegari/qlcplus/blob/master/plugins/midi/common/midiprotocol.h#L91) to read
`#define MIDI2DMX(x) uchar((x == SCHAR_MAX) ? UCHAR_MAX : x << 1)`
or simply
`#define MIDI2DMX(x) uchar((x == 127) ? 255 : x << 1)`

or
`#define MIDI_MAX_VALUE 127; #define DMX_MAX_VALUE 255`

**Comment by mcallegari** [comment]
@janosvitok please re-enable the MIDI plugin on AppVeyor

**Comment by janosvitok** [comment]
> P.S. Pity that we've "lost" the GIT history for the whole MIDI plugin just for one test unit :(

Not really. If you check [history for plugins/midi](https://github.com/mcallegari/qlcplus/commits/master/plugins/midi), you'll see all related commits. For individual files, a) blame still works, b) there is git log --follow. 

Unfortunately b) is not (yet) supported on GitHub (I didn't know that until now). I use renames quite often in my daily job, so I didn't suspect a problem...

**Comment by mcallegari** [comment]
Ah, alright, if you click on "history" per folder.
But if you click on a file and hit "history" it is interrupted to the latest move/rename. I know, GitHub fault.
