### ISSUE TITLE
Channel 17 (16) toggles after first switch to operate mode

### ISSUE THREAD

**Issue by siegmund42** [mcallegari/qlcplus#948]
This has been reported quite accurate here: http://www.qlcplus.org/forum/viewtopic.php?f=33&t=10865#p46815

Seems like it is only related to some channels in combination with using an input profile with "generate extra toggle" enabled.
From debugging it seems like channel 17 (16 - if counting from 0) changes its value - and triggers `slotInputValueChanged` on the frame - which causes all the trouble. I was not able to find out why (especially) channel 17 (16) is doing this - and because of a lack of debugging experience in cpp I have no idea how to do that.

**Comment by mdmayfield** [comment]
This is more complex than just channel 17 - when channels in the loopback universe are modified in Simple Desk prior to the first update of other channels, strange combinations of frames are enabled/disabled. Perhaps this is some kind of rounding error?

**Comment by mdmayfield** [comment]
This is on the "back burner" and not a high priority, but recently I've seen a light or two flash on the first time going to Live mode after opening a workspace.

I think that means that this isn't a bug in the VC or frame enable widgets, but rather something deeper in the engine that is causing the very first DMX frame of certain channels to register >0 -- but only for one DMX frame, and only on the first time switching to Live mode after starting QLC or opening a project.

This behavior is deterministic, not random. Unfortunately it seems very hard to understand what causes it and why those particular channels are affected.

For example, channel 17 in universe 3 "flips" momentarily the first time going to Live mode... Unless channel 17's Simple Desk fader was touched before going to Live mode. In that case, a bizarre pattern of other channels "flip" when going to Live mode.

In any case, this only happens once per opening of a project. After the first time, going back and forth between Live and Edit modes does not show this behavior.

**Comment by mcallegari** [comment]
@mdmayfield there's indeed something wrong
I've added a debug message here: https://github.com/mcallegari/qlcplus/blob/master/plugins/loopback/src/loopback.cpp#L200

and it says: Data changed at 16 "0" "0" 
Where 16 is i, "0" is chData[i] and "0" is data[i]
So basically between the if statement and the debug message someone changes the value of data (or chData)

**Comment by mcallegari** [comment]
Alright, this seems to solve the issue.
If you can build from sources, this is the code to be replaced:

```
void Loopback::writeUniverse(quint32 universe, quint32 output, const QByteArray &data)
{
    Q_UNUSED(universe);

    if (!m_outputMap.contains(output))
        return;

    QByteArray &chData = m_channelData[output];

    if (m_inputMap.contains(output))
    {
        quint32 inputUniverse = m_inputMap[output];

        for (int i = 0; i < data.size(); i++)
        {
            if (chData[i] != data[i])
            {
                chData[i] = data[i];
                //qDebug() << "Data changed at" << i << QString::number(chData[i]) << QString::number(data[i]);
                emit valueChanged(inputUniverse, output, i, chData[i]);
            }
        }
    }
}
```
