### ISSUE TITLE
Channel groups in scenes not updated after channel group change

### ISSUE THREAD

**Issue by siegmund42** [mcallegari/qlcplus#960]
This bug has been reported [here](http://www.qlcplus.org/forum/viewtopic.php?p=47328#p47328)

I discovered it by myself for several times. Since it is really annoying and should be working I am willing to fix it. The only question is how to do it.
First, there should be an `updateChannelGroup` method added to the scene class. This is no problem so far.
Second, this new method has to be called every time the channels group is altered (can be done for example in the `slotFixtureRemoved` of the `channelsGroup` class). The problem is to get a reference to the scene. As far as I investigated I did not found a way to get from the `SceneValue` to the corresponding scene (please correct me if there is a way).
So the options are:

- add a reference to the scene to the `SceneValue` class (a lot of work)
- add a reference to corresponding scenes in the `channelsGroup` class (still some work to do and a bit hacky)
- find another way to reach a scene from `SceneValue` class - for example search through all scenes until the right one is found (with a large amount of scenes with lots of values this could lead to performance issues)

Any ideas are appreciated.

**Comment by mcallegari** [comment]
Not a bug. See http://www.qlcplus.org/forum/viewtopic.php?f=20&t=10985&p=47452#p47452
