### ISSUE TITLE
unable to install on fedora

### ISSUE THREAD

**Issue by LaKing** [mcallegari/qlcplus#972]
I cant find anything that solves this issue, ...

```nothing provides libqt4 >= 4.6 needed by qlcplus-qt4-4.10.5b-7.1.x86_64```

Strange thing is I installed qlcplus on fedora already one or twice in the past, ...

**Comment by janosvitok** [comment]
Let's discuss it here: http://www.qlcplus.org/forum/viewforum.php?f=32

Most probably OBS needs to be updated. It seems that there are packages for either qt4 https://www.rpmfind.net/linux/rpm2html/search.php?query=qt4 or qt5: https://www.rpmfind.net/linux/rpm2html/search.php?query=qt5

Please state what Fedora version do you have.

I will close this issue now, and reopen it when we come to a conclusion in the forum.

Thanks!
