### ISSUE TITLE
[Archlinux] Build failed with qlcplus-qt5 aur package

### ISSUE THREAD

**Issue by FabianCernota** [mcallegari/qlcplus#982]
Hi,
getting this build errors on qlcplus-qt5 Arch Package:
https://pastebin.com/HzM820MZ

Any ideas?

Thanks

**Comment by enbyted** [comment]
Snippet from [here][1]. (code that triggers the error)
```c++
if (!m_stream.next_frame)
{
    remaining = m_stream.bufend - m_stream.next_frame;
    memmove (m_input_buf, m_stream.next_frame, remaining); // Line 224
}
```

In this context m_stream.next_frame (`unsigned char const*`) is zero, so `memmove` get's a null pointer as source(which is reported) and remaining doesn't change. I'm not sure what the logic should be here, but it's surprising that it hasn't triggered segfaults nor compilation errors for anyone else.

What version of g++ are you using? (output of `g++ -v`).

[1]: https://github.com/mcallegari/qlcplus/blob/master/engine/audio/plugins/mad/audiodecoder_mad.cpp#L224

**Comment by FabianCernota** [comment]
gcc-Version 7.1.1 20170516 (GCC)

**Comment by enbyted** [comment]
It appears that g++ [enchanced null argument checks (look for -Wnonnull)][1] in 7.x branch and reports a genuine bug in program logic.
If you want you can try building QLC with g++ 4.9 for example.

As far as this bug is concerned let's wait for someone who actually knows how this decoder works, probably @mcallegari, since nobody else has touched this class.

[1]: https://gcc.gnu.org/gcc-7/changes.html

**Comment by janosvitok** [comment]
After looking at the code and history I found this:

The code in question is heavily based on qmmp, see https://sourceforge.net/p/qmmp-dev/code/HEAD/tree/branches/qmmp-1.2/src/plugins/Input/mad/decoder_mad.cpp#l252

The same problem is still in the qmmp code.

My guess is that the code should look like:

```c++
if (!m_stream.next_frame)
{
    remaining = m_stream.bufend - m_stream.buffer;
    memmove (m_input_buf, m_stream.buffer, remaining); // Line 224
}
```

**Comment by enbyted** [comment]
@janosvitok Yes, that's what I'm thinking too, but if this wasn't ever reported as causing segfaults maybe it's dead code?

**Comment by janosvitok** [comment]
I've reported this upstream: https://sourceforge.net/p/qmmp-dev/tickets/923/

It may be dead code since it's guarded by 
```
 if (m_stream.error == MAD_ERROR_BUFLEN || !m_stream.buffer)
```

**Comment by enbyted** [comment]
Yes, that means that your proposed change may lead to null pointer dereference too, since `m_stream.buffer` being null is one of entry conditions.
I don't know much about this and don't have time currently to study the code, so I'm leaving this issue. I won't be able to help much more (unless it's still open next week, then I'll take a deeper look).

**Comment by janosvitok** [comment]
You are right.
This is the source of the code: https://sourceforge.net/p/qmmp-dev/code/495/ 
Since it's from 2008, chances are high that the code does not get executed...

**Comment by mcallegari** [comment]
Or more likely, it's a copy&paste error.
The meaning of that block code is: if there is not enough loaded data, load more.
It should be:
```
if (!m_stream.next_frame)
{
    remaining = m_stream.bufend - m_stream.this_frame;
    memmove (m_input_buf, m_stream.this_frame, remaining);
}
```
How do I know it ? See below at https://github.com/mcallegari/qlcplus/blob/master/engine/audio/plugins/mad/audiodecoder_mad.cpp#L244

**Comment by mcallegari** [comment]
Committed 73b7523541d605825af729f542426cd1f70ba746
Please let me know if Arch is happy now.

**Comment by luxcapto** [comment]
Arch is happy now. Both qlcplus and qlcplus-qt5 showed the same error when building from AUR. I built from source using master branch and it compiles, installs, and runs.

**Comment by janosvitok** [comment]
qmmp came up with a different solution:
https://sourceforge.net/p/qmmp-dev/code/7250/
