### ISSUE TITLE
Speed 255 is actually half speed

### ISSUE THREAD

**Issue by zoell** [mcallegari/qlcplus#984]
Hi,

I have this light http://www.lixada.com/stage-lighting-effect-422/p-l0581au.html
CH1 is a function channel, so when I set it to strobe mode (value 201-255), and set the CH3 (speed) to 255, it is not as fast as it should be. Like with Freestyler it is really really fast with value 255 but with QLC+ it is like at half speed.

I am using an uDMX USB. Not sure if this is a bug/known issue/configuration issue? I am using everything at default settings.

Thanks,

**Comment by mcallegari** [comment]
Since you totally ignored the message that appeared when you opened this, I am closing it.
Please post in the forums like everybody else.

**Comment by zoell** [comment]
Are you waiting for bug reports in a forum? right.

**Comment by mcallegari** [comment]
Yes I do. This area is for developers.
And who says this is a bug, you ?

**Comment by zoell** [comment]
Yes, sorry about that. I just thought because with ArtNet it is working fine, and other softwares with uDMX are working fine. No issue, it is ok with ArtNet for me.
