### ISSUE TITLE
[VC] Speed Dial can't control the speed of an EFX started by a XY Pad

### ISSUE THREAD

**Issue by dreamsinmotion** [mcallegari/qlcplus#990]
This issue seems to be forgotten but still exist.

When i trigger a efx movement in the xy pad and i make a change with the speeddial, the change is not perceived.

http://www.qlcplus.org/forum/viewtopic.php?t=9535

**Comment by mcallegari** [comment]
That's because XY Pad doesn't run the original EFX, but makes a copy of it.
https://github.com/mcallegari/qlcplus/blob/master/ui/src/virtualconsole/vcxypad.cpp#L697
Otherwise, whenever you change something in the pad, the EFX would be edited permanently.

This needs to be reviewed in deep.

**Comment by mcallegari** [comment]
Should be fixed now. Please check version 4.11.1.85 [over here](http://www.qlcplus.org/forum/viewtopic.php?f=12&t=3135)

**Comment by dreamsinmotion** [comment]
@mcallegari Yes it works fine now, thanks!
