### ISSUE TITLE
automatic detection for binding gamepad to XYpad doesn't work correct?

### ISSUE THREAD

**Issue by neutrinopower** [mcallegari/qlcplus#993]
I recognized this issue since the first try at ~2015 on my old 32bit laptop with archlinux and kde, now I tried it one more time with newest archlinux 4.12.8 and kde 17.0.3 and qlcplus 4.11.1 from git:
If I bind the gamepad or joystick "sliders" to a xy-pad with auto-detection on one slider at a time, often the second slider (y) toggle sometimes to the same axes which I move at the input-device. Then I turn the auto-detection off and for the other slider (y) on. But sometimes now the first slider (x) which should stay fix, toggles to the axes which I'am moving actually.
So it ist often tricky to configure the xy-pad to two different sliders of the gamepad or joystick with auto-detection. Even if I use an profile or not for the input-device.
Can someone confirm this issue?
(Now I describe in another Issue why I have to bind the xy-pad more times than I should have to..)

**Comment by mcallegari** [comment]
Have you read this before posting here ?

> If you are a developer, you are supposed to have built QLC+ from sources, and started to debug the issue you have found.
> 
> Therefore, please provide a crash log or references to the code that are supposed to help the QLC+ developers to resolve the issue.

**Comment by mcallegari** [comment]
Closing, for these reasons:
- you ignored the template message when opening a GitHub issue
- this is not a developer report and it's in any case incomplete (e.g. missing make/model of the mentioned joystick)
- you THINK your joystick emits only one axis at the time when you move it, but you have no proof of that. Most likely both axes are always transmitted

Therefore: write in the forums like everybody else
