### ISSUE TITLE
qlcplus forgets profile-selection of input/output devices at saving project when device are disconnected

### ISSUE THREAD

**Issue by neutrinopower** [mcallegari/qlcplus#994]
I saw following issue last time on archlinux 4.12.8, kde 17.04.3 and qlcplus 4.11.1 compiled from git (and earlier with older qlc+ versions):

Some times I want to change a qlc-project without having all in reality attached input/output-devices connected at the editing because some devices I don't have all the time in my reach.
The first time I start qlcplus and the project without some attached device it isn't anymore in input/output-allocation-tab of course, but the attached profile of the unavailable device is still selected.
If I now save the project-file and then the next (second) time start the qlc-project the profile is yet unselected. I expect that qlcplus keep the selected profiles even without connected devices. Also in the side-effect you shouldn't have to rebind the gamepad/joystick-sliders to the xy-pads everytime when you start qlcplus-project with all input-devices after editing without those in reality attached devices.
One more problem is that if you don't rebind the sliders's to xy-pads qlcplus has forgotten after reselecting the previous profile the "relative"-movements-setting of the gamepad/joystick and does "absolute-movement" even it is correctly in profile stored.
(After reslecting the profiles Qlcplus also forgets the bindings of buttons and sliders in second, thirds and following pages but the first page. The names of the buttons as decribed in profile will not be displayd correctly any more? But maybe I have to test it out more before describing. Or this is one more side-effect?)

**Comment by mcallegari** [comment]
Since this was not a developer report, next time write in the QLC+ forums like everybody else.
